use serde_json::Value;
use std::{
    env,
    ffi::OsString,
    fs, io,
    path::{Path, PathBuf},
    process::{self, Command},
};

fn main() {
    let args = match Args::parse(env::args_os().skip(1)) {
        Ok(args) => args,
        Err(message) => {
            eprintln!("{message}");
            print_usage();
            process::exit(2);
        }
    };

    if args.help {
        print_usage();
        return;
    }

    if let Err(error) = generate(args) {
        eprintln!("failed to generate Python UniFFI package: {error}");
        process::exit(1);
    }
}

#[derive(Debug)]
struct Args {
    cdylib: Option<PathBuf>,
    package_dir: PathBuf,
    help: bool,
}

impl Args {
    fn parse(values: impl Iterator<Item = OsString>) -> Result<Self, String> {
        let mut cdylib = None;
        let mut package_dir = default_package_dir();
        let mut help = false;
        let mut values = values.peekable();

        while let Some(value) = values.next() {
            let Some(value) = value.to_str() else {
                return Err("arguments must be valid Unicode paths".to_string());
            };

            match value {
                "--cdylib" => {
                    cdylib = Some(next_path(&mut values, "--cdylib")?);
                }
                "--package-dir" => {
                    package_dir = next_path(&mut values, "--package-dir")?;
                }
                "-h" | "--help" => {
                    help = true;
                }
                other => return Err(format!("unknown argument: {other}")),
            }
        }

        Ok(Self {
            cdylib,
            package_dir,
            help,
        })
    }
}

fn next_path(
    values: &mut std::iter::Peekable<impl Iterator<Item = OsString>>,
    flag: &str,
) -> Result<PathBuf, String> {
    values
        .next()
        .map(PathBuf::from)
        .ok_or_else(|| format!("{flag} requires a path"))
}

fn generate(args: Args) -> Result<(), Box<dyn std::error::Error>> {
    let cdylib = args.cdylib.unwrap_or_else(default_cdylib_path);
    if !cdylib.is_file() {
        return Err(format!(
            "cdylib not found at {}. Build an explicit merman-uniffi artifact profile first, or pass --cdylib.",
            cdylib.display()
        )
        .into());
    }

    let module_dir = args.package_dir.join("src").join("merman");
    fs::create_dir_all(&module_dir)?;
    ensure_init_file(&module_dir)?;
    fs::write(
        module_dir.join("_abi.py"),
        merman_uniffi::MERMAN_UNIFFI_PYTHON_ABI_MODULE,
    )?;

    uniffi::generate(uniffi::GenerateOptions {
        languages: vec![uniffi::TargetLanguage::Python],
        source: utf8_path(&cdylib).into(),
        out_dir: utf8_path(&module_dir).into(),
        config_override: None,
        format: false,
        crate_filter: Some("merman_uniffi".to_string()),
        metadata_no_deps: false,
    })?;

    let cdylib_name = cdylib
        .file_name()
        .ok_or_else(|| format!("cdylib path has no file name: {}", cdylib.display()))?;
    let copied_cdylib = module_dir.join(cdylib_name);
    fs::copy(&cdylib, &copied_cdylib)?;

    println!("generated Python UniFFI module in {}", module_dir.display());
    println!("copied native library to {}", copied_cdylib.display());
    Ok(())
}

fn ensure_init_file(module_dir: &Path) -> io::Result<()> {
    fs::write(
        module_dir.join("_runtime_contract.py"),
        PYTHON_RUNTIME_CONTRACT_MODULE,
    )?;
    let init = module_dir.join("__init__.py");
    if !init.exists() {
        fs::write(init, PYTHON_PACKAGE_INIT)?;
        return Ok(());
    }

    let current = fs::read_to_string(&init)?;
    if is_managed_init_file(&current) && current != PYTHON_PACKAGE_INIT {
        fs::write(init, PYTHON_PACKAGE_INIT)?;
    }

    Ok(())
}

const PYTHON_PACKAGE_INIT_MARKER: &str = "# Generated by `cargo run -p merman-uniffi --example generate_python_package`; do not edit by hand.";
const PYTHON_RUNTIME_CONTRACT_MODULE: &str = include_str!("../python/runtime_contract.py");

const PYTHON_PACKAGE_INIT: &str = concat!(
    "\"\"\"Python package shim for generated merman UniFFI bindings.\"\"\"\n",
    "# Generated by `cargo run -p merman-uniffi --example generate_python_package`; do not edit by hand.",
    "\n\n",
    "from ._abi import (\n",
    "    ABI_VERSION,\n",
    "    TEXT_MEASUREMENT_OPERATIONS,\n",
    "    TEXT_MEASUREMENT_RESULT_KINDS,\n",
    "    AbiVersionMismatch,\n",
    "    require_abi_version,\n",
    ")\n\n",
    "from ._runtime_contract import (\n",
    "    MermanRuntimeContract,\n",
    "    MermanRuntimeContractError,\n",
    "    MermanRuntimeFeatures,\n",
    "    MermanTextMeasurementCapabilities,\n",
    "    get_runtime_contract,\n",
    ")\n\n",
    "try:\n",
    "    from .merman_uniffi import (\n",
    "        MermanAsciiCapability,\n",
    "        MermanAsciiCapabilityEvidence,\n",
    "        MermanDiagramFamilyCapability,\n",
    "        MermanEngine,\n",
    "        MermanError,\n",
    "        MermanLintRuleCatalogEntry,\n",
    "        MermanReusableEngine,\n",
    "        MermanTextDirection,\n",
    "        MermanTextMeasureRequest,\n",
    "        MermanTextMeasureResult,\n",
    "        MermanTextMeasurementOperation,\n",
    "        MermanTextMeasurementPhase,\n",
    "        MermanTextMeasurementResultKind,\n",
    "        MermanTextMeasurer,\n",
    "        MermanTextWhiteSpace,\n",
    "        MermanTextWrapMode,\n",
    "        MermanValidationResult,\n",
    "    )\n",
    "except ModuleNotFoundError as exc:\n",
    "    if exc.name == f\"{__name__}.merman_uniffi\":\n",
    "        raise ImportError(\n",
    "            \"Generated merman UniFFI bindings are missing. \"\n",
    "            \"Build an explicit merman-uniffi artifact profile, then run \"\n",
    "            \"`cargo run -p merman-uniffi --no-default-features --features bindgen-smoke --example \"\n",
    "            \"generate_python_package -- --package-dir platforms/python/merman`.\"\n",
    "        ) from exc\n",
    "    raise\n\n",
    "__all__ = [\n",
    "    \"ABI_VERSION\",\n",
    "    \"AbiVersionMismatch\",\n",
    "    \"TEXT_MEASUREMENT_OPERATIONS\",\n",
    "    \"TEXT_MEASUREMENT_RESULT_KINDS\",\n",
    "    \"MermanAsciiCapability\",\n",
    "    \"MermanAsciiCapabilityEvidence\",\n",
    "    \"MermanDiagramFamilyCapability\",\n",
    "    \"MermanEngine\",\n",
    "    \"MermanError\",\n",
    "    \"MermanLintRuleCatalogEntry\",\n",
    "    \"MermanReusableEngine\",\n",
    "    \"MermanRuntimeContract\",\n",
    "    \"MermanRuntimeContractError\",\n",
    "    \"MermanRuntimeFeatures\",\n",
    "    \"MermanTextDirection\",\n",
    "    \"MermanTextMeasureRequest\",\n",
    "    \"MermanTextMeasureResult\",\n",
    "    \"MermanTextMeasurementOperation\",\n",
    "    \"MermanTextMeasurementPhase\",\n",
    "    \"MermanTextMeasurementResultKind\",\n",
    "    \"MermanTextMeasurementCapabilities\",\n",
    "    \"MermanTextMeasurer\",\n",
    "    \"MermanTextWhiteSpace\",\n",
    "    \"MermanTextWrapMode\",\n",
    "    \"MermanValidationResult\",\n",
    "    \"get_runtime_contract\",\n",
    "    \"require_abi_version\",\n",
    "]\n",
);

fn is_managed_init_file(contents: &str) -> bool {
    contents.contains(PYTHON_PACKAGE_INIT_MARKER)
        || contents.starts_with("\"\"\"Generated merman UniFFI package shim.\"\"\"\n")
        || contents.starts_with(
            "\"\"\"Python package shim for generated merman UniFFI bindings.\"\"\"\n\n",
        )
}

fn default_package_dir() -> PathBuf {
    workspace_root()
        .join("platforms")
        .join("python")
        .join("merman")
}

fn default_cdylib_path() -> PathBuf {
    cargo_target_dir()
        .unwrap_or_else(|_| workspace_root().join("target"))
        .join("debug")
        .join(cdylib_filename())
}

fn cargo_target_dir() -> Result<PathBuf, Box<dyn std::error::Error>> {
    let cargo = env::var("CARGO").unwrap_or_else(|_| "cargo".to_string());
    let output = Command::new(cargo)
        .current_dir(workspace_root())
        .args(["metadata", "--format-version=1", "--no-deps"])
        .output()?;

    if !output.status.success() {
        return Err(format!(
            "cargo metadata failed: {}",
            String::from_utf8_lossy(&output.stderr)
        )
        .into());
    }

    let metadata: Value = serde_json::from_slice(&output.stdout)?;
    let target_directory = metadata
        .get("target_directory")
        .and_then(Value::as_str)
        .ok_or("cargo metadata target_directory missing")?;
    Ok(PathBuf::from(target_directory))
}

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .expect("merman-uniffi should live under workspace/crates")
        .to_path_buf()
}

fn cdylib_filename() -> &'static str {
    if cfg!(windows) {
        "merman_uniffi.dll"
    } else if cfg!(target_os = "macos") {
        "libmerman_uniffi.dylib"
    } else {
        "libmerman_uniffi.so"
    }
}

fn utf8_path(path: &Path) -> String {
    path.to_str()
        .unwrap_or_else(|| panic!("path is not valid UTF-8: {}", path.display()))
        .to_string()
}

fn print_usage() {
    eprintln!(
        "usage: cargo run -p merman-uniffi --no-default-features --features bindgen-smoke --example generate_python_package -- [--cdylib PATH] [--package-dir PATH]"
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    fn assert_text_measurement_protocol_exports(init: &str) {
        for name in [
            "MermanTextMeasurementOperation",
            "MermanTextMeasurementPhase",
            "MermanTextMeasurementResultKind",
        ] {
            assert!(
                init.contains(&format!("        {name},\n")),
                "generated package shim must import {name}"
            );
            assert!(
                init.contains(&format!("    \"{name}\",\n")),
                "generated package shim must include {name} in __all__"
            );
        }
    }

    #[test]
    fn ensure_init_file_creates_missing_managed_shim() {
        let temp = tempfile::tempdir().expect("create tempdir");
        let module_dir = temp.path().join("merman");
        fs::create_dir_all(&module_dir).expect("create module dir");

        ensure_init_file(&module_dir).expect("create init file");

        let init = fs::read_to_string(module_dir.join("__init__.py")).expect("read init file");
        assert!(init.contains(PYTHON_PACKAGE_INIT_MARKER));
        assert!(init.contains("MermanTextMeasurer"));
        assert!(init.contains("MermanLintRuleCatalogEntry"));
        assert!(init.contains("get_runtime_contract"));
        assert_eq!(
            fs::read_to_string(module_dir.join("_runtime_contract.py"))
                .expect("read runtime contract helper"),
            PYTHON_RUNTIME_CONTRACT_MODULE
        );
        assert_text_measurement_protocol_exports(&init);
    }

    #[test]
    fn ensure_init_file_refreshes_stale_generated_shim() {
        let temp = tempfile::tempdir().expect("create tempdir");
        let module_dir = temp.path().join("merman");
        fs::create_dir_all(&module_dir).expect("create module dir");
        fs::write(
            module_dir.join("__init__.py"),
            concat!(
                "\"\"\"Generated merman UniFFI package shim.\"\"\"\n",
                "from .merman_uniffi import (\n",
                "    MermanEngine,\n",
                ")\n\n",
                "__all__ = [\n",
                "    \"MermanEngine\",\n",
                "]\n",
            ),
        )
        .expect("write stale init");

        ensure_init_file(&module_dir).expect("refresh init file");

        let init = fs::read_to_string(module_dir.join("__init__.py")).expect("read init file");
        assert_eq!(init, PYTHON_PACKAGE_INIT);
        assert!(init.contains("MermanTextMeasureRequest"));
        assert!(init.contains("MermanTextMeasureResult"));
        assert!(init.contains("MermanRuntimeContract"));
        assert_text_measurement_protocol_exports(&init);
    }

    #[test]
    fn ensure_init_file_preserves_custom_unmarked_shim() {
        let temp = tempfile::tempdir().expect("create tempdir");
        let module_dir = temp.path().join("merman");
        fs::create_dir_all(&module_dir).expect("create module dir");
        let custom = "\"\"\"Custom package code.\"\"\"\nCUSTOM = True\n";
        fs::write(module_dir.join("__init__.py"), custom).expect("write custom init");

        ensure_init_file(&module_dir).expect("preserve custom init file");

        let init = fs::read_to_string(module_dir.join("__init__.py")).expect("read init file");
        assert_eq!(init, custom);
    }

    #[test]
    fn checked_in_python_support_files_match_the_generator() {
        let module_dir = workspace_root()
            .join("platforms")
            .join("python")
            .join("merman")
            .join("src")
            .join("merman");
        assert_eq!(
            fs::read_to_string(module_dir.join("__init__.py")).expect("read package shim"),
            PYTHON_PACKAGE_INIT
        );
        assert_eq!(
            fs::read_to_string(module_dir.join("_runtime_contract.py"))
                .expect("read runtime contract helper"),
            PYTHON_RUNTIME_CONTRACT_MODULE
        );
    }
}
