name: merman
description: Flutter and Dart FFI bindings for merman headless Mermaid rendering.
version: 0.8.0-alpha.6
homepage: https://github.com/Latias94/merman
repository: https://github.com/Latias94/merman
issue_tracker: https://github.com/Latias94/merman/issues
documentation: https://github.com/Latias94/merman/blob/main/docs/bindings/FLUTTER_DART_FFI.md
topics:
  - mermaid
  - ffi
  - flutter
  - svg
  - diagrams

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  code_assets: ^1.0.0
  ffi: ^2.1.4
  hooks: ^1.0.0

dev_dependencies:
  ffigen: ^20.1.1
