---
title: git-graph
---
gitGraph TB:
commit id:"root" msg:"功能完成" tag:"v1" type:HIGHLIGHT
branch feature/test order:2
checkout feature/test
switch main
merge feature/test tag:"merged" id:"merge-1" type:REVERSE
cherry-pick id:"root" parent:"base" tag:"backport"
