---
title: sequence
---
sequenceDiagram
actor U as 用户
participant API@{ "type": "boundary" } as Checkout API
autonumber 10 5
U->>+API: start
alt accepted
  Note over U,API: processing
else rejected
  API-->>-U: complete
end
