---
title: state
---
stateDiagram-v2
state "Ready 世界" as ready
state Choice <<choice>>
ready --> Choice:::hot: decide#colon; now
note right of Choice: Review
note left of ready
  Check again
end note
classDef hot fill:#f00,color:white
class ready,Choice hot
style Choice fill:#fff
direction LR
scale 640 width
