---
title: xychart
---
xychart-beta horizontal
title "`**Revenue** by quarter`"
x-axis "Quarter" [Q1, "Q2"]
y-axis "USD" 0 --> 100
line "Forecast" [25 "Launch", 90]
bar [20, 80]
accTitle: Revenue overview
