#import "context.typ": typst-layout
#import "image.typ": result-image, svg-bytes-or-panic
#import "options.typ": build-binding-options, context-host-theme, options-bytes
#import "plugin.typ": merman-plugin
#import "source.typ": source-text-value

#let render-svg-result(
  source,
  options: none,
  profile: none,
  typography: none,
  context-host-theme: none,
  site-config: none,
  host-theme: none,
  theme: none,
  theme-name: none,
  base-theme: none,
  pipeline: none,
  id: none,
  diagram-id: none,
  background: none,
  layout: none,
  scoped-css: none,
  css-override-policy: none,
  drop-native-duplicate-fallbacks: none,
  text-measurer: none,
  math-renderer: none,
  viewport-width: none,
  viewport-height: none,
  fixed-today: none,
  fixed-local-offset-minutes: none,
) = {
  let source-text = source-text-value(source)
  let binding-options = build-binding-options(
    options: options,
    profile: profile,
    typography: typography,
    context-host-theme: context-host-theme,
    site-config: site-config,
    host-theme: host-theme,
    theme: theme,
    theme-name: theme-name,
    base-theme: base-theme,
    pipeline: pipeline,
    id: id,
    diagram-id: diagram-id,
    background: background,
    layout: layout,
    scoped-css: scoped-css,
    css-override-policy: css-override-policy,
    drop-native-duplicate-fallbacks: drop-native-duplicate-fallbacks,
    text-measurer: text-measurer,
    math-renderer: math-renderer,
    viewport-width: viewport-width,
    viewport-height: viewport-height,
    fixed-today: fixed-today,
    fixed-local-offset-minutes: fixed-local-offset-minutes,
  )

  json(merman-plugin.render_svg_json(bytes(source-text), options-bytes(binding-options)))
}

#let render-svg-bytes(..args) = {
  svg-bytes-or-panic(render-svg-result(..args))
}

#let validate-payload(
  source,
  options: none,
  profile: none,
  typography: none,
  site-config: none,
  host-theme: none,
  theme: none,
  theme-name: none,
  base-theme: none,
  pipeline: none,
  id: none,
  diagram-id: none,
  background: none,
  layout: none,
  scoped-css: none,
  css-override-policy: none,
  drop-native-duplicate-fallbacks: none,
  text-measurer: none,
  math-renderer: none,
  viewport-width: none,
  viewport-height: none,
  fixed-today: none,
  fixed-local-offset-minutes: none,
) = {
  let source-text = source-text-value(source)
  let binding-options = build-binding-options(
    options: options,
    profile: profile,
    typography: typography,
    site-config: site-config,
    host-theme: host-theme,
    theme: theme,
    theme-name: theme-name,
    base-theme: base-theme,
    pipeline: pipeline,
    id: id,
    diagram-id: diagram-id,
    background: background,
    layout: layout,
    scoped-css: scoped-css,
    css-override-policy: css-override-policy,
    drop-native-duplicate-fallbacks: drop-native-duplicate-fallbacks,
    text-measurer: text-measurer,
    math-renderer: math-renderer,
    viewport-width: viewport-width,
    viewport-height: viewport-height,
    fixed-today: fixed-today,
    fixed-local-offset-minutes: fixed-local-offset-minutes,
  )

  json(merman-plugin.validate_json(bytes(source-text), options-bytes(binding-options)))
}

#let mermaid-result(
  source,
  options: none,
  profile: none,
  typography: none,
  site-config: none,
  host-theme: none,
  theme: none,
  theme-name: none,
  base-theme: none,
  pipeline: none,
  id: none,
  diagram-id: none,
  background: none,
  layout: none,
  scoped-css: none,
  css-override-policy: none,
  drop-native-duplicate-fallbacks: none,
  text-measurer: none,
  math-renderer: none,
  viewport-width: none,
  viewport-height: none,
  fixed-today: none,
  fixed-local-offset-minutes: none,
) = render-svg-result(
  source,
  options: options,
  profile: profile,
  typography: typography,
  site-config: site-config,
  host-theme: host-theme,
  theme: theme,
  theme-name: theme-name,
  base-theme: base-theme,
  pipeline: pipeline,
  id: id,
  diagram-id: diagram-id,
  background: background,
  layout: layout,
  scoped-css: scoped-css,
  css-override-policy: css-override-policy,
  drop-native-duplicate-fallbacks: drop-native-duplicate-fallbacks,
  text-measurer: text-measurer,
  math-renderer: math-renderer,
  viewport-width: viewport-width,
  viewport-height: viewport-height,
  fixed-today: fixed-today,
  fixed-local-offset-minutes: fixed-local-offset-minutes,
)

#let mermaid-svg(
  source,
  options: none,
  profile: none,
  typography: none,
  site-config: none,
  host-theme: none,
  theme: none,
  theme-name: none,
  base-theme: none,
  pipeline: none,
  id: none,
  diagram-id: none,
  background: none,
  layout: none,
  scoped-css: none,
  css-override-policy: none,
  drop-native-duplicate-fallbacks: none,
  text-measurer: none,
  math-renderer: none,
  viewport-width: none,
  viewport-height: none,
  fixed-today: none,
  fixed-local-offset-minutes: none,
) = {
  str(render-svg-bytes(
    source,
    options: options,
    profile: profile,
    typography: typography,
    site-config: site-config,
    host-theme: host-theme,
    theme: theme,
    theme-name: theme-name,
    base-theme: base-theme,
    pipeline: pipeline,
    id: id,
    diagram-id: diagram-id,
    background: background,
    layout: layout,
    scoped-css: scoped-css,
    css-override-policy: css-override-policy,
    drop-native-duplicate-fallbacks: drop-native-duplicate-fallbacks,
    text-measurer: text-measurer,
    math-renderer: math-renderer,
    viewport-width: viewport-width,
    viewport-height: viewport-height,
    fixed-today: fixed-today,
    fixed-local-offset-minutes: fixed-local-offset-minutes,
  ))
}

#let validate-mermaid(
  source,
  options: none,
  profile: none,
  typography: none,
  site-config: none,
  host-theme: none,
  theme: none,
  theme-name: none,
  base-theme: none,
  pipeline: none,
  id: none,
  diagram-id: none,
  background: none,
  layout: none,
  scoped-css: none,
  css-override-policy: none,
  drop-native-duplicate-fallbacks: none,
  text-measurer: none,
  math-renderer: none,
  viewport-width: none,
  viewport-height: none,
  fixed-today: none,
  fixed-local-offset-minutes: none,
) = validate-payload(
  source,
  options: options,
  profile: profile,
  typography: typography,
  site-config: site-config,
  host-theme: host-theme,
  theme: theme,
  theme-name: theme-name,
  base-theme: base-theme,
  pipeline: pipeline,
  id: id,
  diagram-id: diagram-id,
  background: background,
  layout: layout,
  scoped-css: scoped-css,
  css-override-policy: css-override-policy,
  drop-native-duplicate-fallbacks: drop-native-duplicate-fallbacks,
  text-measurer: text-measurer,
  math-renderer: math-renderer,
  viewport-width: viewport-width,
  viewport-height: viewport-height,
  fixed-today: fixed-today,
  fixed-local-offset-minutes: fixed-local-offset-minutes,
)

#let render-image(
  source,
  options: none,
  profile: none,
  typography: none,
  context-host-theme: none,
  site-config: none,
  host-theme: none,
  theme: none,
  theme-name: none,
  base-theme: none,
  pipeline: none,
  id: none,
  diagram-id: none,
  background: none,
  layout: none,
  scoped-css: none,
  css-override-policy: none,
  drop-native-duplicate-fallbacks: none,
  text-measurer: none,
  math-renderer: none,
  viewport-width: none,
  viewport-height: none,
  fixed-today: none,
  fixed-local-offset-minutes: none,
  width: auto,
  height: auto,
  fit: "contain",
  scale: none,
  alt: none,
  error-mode: "panic",
) = {
  let result = render-svg-result(
    source,
    options: options,
    profile: profile,
    typography: typography,
    context-host-theme: context-host-theme,
    site-config: site-config,
    host-theme: host-theme,
    theme: theme,
    theme-name: theme-name,
    base-theme: base-theme,
    pipeline: pipeline,
    id: id,
    diagram-id: diagram-id,
    background: background,
    layout: layout,
    scoped-css: scoped-css,
    css-override-policy: css-override-policy,
    drop-native-duplicate-fallbacks: drop-native-duplicate-fallbacks,
    text-measurer: text-measurer,
    math-renderer: math-renderer,
    viewport-width: viewport-width,
    viewport-height: viewport-height,
    fixed-today: fixed-today,
    fixed-local-offset-minutes: fixed-local-offset-minutes,
  )
  result-image(result, width, height, fit, alt, scale, error-mode)
}

#let render-image-with-document-context(
  source,
  options: none,
  profile: none,
  typography: none,
  site-config: none,
  host-theme: none,
  theme: none,
  theme-name: none,
  base-theme: none,
  pipeline: none,
  id: none,
  diagram-id: none,
  background: none,
  layout: none,
  scoped-css: none,
  css-override-policy: none,
  drop-native-duplicate-fallbacks: none,
  text-measurer: none,
  math-renderer: none,
  viewport-width: none,
  viewport-height: none,
  fixed-today: none,
  fixed-local-offset-minutes: none,
  width: auto,
  height: auto,
  fit: "contain",
  scale: none,
  alt: none,
  error-mode: "panic",
) = context {
  let inferred-host-theme = context-host-theme(text.font, text.size)
  if layout != none or viewport-width != none {
    let result = render-svg-result(
      source,
      options: options,
      profile: profile,
      typography: typography,
      context-host-theme: inferred-host-theme,
      site-config: site-config,
      host-theme: host-theme,
      theme: theme,
      theme-name: theme-name,
      base-theme: base-theme,
      pipeline: pipeline,
      id: id,
      diagram-id: diagram-id,
      background: background,
      layout: layout,
      scoped-css: scoped-css,
      css-override-policy: css-override-policy,
      drop-native-duplicate-fallbacks: drop-native-duplicate-fallbacks,
      text-measurer: text-measurer,
      math-renderer: math-renderer,
      viewport-width: viewport-width,
      viewport-height: viewport-height,
      fixed-today: fixed-today,
      fixed-local-offset-minutes: fixed-local-offset-minutes,
    )
    result-image(result, width, height, fit, alt, scale, error-mode)
  } else {
    typst-layout(size => {
      let result = render-svg-result(
        source,
        options: options,
        profile: profile,
        typography: typography,
        context-host-theme: inferred-host-theme,
        site-config: site-config,
        host-theme: host-theme,
        theme: theme,
        theme-name: theme-name,
        base-theme: base-theme,
        pipeline: pipeline,
        id: id,
        diagram-id: diagram-id,
        background: background,
        layout: layout,
        scoped-css: scoped-css,
        css-override-policy: css-override-policy,
        drop-native-duplicate-fallbacks: drop-native-duplicate-fallbacks,
        text-measurer: text-measurer,
        math-renderer: math-renderer,
        viewport-width: size.width / 1pt,
        viewport-height: viewport-height,
        fixed-today: fixed-today,
        fixed-local-offset-minutes: fixed-local-offset-minutes,
      )
      result-image(result, width, height, fit, alt, scale, error-mode)
    })
  }
}

#let mermaid(
  source,
  options: none,
  profile: none,
  typography: none,
  site-config: none,
  host-theme: none,
  theme: none,
  theme-name: none,
  base-theme: none,
  pipeline: none,
  id: none,
  diagram-id: none,
  background: none,
  layout: none,
  scoped-css: none,
  css-override-policy: none,
  drop-native-duplicate-fallbacks: none,
  text-measurer: none,
  math-renderer: none,
  viewport-width: none,
  viewport-height: none,
  fixed-today: none,
  fixed-local-offset-minutes: none,
  document-context: false,
  width: auto,
  height: auto,
  fit: "contain",
  scale: none,
  alt: none,
  error-mode: "panic",
) = {
  if document-context {
    render-image-with-document-context(
      source,
      options: options,
      profile: profile,
      typography: typography,
      site-config: site-config,
      host-theme: host-theme,
      theme: theme,
      theme-name: theme-name,
      base-theme: base-theme,
      pipeline: pipeline,
      id: id,
      diagram-id: diagram-id,
      background: background,
      layout: layout,
      scoped-css: scoped-css,
      css-override-policy: css-override-policy,
      drop-native-duplicate-fallbacks: drop-native-duplicate-fallbacks,
      text-measurer: text-measurer,
      math-renderer: math-renderer,
      viewport-width: viewport-width,
      viewport-height: viewport-height,
      fixed-today: fixed-today,
      fixed-local-offset-minutes: fixed-local-offset-minutes,
      width: width,
      height: height,
      fit: fit,
      scale: scale,
      alt: alt,
      error-mode: error-mode,
    )
  } else {
    render-image(
      source,
      options: options,
      profile: profile,
      typography: typography,
      site-config: site-config,
      host-theme: host-theme,
      theme: theme,
      theme-name: theme-name,
      base-theme: base-theme,
      pipeline: pipeline,
      id: id,
      diagram-id: diagram-id,
      background: background,
      layout: layout,
      scoped-css: scoped-css,
      css-override-policy: css-override-policy,
      drop-native-duplicate-fallbacks: drop-native-duplicate-fallbacks,
      text-measurer: text-measurer,
      math-renderer: math-renderer,
      viewport-width: viewport-width,
      viewport-height: viewport-height,
      fixed-today: fixed-today,
      fixed-local-offset-minutes: fixed-local-offset-minutes,
      width: width,
      height: height,
      fit: fit,
      scale: scale,
      alt: alt,
      error-mode: error-mode,
    )
  }
}
