// This file is @generated by `cargo run -p xtask -- gen-text-measurement-protocol`.
// Do not edit it directly; edit `contracts/abi/text-measurement-v1.json` instead.

package io.merman

object MermanTextMeasurementResultKind {
    const val METRICS: Int = 0
    const val LENGTH: Int = 1
    const val HORIZONTAL_EXTENTS: Int = 2
    const val WRAPPED_WITH_RAW_WIDTH: Int = 3

    val ALL: IntArray = intArrayOf(
        METRICS,
        LENGTH,
        HORIZONTAL_EXTENTS,
        WRAPPED_WITH_RAW_WIDTH,
    )

    fun externalName(code: Int): String? = when (code) {
        METRICS -> "metrics"
        LENGTH -> "length"
        HORIZONTAL_EXTENTS -> "horizontal-extents"
        WRAPPED_WITH_RAW_WIDTH -> "wrapped-with-raw-width"
        else -> null
    }
}
