// This file is @generated by `cargo run -p xtask -- gen-resource-contract`.
// Do not edit directly; edit `crates/merman-render/src/resources.rs`.

package io.merman

public enum class MermanResourceProfile(public val id: String) {
    INTERACTIVE("interactive"),
    CONSTRAINED("constrained"),
    TRUSTED_NATIVE("trusted-native"),
    UNBOUNDED_FOR_TRUSTED_INPUT("unbounded-for-trusted-input"),
}

public enum class MermanResourceLimitId(public val id: String, public val overridable: Boolean) {
    MAX_SOURCE_BYTES("max_source_bytes", true),
    MAX_SVG_BYTES("max_svg_bytes", true),
    MAX_SVG_ELEMENTS("max_svg_elements", true),
    MAX_SVG_TREE_DEPTH("max_svg_tree_depth", false),
    MAX_FLOWCHART_NODES("max_flowchart_nodes", true),
    MAX_FLOWCHART_EDGES("max_flowchart_edges", true),
    MAX_FLOWCHART_SUBGRAPHS("max_flowchart_subgraphs", true),
    MAX_CLASS_NODES("max_class_nodes", true),
    MAX_CLASS_EDGES("max_class_edges", true),
    MAX_CLASS_NAMESPACES("max_class_namespaces", true),
    MAX_ZENUML_PARTICIPANTS("max_zenuml_participants", true),
    MAX_ZENUML_STATEMENTS("max_zenuml_statements", true),
    MAX_ZENUML_FRAGMENTS("max_zenuml_fragments", true),
    MAX_VENN_AREAS("max_venn_areas", true),
    MAX_SWIMLANE_LINE_HOP_SEGMENT_PAIRS("max_swimlane_line_hop_segment_pairs", true),
    MAX_LABEL_BYTES("max_label_bytes", true),
}

public class MermanResourceOptionsBuilder(
    private var profile: MermanResourceProfile = MermanResourceProfile.INTERACTIVE) {
    private val limits = linkedMapOf<MermanResourceLimitId, Long>()

    public fun profile(profile: MermanResourceProfile): MermanResourceOptionsBuilder {
        this.profile = profile
        return this
    }

    public fun limit(id: MermanResourceLimitId, value: Long): MermanResourceOptionsBuilder {
        require(id.overridable) { "Resource limit is not overridable: ${id.id}" }
        require(value > 0) { "Resource limit must be positive: ${id.id}" }
        limits[id] = value
        return this
    }

    public fun build(): MermanResourceOptions = MermanResourceOptions(profile, limits.toMap())
}

public data class MermanResourceOptions(
    val profile: MermanResourceProfile,
    val limits: Map<MermanResourceLimitId, Long> = emptyMap(),
) {
    public fun toOptionsJson(): String {
        val sorted = limits.entries.sortedBy { it.key.ordinal }
        val limitJson = sorted.joinToString(",") { "\"${it.key.id}\":${it.value}" }
        val limitsPart = if (sorted.isEmpty()) "" else ",\"limits\":{${limitJson}}"
        return "{\"version\":1,\"resources\":{\"profile\":\"${profile.id}\"${limitsPart}}}"
    }
}
