// This file is @generated by `cargo run -p xtask -- gen-text-measurement-protocol`.
// Do not edit it directly; edit `contracts/abi/text-measurement-v1.json` instead.

package io.merman

object MermanTextMeasurementOperation {
    const val PROTOCOL_VERSION: Int = 1
    const val MEASURE: Int = 0
    const val COMPUTED_LENGTH: Int = 1
    const val BBOX_X: Int = 2
    const val BBOX_X_WITH_ASCII_OVERHANG: Int = 3
    const val TITLE_BBOX_X: Int = 4
    const val SIMPLE_BBOX_WIDTH: Int = 5
    const val RAW_BBOX_WIDTH: Int = 6
    const val TSPAN_BBOX_WIDTH: Int = 7
    const val TSPAN_BBOX_HEIGHT: Int = 8
    const val WRAP_PROBE_BBOX_WIDTH: Int = 9
    const val SIMPLE_BBOX_HEIGHT: Int = 10
    const val WRAPPED: Int = 11
    const val WRAPPED_WITH_RAW_WIDTH: Int = 12
    const val BOUNDING_CLIENT_RECT_WIDTH: Int = 13
    const val CREATE_TEXT_BBOX_Y_OFFSET: Int = 14
    const val MERMAID_CALCULATE_TEXT_DIMENSIONS: Int = 15
    const val CANVAS_MEASURE_TEXT_WIDTH: Int = 16
    const val CREATE_TEXT_MIDDLE_BBOX_Y_OFFSET: Int = 17
    const val RAW_BBOX_HEIGHT: Int = 18

    val ALL: IntArray = intArrayOf(
        MEASURE,
        COMPUTED_LENGTH,
        BBOX_X,
        BBOX_X_WITH_ASCII_OVERHANG,
        TITLE_BBOX_X,
        SIMPLE_BBOX_WIDTH,
        RAW_BBOX_WIDTH,
        TSPAN_BBOX_WIDTH,
        TSPAN_BBOX_HEIGHT,
        WRAP_PROBE_BBOX_WIDTH,
        SIMPLE_BBOX_HEIGHT,
        WRAPPED,
        WRAPPED_WITH_RAW_WIDTH,
        BOUNDING_CLIENT_RECT_WIDTH,
        CREATE_TEXT_BBOX_Y_OFFSET,
        MERMAID_CALCULATE_TEXT_DIMENSIONS,
        CANVAS_MEASURE_TEXT_WIDTH,
        CREATE_TEXT_MIDDLE_BBOX_Y_OFFSET,
        RAW_BBOX_HEIGHT,
    )

    fun externalName(code: Int): String? = when (code) {
        MEASURE -> "measure"
        COMPUTED_LENGTH -> "computed-length"
        BBOX_X -> "bbox-x"
        BBOX_X_WITH_ASCII_OVERHANG -> "bbox-x-with-ascii-overhang"
        TITLE_BBOX_X -> "title-bbox-x"
        SIMPLE_BBOX_WIDTH -> "simple-bbox-width"
        RAW_BBOX_WIDTH -> "raw-bbox-width"
        TSPAN_BBOX_WIDTH -> "tspan-bbox-width"
        TSPAN_BBOX_HEIGHT -> "tspan-bbox-height"
        WRAP_PROBE_BBOX_WIDTH -> "wrap-probe-bbox-width"
        SIMPLE_BBOX_HEIGHT -> "simple-bbox-height"
        WRAPPED -> "wrapped"
        WRAPPED_WITH_RAW_WIDTH -> "wrapped-with-raw-width"
        BOUNDING_CLIENT_RECT_WIDTH -> "bounding-client-rect-width"
        CREATE_TEXT_BBOX_Y_OFFSET -> "create-text-bbox-y-offset"
        MERMAID_CALCULATE_TEXT_DIMENSIONS -> "mermaid-calculate-text-dimensions"
        CANVAS_MEASURE_TEXT_WIDTH -> "canvas-measure-text-width"
        CREATE_TEXT_MIDDLE_BBOX_Y_OFFSET -> "create-text-middle-bbox-y-offset"
        RAW_BBOX_HEIGHT -> "raw-bbox-height"
        else -> null
    }

    fun requiredResultKind(code: Int): Int? = when (code) {
        MEASURE -> MermanTextMeasurementResultKind.METRICS
        COMPUTED_LENGTH -> MermanTextMeasurementResultKind.LENGTH
        BBOX_X -> MermanTextMeasurementResultKind.HORIZONTAL_EXTENTS
        BBOX_X_WITH_ASCII_OVERHANG -> MermanTextMeasurementResultKind.HORIZONTAL_EXTENTS
        TITLE_BBOX_X -> MermanTextMeasurementResultKind.HORIZONTAL_EXTENTS
        SIMPLE_BBOX_WIDTH -> MermanTextMeasurementResultKind.LENGTH
        RAW_BBOX_WIDTH -> MermanTextMeasurementResultKind.LENGTH
        TSPAN_BBOX_WIDTH -> MermanTextMeasurementResultKind.LENGTH
        TSPAN_BBOX_HEIGHT -> MermanTextMeasurementResultKind.LENGTH
        WRAP_PROBE_BBOX_WIDTH -> MermanTextMeasurementResultKind.LENGTH
        SIMPLE_BBOX_HEIGHT -> MermanTextMeasurementResultKind.LENGTH
        WRAPPED -> MermanTextMeasurementResultKind.METRICS
        WRAPPED_WITH_RAW_WIDTH -> MermanTextMeasurementResultKind.WRAPPED_WITH_RAW_WIDTH
        BOUNDING_CLIENT_RECT_WIDTH -> MermanTextMeasurementResultKind.LENGTH
        CREATE_TEXT_BBOX_Y_OFFSET -> MermanTextMeasurementResultKind.LENGTH
        MERMAID_CALCULATE_TEXT_DIMENSIONS -> MermanTextMeasurementResultKind.METRICS
        CANVAS_MEASURE_TEXT_WIDTH -> MermanTextMeasurementResultKind.LENGTH
        CREATE_TEXT_MIDDLE_BBOX_Y_OFFSET -> MermanTextMeasurementResultKind.LENGTH
        RAW_BBOX_HEIGHT -> MermanTextMeasurementResultKind.LENGTH
        else -> null
    }

    fun acceptsSignedLength(code: Int): Boolean = when (code) {
        CREATE_TEXT_BBOX_Y_OFFSET -> true
        CREATE_TEXT_MIDDLE_BBOX_Y_OFFSET -> true
        else -> false
    }
}
