// This file is @generated by `cargo run -p xtask -- gen-text-measurement-protocol`.
// Do not edit it directly; edit `contracts/abi/text-measurement-v1.json` instead.

package io.merman

enum class MermanTextWrapMode(val code: Int, val externalName: String) {
    SVG_LIKE(0, "svg-like"),
    SVG_LIKE_SINGLE_RUN(1, "svg-like-single-run"),
    HTML_LIKE(2, "html-like");

    companion object {
        @JvmStatic
        fun fromCode(code: Int): MermanTextWrapMode? = entries.firstOrNull { it.code == code }
    }
}

enum class MermanTextDirection(val code: Int, val externalName: String) {
    AUTO(0, "auto");

    companion object {
        @JvmStatic
        fun fromCode(code: Int): MermanTextDirection? = entries.firstOrNull { it.code == code }
    }
}

enum class MermanTextWhiteSpace(val code: Int, val externalName: String) {
    NORMAL(0, "normal"),
    NOWRAP(1, "nowrap"),
    BREAK_SPACES(2, "break-spaces");

    companion object {
        @JvmStatic
        fun fromCode(code: Int): MermanTextWhiteSpace? = entries.firstOrNull { it.code == code }
    }
}

enum class MermanTextMeasurementPhase(val code: Int, val externalName: String) {
    LAYOUT(0, "layout"),
    WRAP(1, "wrap"),
    SVG_BBOX(2, "svg-bbox"),
    COMPUTED_LENGTH(3, "computed-length");

    companion object {
        @JvmStatic
        fun fromCode(code: Int): MermanTextMeasurementPhase? = entries.firstOrNull { it.code == code }
    }
}
