// This file is @generated by `cargo run -p xtask -- gen-resource-contract`.
// Do not edit directly; edit the authoritative descriptors in the owning core, render, analysis, ASCII, or export crate.

package io.merman

internal const val MERMAN_BINDING_OPTIONS_SCHEMA_VERSION: Int = 2

public enum class MermanResourceProfile(public val id: String) {
    INTERACTIVE("interactive"),
    CONSTRAINED("constrained"),
    TRUSTED_NATIVE("trusted-native"),
    UNBOUNDED_FOR_TRUSTED_INPUT("unbounded-for-trusted-input"),
}

public enum class MermanResourceLimitId(public val id: String, public val overridable: Boolean, public val minimumValue: Long) {
    MAX_SOURCE_BYTES("max_source_bytes", true, 1),
    MAX_MODEL_ITEMS("max_model_items", true, 1),
    MAX_MODEL_TEXT_BYTES("max_model_text_bytes", true, 1),
    MAX_MODEL_NESTING_DEPTH("max_model_nesting_depth", true, 1),
    MAX_LAYOUT_WORK_UNITS("max_layout_work_units", true, 1),
    MAX_SVG_BYTES("max_svg_bytes", true, 1),
    MAX_SVG_ELEMENTS("max_svg_elements", true, 1),
    MAX_THEME_ENCODED_BYTES("max_theme_encoded_bytes", true, 0),
    MAX_THEME_BASE64_BYTES("max_theme_base64_bytes", true, 0),
    MAX_FONT_ASSET_COMPRESSED_BYTES("max_font_asset_compressed_bytes", true, 0),
    MAX_FONT_ASSET_DECODED_BYTES("max_font_asset_decoded_bytes", true, 0),
    MAX_FONT_CATALOG_DECODED_BYTES("max_font_catalog_decoded_bytes", true, 0),
    MAX_FONT_ASSETS("max_font_assets", true, 0),
    MAX_FONT_FACES("max_font_faces", true, 0),
    MAX_FONT_TABLES("max_font_tables", true, 0),
    MAX_FONT_ALIASES("max_font_aliases", true, 0),
    MAX_FONT_DECODED_EXPANSION_RATIO("max_font_decoded_expansion_ratio", true, 1),
    THEME_ENCODED_BYTES_HARD_CAP("theme_encoded_bytes_hard_cap", false, 1),
    THEME_BASE64_BYTES_HARD_CAP("theme_base64_bytes_hard_cap", false, 1),
    FONT_ASSET_COMPRESSED_BYTES_HARD_CAP("font_asset_compressed_bytes_hard_cap", false, 1),
    FONT_ASSET_DECODED_BYTES_HARD_CAP("font_asset_decoded_bytes_hard_cap", false, 1),
    FONT_CATALOG_DECODED_BYTES_HARD_CAP("font_catalog_decoded_bytes_hard_cap", false, 1),
    FONT_ASSETS_HARD_CAP("font_assets_hard_cap", false, 1),
    FONT_FACES_HARD_CAP("font_faces_hard_cap", false, 1),
    FONT_TABLES_HARD_CAP("font_tables_hard_cap", false, 1),
    FONT_ALIASES_HARD_CAP("font_aliases_hard_cap", false, 1),
    FONT_DECODED_EXPANSION_RATIO_HARD_CAP("font_decoded_expansion_ratio_hard_cap", false, 1),
    MAX_DOCUMENT_DIAGRAMS("max_document_diagrams", true, 0),
    MAX_ASCII_GRID_CELLS("max_ascii_grid_cells", true, 1),
    MAX_RASTER_WIDTH("max_raster_width", true, 1),
    MAX_RASTER_HEIGHT("max_raster_height", true, 1),
    MAX_RASTER_PIXELS("max_raster_pixels", true, 1),
    MAX_EMBEDDED_IMAGE_BYTES("max_embedded_image_bytes", true, 1),
    MAX_TOTAL_EMBEDDED_IMAGE_BYTES("max_total_embedded_image_bytes", true, 1),
    MAX_EMBEDDED_IMAGE_PIXELS("max_embedded_image_pixels", true, 1),
    MAX_TOTAL_EMBEDDED_IMAGE_PIXELS("max_total_embedded_image_pixels", true, 1),
    MAX_PDF_FILTER_IMAGE_PIXELS("max_pdf_filter_image_pixels", true, 1),
    MAX_SVG_CONVERSION_ISOLATION_DEPTH("max_svg_conversion_isolation_depth", false, 1),
    MAX_SVG_CONVERSION_FILTER_PRIMITIVES_PER_FILTER("max_svg_conversion_filter_primitives_per_filter", false, 1),
    MAX_TOTAL_SVG_CONVERSION_FILTER_PRIMITIVES("max_total_svg_conversion_filter_primitives", false, 1),
    MAX_SVG_CONVERSION_SUBROOTS("max_svg_conversion_subroots", false, 1),
    MAX_NESTED_SVG_IMAGES("max_nested_svg_images", false, 1),
    SVG_BACKEND_TREE_NODES("svg_backend_tree_nodes", false, 1),
}

public enum class MermanResourceOverrideId(public val id: String, public val minimumValue: Long) {
    MAX_SOURCE_BYTES("max_source_bytes", 1),
    MAX_MODEL_ITEMS("max_model_items", 1),
    MAX_MODEL_TEXT_BYTES("max_model_text_bytes", 1),
    MAX_MODEL_NESTING_DEPTH("max_model_nesting_depth", 1),
    MAX_LAYOUT_WORK_UNITS("max_layout_work_units", 1),
    MAX_SVG_BYTES("max_svg_bytes", 1),
    MAX_SVG_ELEMENTS("max_svg_elements", 1),
    MAX_THEME_ENCODED_BYTES("max_theme_encoded_bytes", 0),
    MAX_THEME_BASE64_BYTES("max_theme_base64_bytes", 0),
    MAX_FONT_ASSET_COMPRESSED_BYTES("max_font_asset_compressed_bytes", 0),
    MAX_FONT_ASSET_DECODED_BYTES("max_font_asset_decoded_bytes", 0),
    MAX_FONT_CATALOG_DECODED_BYTES("max_font_catalog_decoded_bytes", 0),
    MAX_FONT_ASSETS("max_font_assets", 0),
    MAX_FONT_FACES("max_font_faces", 0),
    MAX_FONT_TABLES("max_font_tables", 0),
    MAX_FONT_ALIASES("max_font_aliases", 0),
    MAX_FONT_DECODED_EXPANSION_RATIO("max_font_decoded_expansion_ratio", 1),
    MAX_DOCUMENT_DIAGRAMS("max_document_diagrams", 0),
    MAX_ASCII_GRID_CELLS("max_ascii_grid_cells", 1),
    MAX_RASTER_WIDTH("max_raster_width", 1),
    MAX_RASTER_HEIGHT("max_raster_height", 1),
    MAX_RASTER_PIXELS("max_raster_pixels", 1),
    MAX_EMBEDDED_IMAGE_BYTES("max_embedded_image_bytes", 1),
    MAX_TOTAL_EMBEDDED_IMAGE_BYTES("max_total_embedded_image_bytes", 1),
    MAX_EMBEDDED_IMAGE_PIXELS("max_embedded_image_pixels", 1),
    MAX_TOTAL_EMBEDDED_IMAGE_PIXELS("max_total_embedded_image_pixels", 1),
    MAX_PDF_FILTER_IMAGE_PIXELS("max_pdf_filter_image_pixels", 1),
}

public class MermanResourceOptionsBuilder(
    private var profile: MermanResourceProfile? = null,
) {
    private val limits = linkedMapOf<MermanResourceOverrideId, Long>()

    public fun profile(profile: MermanResourceProfile): MermanResourceOptionsBuilder {
        this.profile = profile
        return this
    }

    public fun limit(id: MermanResourceOverrideId, value: Long): MermanResourceOptionsBuilder {
        require(value >= id.minimumValue) { "Resource limit must be at least ${id.minimumValue}: ${id.id}" }
        limits[id] = value
        return this
    }

    public fun build(): MermanResourceOptions = MermanResourceOptions(profile, limits)
}

public class MermanResourceOptions(
    profile: MermanResourceProfile? = null,
    limits: Map<MermanResourceOverrideId, Long> = emptyMap(),
) {
    public val profile: MermanResourceProfile? = profile
    public val limits: Map<MermanResourceOverrideId, Long> = limits.toMap()

    init {
        for ((id, value) in this.limits) {
            require(value >= id.minimumValue) { "Resource limit must be at least ${id.minimumValue}: ${id.id}" }
        }
    }

    public fun toOptionsJson(): String {
        val sorted = limits.entries.sortedBy { it.key.ordinal }
        val parts = mutableListOf<String>()
        profile?.let { parts += "\"profile\":\"${it.id}\"" }
        if (sorted.isNotEmpty()) {
            val limitJson = sorted.joinToString(",") { "\"${it.key.id}\":${it.value}" }
            parts += "\"limits\":{${limitJson}}"
        }
        return if (parts.isEmpty()) {
            "{\"version\":2}"
        } else {
            "{\"version\":2,\"resources\":{${parts.joinToString(",")}}}"
        }
    }
}
