//! Per-diagram SVG compare commands.
mod architecture;
mod block;
mod c4;
mod class;
mod er;
mod flowchart;
mod gantt;
mod gitgraph;
mod info;
mod journey;
mod kanban;
mod mindmap;
mod packet;
mod pie;
mod quadrantchart;
mod radar;
mod requirement;
mod sankey;
mod sequence;
mod state;
mod timeline;
mod treemap;
mod xychart;

pub(crate) use architecture::compare_architecture_svgs;
pub(crate) use block::compare_block_svgs;
pub(crate) use c4::compare_c4_svgs;
pub(crate) use class::compare_class_svgs;
pub(crate) use er::compare_er_svgs;
pub(crate) use flowchart::compare_flowchart_svgs;
pub(crate) use gantt::compare_gantt_svgs;
pub(crate) use gitgraph::compare_gitgraph_svgs;
pub(crate) use info::compare_info_svgs;
pub(crate) use journey::compare_journey_svgs;
pub(crate) use kanban::compare_kanban_svgs;
pub(crate) use mindmap::compare_mindmap_svgs;
pub(crate) use packet::compare_packet_svgs;
pub(crate) use pie::compare_pie_svgs;
pub(crate) use quadrantchart::compare_quadrantchart_svgs;
pub(crate) use radar::compare_radar_svgs;
pub(crate) use requirement::compare_requirement_svgs;
pub(crate) use sankey::compare_sankey_svgs;
pub(crate) use sequence::compare_sequence_svgs;
pub(crate) use state::compare_state_svgs;
pub(crate) use timeline::compare_timeline_svgs;
pub(crate) use treemap::compare_treemap_svgs;
pub(crate) use xychart::compare_xychart_svgs;
