version: 2
updates:
  - package-ecosystem: npm
    directory: /distribution/tree-sitter-mermaid
    schedule:
      interval: weekly
      day: monday
      time: "05:07"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - grammar

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:17"
      timezone: Etc/UTC
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: dtolnay/rust-toolchain
    labels:
      - dependencies
      - ci
