# @generated by `cargo run -p xtask -- gen-binding-contract`.
# Sources: typed registries in merman-bindings-core. Do not edit directly.

REQUIRED_PAYLOAD_SCHEMA_VERSIONS = {
    "binding-result": 1,
    "operation-metadata": 1,
}
