# This file is @generated by `cargo run -p xtask -- gen-resource-contract`.
# Do not edit directly; edit the authoritative descriptors in `crates/merman-core/src/resources.rs` and `crates/merman-render/src/resources.rs`.

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum
from typing import Mapping

class ResourceProfile(str, Enum):
    INTERACTIVE = "interactive"
    CONSTRAINED = "constrained"
    TRUSTED_NATIVE = "trusted-native"
    UNBOUNDED_FOR_TRUSTED_INPUT = "unbounded-for-trusted-input"

class ResourceLimitId(str, Enum):
    MAX_SOURCE_BYTES = "max_source_bytes"
    MAX_MODEL_ITEMS = "max_model_items"
    MAX_MODEL_TEXT_BYTES = "max_model_text_bytes"
    MAX_MODEL_NESTING_DEPTH = "max_model_nesting_depth"
    MAX_LAYOUT_WORK_UNITS = "max_layout_work_units"
    MAX_SVG_BYTES = "max_svg_bytes"
    MAX_SVG_ELEMENTS = "max_svg_elements"

_OVERRIDABLE_LIMITS = {
    ResourceLimitId.MAX_SOURCE_BYTES,
    ResourceLimitId.MAX_MODEL_ITEMS,
    ResourceLimitId.MAX_MODEL_TEXT_BYTES,
    ResourceLimitId.MAX_MODEL_NESTING_DEPTH,
    ResourceLimitId.MAX_LAYOUT_WORK_UNITS,
    ResourceLimitId.MAX_SVG_BYTES,
    ResourceLimitId.MAX_SVG_ELEMENTS,
}

@dataclass(frozen=True)
class ResourceOptions:
    profile: ResourceProfile = ResourceProfile.INTERACTIVE
    limits: Mapping[ResourceLimitId, int] = field(default_factory=dict)

    def __post_init__(self) -> None:
        for limit, value in self.limits.items():
            if limit not in _OVERRIDABLE_LIMITS:
                raise ValueError(f"resource limit is not overridable: {limit.value}")
            if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
                raise ValueError(f"resource limit must be a positive integer: {limit.value}")

    def to_options_json(self) -> str:
        limits = {limit.value: self.limits[limit] for limit in sorted(self.limits, key=lambda item: item.value)}
        resources = {"profile": self.profile.value}
        if limits:
            resources["limits"] = limits
        return json.dumps({"version": 1, "resources": resources}, separators=(",", ":"), sort_keys=True)

@dataclass
class ResourceOptionsBuilder:
    _profile: ResourceProfile = ResourceProfile.INTERACTIVE
    _limits: dict[ResourceLimitId, int] = field(default_factory=dict)

    def profile(self, profile: ResourceProfile) -> ResourceOptionsBuilder:
        self._profile = profile
        return self

    def limit(self, limit: ResourceLimitId, value: int) -> ResourceOptionsBuilder:
        self._limits[limit] = value
        return self

    def build(self) -> ResourceOptions:
        return ResourceOptions(self._profile, dict(self._limits))
