.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH MERMAN-CLI-RUSTDOC-BUILD 1 2026-08-15 "Merman 0.8.0-alpha.5" "Merman CLI Manual"
.SH NAME
merman\-cli\-rustdoc\-build \- Build the complete managed Rustdoc fragment bundle
.SH SYNOPSIS
\fBmerman\-cli rustdoc build\fR [\fB\-\-config\fR] [\fB\-\-quiet\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR]
.SH DESCRIPTION
Build the complete managed Rustdoc fragment bundle
.SH OPTIONS
.TP
\fB\-\-config\fR \fI<PATH>\fR [default: merman\-rustdoc.toml]
Rustdoc fragment configuration file
.TP
\fB\-\-quiet\fR
Suppress non\-error progress output
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.8.0\-alpha.5
