.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH MERMAN-CLI-CAPABILITIES 1 2026-07-29 "Merman 0.8.0-alpha.6" "Merman CLI Manual"
.SH NAME
merman\-cli\-capabilities \- Print the compiled capabilities from the canonical capability descriptor
.SH SYNOPSIS
\fBmerman\-cli capabilities\fR [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR]
.SH DESCRIPTION
Print the compiled capabilities from the canonical capability descriptor
.SH OPTIONS
.TP
\fB\-\-json\fR
Emit the machine\-readable capability document
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.8.0\-alpha.6
