import { bindSurfaceRuntime } from "../surface-runtime.js";
import type { MermanWasmModule } from "../index.js";
export type * from "../index.js";
export {
  MERMAN_ABI_VERSION,
  UNAVAILABLE_DIAGRAM_DETECTION,
  SUPPORTED_THEMES,
  SUPPORTED_HOST_THEME_PRESETS,
  SUPPORTED_DIAGRAMS,
  SUPPORTED_ASCII_DIAGRAMS,
  BINDING_STATUS_CODE_NAMES,
  FULL_BINDING_CAPABILITIES as DEFAULT_BINDING_CAPABILITIES,
  isThemeName,
  isHostThemePresetName,
  isDiagramType,
  isAsciiDiagramType,
  isBindingStatusCodeName,
  isBindingErrorPayload,
  normalizeThemeName,
  normalizeHostThemePresetName,
  encodeOptions,
  assertSafeSvgForDom,
  createBrowserTextMeasurementSession,
  SEMANTIC_TOKEN_DESCRIPTOR,
  SEMANTIC_TOKEN_DESCRIPTOR_DIGEST,
  SEMANTIC_TOKEN_MODIFIER_LSP_NAMES,
  SEMANTIC_TOKEN_RECORD_WIDTH,
  SEMANTIC_TOKEN_TYPE_LSP_NAMES,
  SEMANTIC_TOKEN_VALID_MODIFIER_MASK,
  SEMANTIC_TOKEN_VALID_TYPE_CODE_MAX,
} from "../index.js";

function surfaceLoader(): Promise<MermanWasmModule> {
  // @ts-ignore -- generated wasm-bindgen artifact exists after build:surfaces runs.
  return import("../../pkg/full/merman_wasm.js");
}

const runtime = bindSurfaceRuntime(surfaceLoader);

export const {
  initMerman,
  getMerman,
  isMermanInitialized,
  analyze,
  analyzeJson,
  analysisFacts,
  detectDiagramFacts,
  analyzeDocument,
  analyzeDocumentFacts,
  validate,
  bindingCapabilities,
  runtimeContract,
  selectedRegistryProfile,
  supportedDiagrams,
  diagramFamilyCapabilities,
  supportedThemes,
  abiVersion,
  packageVersion,
  lintRuleCatalog,
  renderSvg,
  renderSvgWithTextMeasurer,
  layoutJsonWithTextMeasurer,
  renderSvgElement,
  renderSvgToElement,
  parseJson,
  parseObject,
  layoutJson,
  layoutObject,
  supportedHostThemePresets,
  renderAscii,
  asciiSupportedDiagrams,
  asciiCapabilities,
  createEditorSession,
  editorDiagnostics,
  editorDiagramDetection,
  editorCodeActions,
  editorCompletions,
  editorHover,
  editorDocumentSymbols,
  editorWorkspaceSymbols,
  editorDefinition,
  editorReferences,
  editorPrepareRename,
  editorRename,
  editorSemanticTokenDescriptor,
  editorSemanticTokens,
} = runtime;
