[package]
name = "xtask"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
chrono = { workspace = true, features = ["clock"] }
base64.workspace = true
brotli.workspace = true
flate2.workspace = true
fs2.workspace = true
futures.workspace = true
dugong = { path = "../dugong" }
lalrpop.workspace = true
merman = { path = "../merman", features = ["render"] }
merman-analysis.workspace = true
merman-core = { path = "../merman-core" }
merman-editor-core.workspace = true
merman-fixture-render-context = { path = "../merman-fixture-render-context" }
merman-layout-elk.workspace = true
merman-render = { path = "../merman-render", features = [
    "layout-cytoscape",
    "layout-elk",
    "font-metrics-generation",
] }
merman-typst-plugin = { path = "../merman-typst-plugin", default-features = false }
regex.workspace = true
roxmltree.workspace = true
serde.workspace = true
serde_json.workspace = true
serde-saphyr.workspace = true
sha2.workspace = true
syn.workspace = true
thiserror.workspace = true
tempfile = "3.27.0"
toml.workspace = true
wasmi.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true
