[package]
name = "xtask"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
base64.workspace = true
brotli.workspace = true
cssparser.workspace = true
flate2.workspace = true
fs2.workspace = true
futures = { workspace = true, features = ["executor"] }
dugong = { path = "../dugong" }
lalrpop.workspace = true
merman = { path = "../merman", default-features = false, features = ["svg"] }
merman-analysis.workspace = true
merman-bindings-core = { workspace = true, features = [
    "analysis",
    "ascii",
    "jpeg",
    "layout-cytoscape",
    "layout-elk",
    "math",
    "pdf",
    "png",
    "svg",
    "system-clock",
    "system-random",
    "system-timezone",
] }
merman-core = { path = "../merman-core", features = ["system-clock", "system-timezone"] }
merman-editor-core.workspace = true
merman-fixture-render-context = { path = "../merman-fixture-render-context" }
merman-layout-elk.workspace = true
merman-render = { path = "../merman-render", features = [
    "layout-cytoscape",
    "layout-elk",
] }
merman-typst-plugin = { path = "../merman-typst-plugin", default-features = false }
regex.workspace = true
roxmltree.workspace = true
serde.workspace = true
serde_json.workspace = true
serde-saphyr = { workspace = true, features = ["deserialize", "serialize"] }
svgtypes.workspace = true
sha2.workspace = true
thiserror.workspace = true
tempfile = "3.27.0"
toml.workspace = true
tree-sitter = "=0.26.5"
tree-sitter-typescript = "=0.23.2"
wasmi.workspace = true

[target.'cfg(unix)'.dependencies]
libc.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { workspace = true, features = ["Win32_Foundation", "Win32_System_Diagnostics_ToolHelp", "Win32_System_Threading"] }
