[package]
name = "merman-wasm"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "WebAssembly bindings for merman browser rendering."
documentation = "https://docs.rs/merman-wasm"
readme = "README.md"
keywords = ["mermaid", "diagrams", "wasm", "svg", "headless"]
categories = ["wasm", "visualization"]

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.merman]
artifact-profile-required = true

[package.metadata.wasm-pack.profile.custom.wasm-bindgen]
omit-default-module-path = true

[features]
default = []
analysis = ["merman-bindings-core/analysis"]
ascii = ["merman-bindings-core/ascii"]
svg = ["dep:js-sys", "merman-bindings-core/svg"]
layout-cytoscape = ["svg", "merman-bindings-core/layout-cytoscape"]
layout-elk = ["svg", "merman-bindings-core/layout-elk"]
editor = [
    "analysis",
    "dep:merman-analysis",
    "dep:merman-editor-core",
    "dep:merman-core",
]
math = ["svg", "merman-bindings-core/math"]

[dependencies]
console_error_panic_hook.workspace = true
merman-analysis = { workspace = true, optional = true }
merman-core = { workspace = true, optional = true }
merman-bindings-core.workspace = true
merman-editor-core = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
serde-wasm-bindgen.workspace = true
wasm-bindgen.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = { workspace = true, optional = true }
