; Every Mermaid family has one body-level fold. Nested structural folds are
; additive and deliberately use Neovim's standard @fold capture.

(source_file
  (_
    body: (_) @fold))

[
  (architecture_accessibility_description_block)
  (block_composite_statement)
  (c4_boundary_statement)
  (class_member_block)
  (class_namespace_declaration)
  (cynefin_domain_block)
  (er_attribute_block)
  (event_data_block)
  (event_nested_data_block)
  (flow_accessibility_description_block)
  (flow_subgraph)
  (gantt_accessibility_description_block)
  (journey_accessibility_description_block)
  (kanban_multiline_label_text)
  (langium_acc_descr_block)
  (mindmap_multiline_label_text)
  (quadrant_chart_accessibility_description_block)
  (radar_accessibility_block)
  (railroad_acc_descr_block)
  (requirement_accessibility_description_block)
  (requirement_declaration)
  (requirement_element_declaration)
  (sequence_alt_block)
  (sequence_and_branch)
  (sequence_box_block)
  (sequence_break_block)
  (sequence_critical_block)
  (sequence_else_branch)
  (sequence_loop_block)
  (sequence_opt_block)
  (sequence_option_branch)
  (sequence_par_block)
  (sequence_rect_block)
  (state_accessibility_description_block)
  (state_composite_declaration)
  (state_multiline_note)
  (swimlane_accessibility_description_block)
  (swimlane_subgraph)
  (timeline_accessibility_description_block)
  (wardley_accessibility_block)
  (wardley_pipeline_statement)
  (xy_chart_accessibility_description_block)
  (zenuml_block)
  (zenuml_group_block)
] @fold
