swimlane-beta LR
subgraph sales["Sales 世界"]
  lead["`Markdown **lead**`"] e1@-->|quote| review{Review}
end
subgraph delivery[Delivery]
  review --> done((Done))
end
classDef active fill:#f96,stroke:#333
class lead,review active
style done fill:#fff
click lead callback "Open"
