; Zed Vim text objects. A Mermaid diagram is the large section; named
; declarations and control blocks are function-sized sections.

(_
  header: (_
    (diagram_keyword))
  body: (_) @class.inside) @class.around

[
  (architecture_group_statement)
  (architecture_service_statement)
  (block_composite_statement)
  (block_node_statement)
  (c4_boundary_statement)
  (c4_entity_declaration)
  (class_declaration)
  (er_entity_declaration)
  (event_data_statement)
  (event_frame_statement)
  (flow_subgraph)
  (flow_node_statement)
  (gantt_section_statement)
  (gantt_task_statement)
  (git_graph_branch_statement)
  (ishikawa_cause_statement)
  (ishikawa_effect_statement)
  (journey_section_statement)
  (journey_task_statement)
  (kanban_item_statement)
  (mindmap_node_statement)
  (packet_block_statement)
  (pie_section)
  (quadrant_chart_point_statement)
  (radar_axis_statement)
  (radar_curve_statement)
  (railroad_rule)
  (railroad_abnf_rule)
  (railroad_ebnf_rule)
  (railroad_peg_rule)
  (requirement_declaration)
  (requirement_element_declaration)
  (sequence_alt_block)
  (sequence_box_block)
  (sequence_break_block)
  (sequence_critical_block)
  (sequence_loop_block)
  (sequence_opt_block)
  (sequence_par_block)
  (sequence_rect_block)
  (sequence_participant_declaration)
  (state_composite_declaration)
  (state_named_declaration)
  (swimlane_subgraph)
  (swimlane_node_statement)
  (timeline_section_statement)
  (timeline_event_statement)
  (tree_view_node_statement)
  (treemap_item_statement)
  (venn_set_statement)
  (wardley_component_statement)
  (xy_chart_bar_statement)
  (xy_chart_line_statement)
  (zenuml_participant_declaration)
  (zenuml_section_statement)
  (zenuml_sync_message_statement)
] @function.around

(comment)+ @comment.around
