/* @generated by `cargo run -p xtask -- gen-native-abi`. */
/* Sources: abi/merman-v3.json and capabilities/feature-surface-v1.json. */
/* Do not edit directly. */

#ifndef MERMAN_H
#define MERMAN_H

#include <stddef.h>
#include <stdint.h>

#include "merman_text_measurement_abi.h"

#if defined(__cplusplus) && (__cplusplus >= 201703L || (defined(_MSVC_LANG) && _MSVC_LANG >= 201703L))
#define MERMAN_NATIVE_NOEXCEPT noexcept
#else
#define MERMAN_NATIVE_NOEXCEPT
#endif

#ifdef __cplusplus
extern "C" {
#endif

#define MERMAN_NATIVE_ABI_VERSION 3u
#define MERMAN_NATIVE_ABI_MINIMUM_PREFIX_LAYOUT_DIGEST "sha256:c40c22461e973267106c0cbd5c2c98d7deed72fc7b94d70d45923f8f9d1c5110"
#define MERMAN_NATIVE_ABI_FULL_DESCRIPTOR_DIGEST "sha256:fd23cf40afff31e77953033cb689f2ecd238685d332dffdb23405881c64135b9"
#define MERMAN_NATIVE_RESULT_SCHEMA_VERSION 1u
#define MERMAN_NATIVE_ERROR_KIND_BUSY "busy"
#define MERMAN_NATIVE_ERROR_KIND_GENERIC "generic"
#define MERMAN_NATIVE_ERROR_KIND_MISSING_CAPABILITY "missing-capability"
#define MERMAN_NATIVE_ERROR_KIND_REENTRANT_CALL "reentrant-call"
#define MERMAN_NATIVE_ERROR_KIND_UNKNOWN_OPERATION "unknown-operation"
#define MERMAN_NATIVE_STRUCT_SIZE(type) ((uint32_t)sizeof(type))
#ifdef __cplusplus
#define MERMAN_NATIVE_RESULT_INIT { MERMAN_NATIVE_STRUCT_SIZE(MermanNativeResult), 0, 0, 0, {}, {}, {} }
#else
#define MERMAN_NATIVE_RESULT_INIT { .struct_size = MERMAN_NATIVE_STRUCT_SIZE(MermanNativeResult) }
#endif

typedef int32_t MermanNativeStatus;
enum {
    MERMAN_NATIVE_STATUS_OK = 0,
    MERMAN_NATIVE_STATUS_INVALID_ARGUMENT = 1,
    MERMAN_NATIVE_STATUS_UTF8_ERROR = 2,
    MERMAN_NATIVE_STATUS_OPTIONS_JSON_ERROR = 3,
    MERMAN_NATIVE_STATUS_NO_DIAGRAM = 4,
    MERMAN_NATIVE_STATUS_PARSE_ERROR = 5,
    MERMAN_NATIVE_STATUS_RENDER_ERROR = 6,
    MERMAN_NATIVE_STATUS_UNSUPPORTED_OPERATION = 7,
    MERMAN_NATIVE_STATUS_PANIC = 8,
    MERMAN_NATIVE_STATUS_INTERNAL_ERROR = 9,
    MERMAN_NATIVE_STATUS_RESOURCE_LIMIT_EXCEEDED = 10,
    MERMAN_NATIVE_STATUS_ABI_MISMATCH = 11,
    MERMAN_NATIVE_STATUS_ABI_LAYOUT_MISMATCH = 12,
    MERMAN_NATIVE_STATUS_CALLBACK_ERROR = 13,
    MERMAN_NATIVE_STATUS_REENTRANT_CALL = 14,
    MERMAN_NATIVE_STATUS_INVALID_ENGINE = 15,
    MERMAN_NATIVE_STATUS_BUSY = 16
};

typedef int32_t MermanNativeOperationCode;
enum {
    MERMAN_NATIVE_OPERATION_NONE = 0,
    MERMAN_NATIVE_OPERATION_SVG = 1,
    MERMAN_NATIVE_OPERATION_PNG = 2,
    MERMAN_NATIVE_OPERATION_JPEG = 3,
    MERMAN_NATIVE_OPERATION_PDF = 4,
    MERMAN_NATIVE_OPERATION_ASCII = 5,
    MERMAN_NATIVE_OPERATION_SEMANTIC_JSON = 6,
    MERMAN_NATIVE_OPERATION_LAYOUT_JSON = 7,
    MERMAN_NATIVE_OPERATION_ANALYSIS_JSON = 8,
    MERMAN_NATIVE_OPERATION_ANALYSIS_FACTS_JSON = 9,
    MERMAN_NATIVE_OPERATION_VALIDATION_JSON = 10,
    MERMAN_NATIVE_OPERATION_DOCUMENT_ANALYSIS_JSON = 11,
    MERMAN_NATIVE_OPERATION_DOCUMENT_ANALYSIS_FACTS_JSON = 12,
    MERMAN_NATIVE_OPERATION_SVG_PLAN_JSON = 13
};
#define MERMAN_NATIVE_OPERATION_REQUIRES_URI_NONE 0
#define MERMAN_NATIVE_OPERATION_REQUIRES_URI_SVG 0
#define MERMAN_NATIVE_OPERATION_ID_SVG "svg"
#define MERMAN_NATIVE_OPERATION_CAPABILITY_SVG "svg"
#define MERMAN_NATIVE_OPERATION_MEDIA_TYPE_SVG "image/svg+xml"
#define MERMAN_NATIVE_OPERATION_REQUIRES_URI_PNG 0
#define MERMAN_NATIVE_OPERATION_ID_PNG "png"
#define MERMAN_NATIVE_OPERATION_CAPABILITY_PNG "png"
#define MERMAN_NATIVE_OPERATION_MEDIA_TYPE_PNG "image/png"
#define MERMAN_NATIVE_OPERATION_REQUIRES_URI_JPEG 0
#define MERMAN_NATIVE_OPERATION_ID_JPEG "jpeg"
#define MERMAN_NATIVE_OPERATION_CAPABILITY_JPEG "jpeg"
#define MERMAN_NATIVE_OPERATION_MEDIA_TYPE_JPEG "image/jpeg"
#define MERMAN_NATIVE_OPERATION_REQUIRES_URI_PDF 0
#define MERMAN_NATIVE_OPERATION_ID_PDF "pdf"
#define MERMAN_NATIVE_OPERATION_CAPABILITY_PDF "pdf"
#define MERMAN_NATIVE_OPERATION_MEDIA_TYPE_PDF "application/pdf"
#define MERMAN_NATIVE_OPERATION_REQUIRES_URI_ASCII 0
#define MERMAN_NATIVE_OPERATION_ID_ASCII "ascii"
#define MERMAN_NATIVE_OPERATION_CAPABILITY_ASCII "ascii"
#define MERMAN_NATIVE_OPERATION_MEDIA_TYPE_ASCII "text/plain; charset=utf-8"
#define MERMAN_NATIVE_OPERATION_REQUIRES_URI_SEMANTIC_JSON 0
#define MERMAN_NATIVE_OPERATION_ID_SEMANTIC_JSON "semantic-json"
#define MERMAN_NATIVE_OPERATION_MEDIA_TYPE_SEMANTIC_JSON "application/json"
#define MERMAN_NATIVE_OPERATION_REQUIRES_URI_LAYOUT_JSON 0
#define MERMAN_NATIVE_OPERATION_ID_LAYOUT_JSON "layout-json"
#define MERMAN_NATIVE_OPERATION_CAPABILITY_LAYOUT_JSON "svg"
#define MERMAN_NATIVE_OPERATION_MEDIA_TYPE_LAYOUT_JSON "application/json"
#define MERMAN_NATIVE_OPERATION_REQUIRES_URI_ANALYSIS_JSON 0
#define MERMAN_NATIVE_OPERATION_ID_ANALYSIS_JSON "analysis-json"
#define MERMAN_NATIVE_OPERATION_CAPABILITY_ANALYSIS_JSON "analysis"
#define MERMAN_NATIVE_OPERATION_MEDIA_TYPE_ANALYSIS_JSON "application/json"
#define MERMAN_NATIVE_OPERATION_REQUIRES_URI_ANALYSIS_FACTS_JSON 0
#define MERMAN_NATIVE_OPERATION_ID_ANALYSIS_FACTS_JSON "analysis-facts-json"
#define MERMAN_NATIVE_OPERATION_CAPABILITY_ANALYSIS_FACTS_JSON "analysis"
#define MERMAN_NATIVE_OPERATION_MEDIA_TYPE_ANALYSIS_FACTS_JSON "application/json"
#define MERMAN_NATIVE_OPERATION_REQUIRES_URI_VALIDATION_JSON 0
#define MERMAN_NATIVE_OPERATION_ID_VALIDATION_JSON "validation-json"
#define MERMAN_NATIVE_OPERATION_CAPABILITY_VALIDATION_JSON "analysis"
#define MERMAN_NATIVE_OPERATION_MEDIA_TYPE_VALIDATION_JSON "application/json"
#define MERMAN_NATIVE_OPERATION_REQUIRES_URI_DOCUMENT_ANALYSIS_JSON 1
#define MERMAN_NATIVE_OPERATION_ID_DOCUMENT_ANALYSIS_JSON "document-analysis-json"
#define MERMAN_NATIVE_OPERATION_CAPABILITY_DOCUMENT_ANALYSIS_JSON "analysis"
#define MERMAN_NATIVE_OPERATION_MEDIA_TYPE_DOCUMENT_ANALYSIS_JSON "application/json"
#define MERMAN_NATIVE_OPERATION_REQUIRES_URI_DOCUMENT_ANALYSIS_FACTS_JSON 1
#define MERMAN_NATIVE_OPERATION_ID_DOCUMENT_ANALYSIS_FACTS_JSON "document-analysis-facts-json"
#define MERMAN_NATIVE_OPERATION_CAPABILITY_DOCUMENT_ANALYSIS_FACTS_JSON "analysis"
#define MERMAN_NATIVE_OPERATION_MEDIA_TYPE_DOCUMENT_ANALYSIS_FACTS_JSON "application/json"
#define MERMAN_NATIVE_OPERATION_REQUIRES_URI_SVG_PLAN_JSON 0
#define MERMAN_NATIVE_OPERATION_ID_SVG_PLAN_JSON "svg-plan-json"
#define MERMAN_NATIVE_OPERATION_CAPABILITY_SVG_PLAN_JSON "svg"
#define MERMAN_NATIVE_OPERATION_MEDIA_TYPE_SVG_PLAN_JSON "application/json"

typedef int32_t MermanNativeFunctionSlot;
enum {
    MERMAN_NATIVE_FUNCTION_RUNTIME_CATALOG = 0,
    MERMAN_NATIVE_FUNCTION_ENGINE_NEW = 1,
    MERMAN_NATIVE_FUNCTION_ENGINE_TRY_CLOSE = 2,
    MERMAN_NATIVE_FUNCTION_EXECUTE_COLLECT = 3,
    MERMAN_NATIVE_FUNCTION_RESULT_FREE = 4
};

typedef uint64_t MermanNativeEngineToken;

typedef struct MermanNativeSlice MermanNativeSlice;
typedef struct MermanNativeBuffer MermanNativeBuffer;
typedef struct MermanNativeTextMeasureRequest MermanNativeTextMeasureRequest;
typedef struct MermanNativeTextMeasureResult MermanNativeTextMeasureResult;
typedef struct MermanNativeEngineConfig MermanNativeEngineConfig;
typedef struct MermanNativeOperationRequest MermanNativeOperationRequest;
typedef struct MermanNativeResult MermanNativeResult;
typedef struct MermanNativeApiRequest MermanNativeApiRequest;
typedef struct MermanNativeApi MermanNativeApi;

typedef MermanNativeStatus (*MermanNativeTextMeasureCallback)(const MermanNativeTextMeasureRequest *request, MermanNativeTextMeasureResult *out_result, void *user_data) MERMAN_NATIVE_NOEXCEPT;

typedef MermanNativeStatus (*MermanNativeRuntimeCatalogFn)(MermanNativeResult *out_result) MERMAN_NATIVE_NOEXCEPT;
typedef MermanNativeStatus (*MermanNativeEngineNewFn)(const MermanNativeEngineConfig *config, MermanNativeEngineToken *out_engine, MermanNativeResult *out_result) MERMAN_NATIVE_NOEXCEPT;
typedef MermanNativeStatus (*MermanNativeEngineTryCloseFn)(MermanNativeEngineToken engine) MERMAN_NATIVE_NOEXCEPT;
typedef MermanNativeStatus (*MermanNativeExecuteCollectFn)(MermanNativeEngineToken engine, const MermanNativeOperationRequest *request, MermanNativeResult *out_result) MERMAN_NATIVE_NOEXCEPT;
typedef void (*MermanNativeResultFreeFn)(MermanNativeResult *result) MERMAN_NATIVE_NOEXCEPT;

struct MermanNativeSlice {
    uint32_t struct_size;
    const uint8_t *data;
    size_t len;
};

struct MermanNativeBuffer {
    uint32_t struct_size;
    uint8_t *data;
    size_t len;
};

struct MermanNativeTextMeasureRequest {
    uint32_t struct_size;
    uint32_t text_measurement_protocol_version;
    MermanNativeSlice text;
    MermanNativeSlice font_family;
    double font_size;
    MermanNativeSlice font_weight;
    MermanNativeSlice font_style;
    double max_width;
    double line_height;
    double letter_spacing;
    double word_spacing;
    int32_t wrap_mode;
    int32_t direction;
    int32_t white_space;
    uint8_t has_max_width;
    int32_t phase;
    int32_t operation;
};

struct MermanNativeTextMeasureResult {
    uint32_t struct_size;
    uint8_t handled;
    uint8_t has_raw_width;
    int32_t result_kind;
    double width;
    double height;
    double length;
    double bbox_left;
    double bbox_right;
    double raw_width;
    size_t line_count;
};

struct MermanNativeEngineConfig {
    uint32_t struct_size;
    MermanNativeSlice options_json;
    MermanNativeTextMeasureCallback text_measure;
    void *text_measure_user_data;
};

struct MermanNativeOperationRequest {
    uint32_t struct_size;
    MermanNativeOperationCode operation;
    MermanNativeSlice source;
    MermanNativeSlice uri;
    MermanNativeSlice options_json;
};

struct MermanNativeResult {
    uint32_t struct_size;
    uint64_t allocation_token;
    MermanNativeStatus status;
    MermanNativeOperationCode operation;
    MermanNativeSlice media_type;
    MermanNativeBuffer data;
    MermanNativeBuffer metadata_or_error_json;
};

struct MermanNativeApiRequest {
    uint32_t struct_size;
    uint32_t expected_abi_version;
    MermanNativeSlice expected_minimum_prefix_layout_digest;
};

struct MermanNativeApi {
    uint32_t struct_size;
    uint32_t abi_version;
    MermanNativeSlice minimum_prefix_layout_digest;
    MermanNativeSlice full_descriptor_digest;
    MermanNativeSlice capability_catalog_digest;
    MermanNativeSlice package_version;
    MermanNativeRuntimeCatalogFn runtime_catalog;
    MermanNativeEngineNewFn engine_new;
    MermanNativeEngineTryCloseFn engine_try_close;
    MermanNativeExecuteCollectFn execute_collect;
    MermanNativeResultFreeFn result_free;
};

#define MERMAN_NATIVE_API_MINIMUM_PREFIX_SIZE ((uint32_t)(offsetof(MermanNativeApi, result_free) + sizeof(((MermanNativeApi *)0)->result_free)))

/*
 * The minimum-prefix digest negotiates layout compatibility. The full descriptor and capability
 * digests report provenance and do not reject a compatible prefix. Except for MermanNativeApi,
 * public records require exact struct_size. The caller supplies MermanNativeApi capacity and
 * receives the producer full size. MermanNativeResult must be fully zero-initialized with
 * MERMAN_NATIVE_RESULT_INIT before every producing call.
 *
 * Host callbacks MUST NOT unwind, throw, propagate SEH, longjmp, or otherwise perform a non-local
 * exit across this boundary. Merman converts callback return statuses; it cannot catch foreign
 * exceptions.
 *
 * Ownership and concurrency rules from the ABI descriptor:
 * - borrowed_slices: Input, media-type, and callback slices are borrowed. Hosts must not retain
 *   their pointers after the enclosing call or callback returns.
 * - disabled_capabilities: A known operation whose backend is absent returns unsupported_operation
 *   with kind missing-capability and the canonical capability_id before result allocation. An
 *   unknown operation code returns the same status with kind unknown-operation and a null
 *   capability_id.
 * - engine_tokens: Engine tokens are opaque u64 values. engine_try_close never waits:
 *   callback-active returns reentrant-call, another active operation returns busy with the token
 *   still valid, and quiescent success permanently closes admission before retiring the token. A
 *   transport reference acquired before successful close cannot enter afterwards. Callback and
 *   user_data are immutable constructor-owned state and may be released after successful close.
 * - host_callbacks: Host callbacks are synchronous and borrowed for the call. They MUST NOT unwind,
 *   throw, propagate SEH, longjmp, or otherwise perform a non-local exit across the ABI boundary.
 *   Merman converts returned status values only; it cannot catch foreign exceptions.
 * - result_buffers: Only result.data and result.metadata_or_error_json identified by a live
 *   allocation_token are Merman-owned. Callers zero-initialize the complete result and set
 *   struct_size before every producing call. Merman assigns a process-lifetime monotonic nonzero
 *   token that is never reused. If token issuance is exhausted, the call returns internal-error and
 *   leaves the caller's valid zero-initialized result untouched because no conforming result can be
 *   written. Moving the complete record transfers ownership. result_free trusts only the token,
 *   never buffer pointers; zero, unknown, stale, and random non-live tokens release nothing and
 *   only clear the supplied record. Copying a live token is outside the same-process hostile-memory
 *   threat boundary. No result buffer may be passed to a host allocator.
 */
MermanNativeStatus merman_get_native_api(const MermanNativeApiRequest *request, MermanNativeApi *out_api) MERMAN_NATIVE_NOEXCEPT;

#ifdef __cplusplus
}
#endif

#endif
