// This file is @generated by `cargo run -p xtask -- gen-resource-contract`.
// Do not edit directly; edit the authoritative descriptors in `crates/merman-core/src/resources.rs` and `crates/merman-render/src/resources.rs`.

#ifndef MERMAN_RESOURCE_CONTRACT_H
#define MERMAN_RESOURCE_CONTRACT_H

#include <stddef.h>
#include <stdint.h>

typedef int32_t MermanResourceProfile;
enum {
    MERMAN_RESOURCE_PROFILE_INTERACTIVE = 0,
    MERMAN_RESOURCE_PROFILE_CONSTRAINED = 1,
    MERMAN_RESOURCE_PROFILE_TRUSTED_NATIVE = 2,
    MERMAN_RESOURCE_PROFILE_UNBOUNDED_FOR_TRUSTED_INPUT = 3
};

typedef int32_t MermanResourceLimitId;
enum {
    MERMAN_RESOURCE_LIMIT_MAX_SOURCE_BYTES = 0,
    MERMAN_RESOURCE_LIMIT_MAX_MODEL_ITEMS = 1,
    MERMAN_RESOURCE_LIMIT_MAX_MODEL_TEXT_BYTES = 2,
    MERMAN_RESOURCE_LIMIT_MAX_MODEL_NESTING_DEPTH = 3,
    MERMAN_RESOURCE_LIMIT_MAX_LAYOUT_WORK_UNITS = 4,
    MERMAN_RESOURCE_LIMIT_MAX_SVG_BYTES = 5,
    MERMAN_RESOURCE_LIMIT_MAX_SVG_ELEMENTS = 6
};

typedef struct MermanResourceLimitOverride {
    MermanResourceLimitId id;
    size_t value;
} MermanResourceLimitOverride;

#endif
