//! Generation of the parser-owned editor rename-policy projections.

use crate::XtaskError;
use serde::Deserialize;
use std::collections::BTreeSet;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

pub(crate) const RENAME_POLICY_PATH: &str = "contracts/editor-language/rename-policy-v1.json";
const RENAME_POLICY_SCHEMA_VERSION: u32 = 1;
const CORE_OUTPUT_PATH: &str = "crates/merman-core/src/generated/editor_rename_policy.rs";
const WEB_OUTPUT_PATH: &str = "platforms/web/src/generated/editor-rename-policy.ts";

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
struct RenamePolicyContract {
    schema_version: u32,
    policies: Vec<RenamePolicy>,
}

#[derive(Debug, Clone, Deserialize)]
#[serde(deny_unknown_fields)]
struct RenamePolicy {
    id: String,
    rust_variant: String,
    description: String,
    #[serde(rename = "default")]
    is_default: bool,
}

fn policy_error(message: impl Into<String>) -> XtaskError {
    XtaskError::VerifyFailed(format!(
        "editor rename-policy contract is invalid: {}",
        message.into()
    ))
}

fn read_contract(path: &Path) -> Result<RenamePolicyContract, XtaskError> {
    let text = fs::read_to_string(path).map_err(|source| XtaskError::ReadFile {
        path: path.display().to_string(),
        source,
    })?;
    let contract = serde_json::from_str::<RenamePolicyContract>(&text)
        .map_err(|error| policy_error(format!("failed to parse {}: {error}", path.display())))?;
    validate_contract(&contract)?;
    Ok(contract)
}

fn validate_contract(contract: &RenamePolicyContract) -> Result<(), XtaskError> {
    if contract.schema_version != RENAME_POLICY_SCHEMA_VERSION {
        return Err(policy_error(format!(
            "unsupported schema {}; expected {RENAME_POLICY_SCHEMA_VERSION}",
            contract.schema_version
        )));
    }
    if contract.policies.is_empty() {
        return Err(policy_error("at least one rename policy is required"));
    }

    let mut ids = BTreeSet::new();
    let mut rust_variants = BTreeSet::new();
    for policy in &contract.policies {
        validate_identifier(&policy.id)?;
        validate_rust_variant(&policy.rust_variant)?;
        if policy.description.trim().is_empty()
            || policy.description.contains('\n')
            || policy.description.contains('\r')
        {
            return Err(policy_error(format!(
                "rename policy `{}` requires a non-empty single-line description",
                policy.id
            )));
        }
        if !ids.insert(policy.id.as_str()) {
            return Err(policy_error(format!(
                "duplicate rename-policy id `{}`",
                policy.id
            )));
        }
        if !rust_variants.insert(policy.rust_variant.as_str()) {
            return Err(policy_error(format!(
                "duplicate rename-policy Rust variant `{}`",
                policy.rust_variant
            )));
        }
    }

    let defaults = contract
        .policies
        .iter()
        .filter(|policy| policy.is_default)
        .count();
    if defaults != 1 {
        return Err(policy_error(format!(
            "rename policies require exactly one default; found {defaults}"
        )));
    }
    Ok(())
}

fn validate_identifier(value: &str) -> Result<(), XtaskError> {
    let valid = !value.is_empty()
        && value.bytes().enumerate().all(|(index, byte)| match byte {
            b'a'..=b'z' => true,
            b'0'..=b'9' => index > 0,
            b'_' => index > 0 && index + 1 < value.len(),
            _ => false,
        })
        && !value.contains("__");
    if valid {
        Ok(())
    } else {
        Err(policy_error(format!(
            "rename-policy id `{value}` must be lower_snake_case"
        )))
    }
}

fn validate_rust_variant(value: &str) -> Result<(), XtaskError> {
    let mut bytes = value.bytes();
    let valid = bytes.next().is_some_and(|byte| byte.is_ascii_uppercase())
        && bytes.all(|byte| byte.is_ascii_alphanumeric());
    if valid {
        Ok(())
    } else {
        Err(policy_error(format!(
            "rename-policy Rust variant `{value}` must be an ASCII PascalCase identifier"
        )))
    }
}

fn generated_preamble(comment: &str) -> String {
    format!(
        "{comment} This file is @generated by `cargo run -p xtask -- gen-editor-language-contract`.\n{comment} Do not edit it directly; edit `{RENAME_POLICY_PATH}` instead.\n\n"
    )
}

fn render_core(contract: &RenamePolicyContract) -> String {
    let mut output = generated_preamble("//");
    output.push_str("/// Parser-owned validation policy for renaming an entity occurrence.\n");
    output.push_str("#[derive(\n");
    for derive in [
        "Debug",
        "Clone",
        "Copy",
        "Default",
        "PartialEq",
        "Eq",
        "PartialOrd",
        "Ord",
        "Hash",
        "serde::Serialize",
        "serde::Deserialize",
    ] {
        writeln!(output, "    {derive},").unwrap();
    }
    output.push_str(")]\npub enum EditorRenamePolicy {\n");
    for policy in &contract.policies {
        writeln!(output, "    /// {}", policy.description).unwrap();
        if policy.is_default {
            output.push_str("    #[default]\n");
        }
        writeln!(output, "    #[serde(rename = {:?})]", policy.id).unwrap();
        writeln!(output, "    {},", policy.rust_variant).unwrap();
    }
    output.push_str("}\n\nimpl EditorRenamePolicy {\n");
    writeln!(
        output,
        "    pub const ALL: [Self; {}] = [",
        contract.policies.len()
    )
    .unwrap();
    for policy in &contract.policies {
        writeln!(output, "        Self::{},", policy.rust_variant).unwrap();
    }
    output.push_str("    ];\n\n");
    writeln!(
        output,
        "    pub const IDS: [&'static str; {}] = [",
        contract.policies.len()
    )
    .unwrap();
    for policy in &contract.policies {
        writeln!(output, "        {:?},", policy.id).unwrap();
    }
    output.push_str(
        "    ];\n\n    pub const fn as_str(self) -> &'static str {\n        match self {\n",
    );
    for policy in &contract.policies {
        writeln!(
            output,
            "            Self::{} => {:?},",
            policy.rust_variant, policy.id
        )
        .unwrap();
    }
    output.push_str("        }\n    }\n}\n");
    output
}

fn render_web(contract: &RenamePolicyContract) -> String {
    let mut output = generated_preamble("//");
    output.push_str("export const EDITOR_RENAME_POLICIES = [\n");
    for policy in &contract.policies {
        writeln!(output, "  {:?},", policy.id).unwrap();
    }
    output.push_str(
        "] as const;\n\nexport type EditorRenamePolicy =\n  (typeof EDITOR_RENAME_POLICIES)[number];\n",
    );
    output
}

pub(crate) fn rename_policy_artifacts(root: &Path) -> Result<Vec<(PathBuf, String)>, XtaskError> {
    let contract = read_contract(&root.join(RENAME_POLICY_PATH))?;
    Ok(vec![
        (PathBuf::from(CORE_OUTPUT_PATH), render_core(&contract)),
        (PathBuf::from(WEB_OUTPUT_PATH), render_web(&contract)),
    ])
}

pub(crate) fn rename_policy_artifact_drift(root: &Path) -> Result<Vec<PathBuf>, XtaskError> {
    let mut drift = Vec::new();
    for (relative_path, expected) in rename_policy_artifacts(root)? {
        let path = root.join(&relative_path);
        let actual = fs::read_to_string(&path).map_err(|source| XtaskError::ReadFile {
            path: path.display().to_string(),
            source,
        })?;
        if actual.replace("\r\n", "\n") != expected {
            drift.push(relative_path);
        }
    }
    Ok(drift)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn committed_contract() -> RenamePolicyContract {
        read_contract(&crate::cmd::workspace_root().join(RENAME_POLICY_PATH))
            .expect("committed editor rename-policy contract")
    }

    #[test]
    fn committed_contract_has_one_default_and_stable_public_ids() {
        let contract = committed_contract();
        assert_eq!(
            contract
                .policies
                .iter()
                .filter(|policy| policy.is_default)
                .map(|policy| policy.id.as_str())
                .collect::<Vec<_>>(),
            ["identifier"]
        );
        assert_eq!(
            contract.policies.first().map(|policy| policy.id.as_str()),
            Some("none")
        );
    }

    #[test]
    fn validator_rejects_duplicate_ids_and_multiple_defaults() {
        let mut duplicate = committed_contract();
        duplicate.policies[1].id = duplicate.policies[0].id.clone();
        assert!(validate_contract(&duplicate).is_err());

        let mut defaults = committed_contract();
        defaults.policies[0].is_default = true;
        assert!(validate_contract(&defaults).is_err());
    }
}
