//! Projection of the analysis configuration contract for editor clients.

use crate::XtaskError;
use merman_analysis::{
    AnalysisConfigClientProjection, AnalysisConfigClientSettingNormalization,
    AnalysisConfigClientValueSet, AnalysisConfigContract,
};
use serde_json::{Map, Value, json};
use std::collections::BTreeSet;
use std::fs;
use std::path::Path;

pub(crate) const VSCODE_MANIFEST_PATH: &str = "tools/vscode-extension/package.json";
pub(crate) const VSCODE_ANALYSIS_CONFIG_BASELINE_PATH: &str =
    "tools/vscode-extension/src/generated/analysis-config-baseline.ts";
pub(crate) const VSCODE_ANALYSIS_SETTING_PREFIX: &str = "merman.analysis.";
pub(crate) const EDITOR_LANGUAGE_CONTRACT_COMMAND: &str =
    "cargo run -p xtask -- gen-editor-language-contract";

fn analysis_config_error(message: impl Into<String>) -> XtaskError {
    XtaskError::VerifyFailed(format!(
        "editor analysis config is invalid: {}",
        message.into()
    ))
}

pub(crate) fn client_projection() -> AnalysisConfigClientProjection {
    AnalysisConfigContract::current().client_projection()
}

pub(crate) fn baseline_artifact() -> Result<String, XtaskError> {
    let payload = serde_json::to_string_pretty(&client_projection())?;
    Ok(format!(
        "// Generated by `{EDITOR_LANGUAGE_CONTRACT_COMMAND}`. Do not edit.\n\nexport const BUNDLED_ANALYSIS_CONFIG_PROJECTION = {payload} as const;\n"
    ))
}

pub(crate) fn project_vscode_analysis_settings(
    contributes: &mut Map<String, Value>,
    contract: &AnalysisConfigClientProjection,
) -> Result<(), XtaskError> {
    let configuration = contributes
        .get_mut("configuration")
        .and_then(Value::as_array_mut)
        .ok_or_else(|| analysis_config_error("VS Code manifest configuration must be an array"))?;
    let matching_sections = configuration
        .iter()
        .enumerate()
        .filter_map(|(index, section)| {
            let properties = section.get("properties")?.as_object()?;
            properties
                .keys()
                .any(|key| key.starts_with(VSCODE_ANALYSIS_SETTING_PREFIX))
                .then_some(index)
        })
        .collect::<Vec<_>>();
    let section_index = match matching_sections.as_slice() {
        [index] => *index,
        [] => {
            return Err(analysis_config_error(
                "VS Code manifest has no analysis configuration section",
            ));
        }
        _ => {
            return Err(analysis_config_error(
                "VS Code manifest has multiple analysis configuration sections",
            ));
        }
    };
    let properties = configuration[section_index]
        .get_mut("properties")
        .and_then(Value::as_object_mut)
        .ok_or_else(|| {
            analysis_config_error("VS Code manifest analysis configuration must be an object")
        })?;

    let projected_paths = properties
        .keys()
        .filter_map(|key| key.strip_prefix(VSCODE_ANALYSIS_SETTING_PREFIX))
        .map(str::to_string)
        .collect::<BTreeSet<_>>();
    let contract_paths = contract
        .constraints
        .settings
        .iter()
        .map(|setting| setting.path.clone())
        .collect::<BTreeSet<_>>();
    if projected_paths != contract_paths {
        return Err(analysis_config_error(format!(
            "VS Code analysis settings must match the analysis contract; manifest has {projected_paths:?}, contract has {contract_paths:?}"
        )));
    }
    for descriptor in &contract.constraints.settings {
        let setting = vscode_analysis_setting_mut(properties, &descriptor.path)?;
        project_vscode_analysis_setting(setting, &descriptor.normalization, contract);
        setting.remove("default");
    }

    Ok(())
}

fn project_vscode_analysis_setting(
    setting: &mut Map<String, Value>,
    normalization: &AnalysisConfigClientSettingNormalization,
    contract: &AnalysisConfigClientProjection,
) {
    project_vscode_analysis_normalization(setting, normalization, contract, true);
}

fn project_vscode_analysis_normalization(
    target: &mut Map<String, Value>,
    normalization: &AnalysisConfigClientSettingNormalization,
    contract: &AnalysisConfigClientProjection,
    nullable_integer: bool,
) {
    for generated_key in [
        "enum",
        "enumDescriptions",
        "markdownEnumDescriptions",
        "examples",
        "pattern",
        "minimum",
        "maximum",
    ] {
        target.remove(generated_key);
    }
    match normalization {
        AnalysisConfigClientSettingNormalization::String { pattern, values } => {
            target.insert("type".to_string(), json!("string"));
            target.remove("items");
            if let Some(pattern) = pattern {
                target.insert("pattern".to_string(), json!(pattern));
            }
            if let Some(values) = values {
                target.insert(
                    "examples".to_string(),
                    json!(client_values(contract, *values)),
                );
            }
        }
        AnalysisConfigClientSettingNormalization::Integer { minimum, maximum } => {
            target.insert(
                "type".to_string(),
                if nullable_integer {
                    json!(["integer", "null"])
                } else {
                    json!("integer")
                },
            );
            target.remove("items");
            project_integer_range(target, *minimum, *maximum);
        }
        AnalysisConfigClientSettingNormalization::Object => {
            target.insert("type".to_string(), json!("object"));
            target.remove("items");
        }
        AnalysisConfigClientSettingNormalization::RuleIdList => {
            target.insert("type".to_string(), json!("array"));
            target.insert(
                "items".to_string(),
                json!({
                    "type": "string",
                    "examples": client_values(
                        contract,
                        AnalysisConfigClientValueSet::ConfigurableRuleIds,
                    ),
                }),
            );
        }
        AnalysisConfigClientSettingNormalization::RuleSeverityOverrides { fields } => {
            let mut properties = Map::new();
            let mut required = Vec::new();
            for field in fields {
                let mut property = Map::new();
                project_vscode_analysis_normalization(
                    &mut property,
                    &field.normalization,
                    contract,
                    false,
                );
                properties.insert(field.name.clone(), Value::Object(property));
                if field.required {
                    required.push(field.name.as_str());
                }
            }
            let mut item = Map::new();
            item.insert("type".to_string(), json!("object"));
            item.insert("properties".to_string(), Value::Object(properties));
            if !required.is_empty() {
                item.insert("required".to_string(), json!(required));
            }
            target.insert("type".to_string(), json!("array"));
            target.insert("items".to_string(), Value::Object(item));
        }
    }
}

fn client_values(
    contract: &AnalysisConfigClientProjection,
    values: AnalysisConfigClientValueSet,
) -> &[String] {
    match values {
        AnalysisConfigClientValueSet::Profiles => &contract.profiles,
        AnalysisConfigClientValueSet::Severities => &contract.severities,
        AnalysisConfigClientValueSet::ConfigurableRuleIds => &contract.configurable_rule_ids,
    }
}

fn vscode_analysis_setting_mut<'a>(
    properties: &'a mut Map<String, Value>,
    path: &str,
) -> Result<&'a mut Map<String, Value>, XtaskError> {
    properties
        .get_mut(&format!("{VSCODE_ANALYSIS_SETTING_PREFIX}{path}"))
        .and_then(Value::as_object_mut)
        .ok_or_else(|| {
            analysis_config_error(format!("VS Code analysis setting {path} must be an object"))
        })
}

fn project_integer_range(setting: &mut Map<String, Value>, minimum: i64, maximum: i64) {
    setting.insert("minimum".to_string(), json!(minimum));
    setting.insert("maximum".to_string(), json!(maximum));
}

pub(crate) fn baseline_drift(root: &Path) -> Result<bool, XtaskError> {
    let expected = baseline_artifact()?;
    let path = root.join(VSCODE_ANALYSIS_CONFIG_BASELINE_PATH);
    let actual = fs::read_to_string(&path).map_err(|source| XtaskError::ReadFile {
        path: path.display().to_string(),
        source,
    })?;
    Ok(actual.replace("\r\n", "\n") != expected)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bundled_analysis_config_is_generated_from_the_owner_projection() {
        let projection = client_projection();
        let artifact = baseline_artifact().unwrap();

        assert!(artifact.contains(EDITOR_LANGUAGE_CONTRACT_COMMAND));
        assert!(artifact.contains(&serde_json::to_string_pretty(&projection).unwrap()));
        assert!(artifact.contains("\"change_scope\": \"snapshot_affecting\""));
        assert!(artifact.contains("\"change_scope\": \"diagnostics_only\""));
    }

    #[test]
    fn analysis_projection_repairs_manifest_settings_from_the_contract() {
        let mut manifest: Value = serde_json::from_str(include_str!(
            "../../../../tools/vscode-extension/package.json"
        ))
        .unwrap();
        let contributes = manifest["contributes"].as_object_mut().unwrap();
        let configuration = contributes["configuration"].as_array_mut().unwrap();
        let analysis_section = configuration
            .iter_mut()
            .find(|section| {
                section["properties"].as_object().is_some_and(|properties| {
                    properties
                        .keys()
                        .any(|key| key.starts_with(VSCODE_ANALYSIS_SETTING_PREFIX))
                })
            })
            .unwrap();
        analysis_section["title"] = json!("分析设置");
        let analysis_properties = analysis_section["properties"].as_object_mut().unwrap();
        analysis_properties["merman.analysis.fixed_today"]["type"] = json!("boolean");
        analysis_properties["merman.analysis.lint.enable_rules"]["items"] =
            json!({ "type": "number" });

        let contract = client_projection();
        project_vscode_analysis_settings(contributes, &contract).unwrap();

        let properties = contributes["configuration"]
            .as_array()
            .unwrap()
            .iter()
            .find(|section| {
                section["properties"].as_object().is_some_and(|properties| {
                    properties
                        .keys()
                        .any(|key| key.starts_with(VSCODE_ANALYSIS_SETTING_PREFIX))
                })
            })
            .unwrap()["properties"]
            .as_object()
            .unwrap();
        let fixed_today = contract
            .constraints
            .settings
            .iter()
            .find(|setting| setting.path == "fixed_today")
            .unwrap();
        let AnalysisConfigClientSettingNormalization::String {
            pattern: Some(expected_pattern),
            ..
        } = &fixed_today.normalization
        else {
            panic!("fixed_today must retain its generated string pattern");
        };
        assert_eq!(
            properties["merman.analysis.fixed_today"]["pattern"],
            json!(expected_pattern)
        );
        assert_eq!(properties["merman.analysis.fixed_today"]["type"], "string");
        assert_eq!(
            properties["merman.analysis.lint.profile"]["examples"],
            json!(contract.profiles)
        );
        assert!(properties["merman.analysis.lint.profile"]["enum"].is_null());
        assert_eq!(
            properties["merman.analysis.lint.enable_rules"]["items"]["examples"],
            json!(contract.configurable_rule_ids)
        );
        assert_eq!(
            properties["merman.analysis.lint.rule_severities"]["items"]["properties"]["severity"]["examples"],
            json!(contract.severities)
        );
        assert!(properties["merman.analysis.lint.rule_severities"]["items"]["properties"]["severity"]["enum"].is_null());
    }
}
