pub(crate) mod admission;
pub(crate) mod audit;
pub(crate) mod compare;
pub(crate) mod cypress_corpus;
pub(crate) mod debug;
pub(crate) mod default_config;
pub(crate) mod fixtures;
pub(crate) mod generate;
pub(crate) mod import;
pub(crate) mod paths;
pub(crate) mod profile_budget;
pub(crate) mod snapshots;
pub(crate) mod text_measurement;
pub(crate) mod typst_package;
pub(crate) mod typst_plugin_smoke;
pub(crate) mod upstream_mmd_corpus;
pub(crate) mod upstream_svg_policy;
pub(crate) mod upstream_svg_provenance;
pub(crate) mod upstream_svg_support;
pub(crate) mod verify;
pub(crate) mod wasm_size_matrix;
pub(crate) mod web_catalog;

pub(crate) const PINNED_MERMAID_PACKAGE_SHA256: &str =
    "3b6a6e2a483e5e6b470be13f765dd648271a35b9d4e322d854d85bd065381ad0";

pub(crate) use admission::*;
pub(crate) use audit::*;
pub(crate) use compare::*;
pub(crate) use cypress_corpus::*;
pub(crate) use debug::*;
pub(crate) use default_config::*;
pub(crate) use fixtures::*;
pub(crate) use generate::*;
pub(crate) use import::*;
pub(crate) use paths::*;
pub(crate) use profile_budget::*;
pub(crate) use snapshots::*;
pub(crate) use text_measurement::*;
pub(crate) use typst_package::*;
pub(crate) use typst_plugin_smoke::*;
pub(crate) use upstream_mmd_corpus::*;
pub(crate) use upstream_svg_policy::*;
pub(crate) use upstream_svg_provenance::*;
pub(crate) use upstream_svg_support::*;
pub(crate) use verify::*;
pub(crate) use wasm_size_matrix::*;
pub(crate) use web_catalog::*;
