//! Checked projection of the runtime ASCII capability authority for the Playground fallback.

use crate::XtaskError;
use std::fs;
use std::path::Path;

const DEFAULT_OUTPUT: &str = "playground/src/generated/ascii-capabilities.ts";
const GENERATE_COMMAND: &str = "cargo run -p xtask -- gen-playground-ascii-capabilities";

fn render_ascii_capabilities() -> Result<String, XtaskError> {
    let capabilities = merman_bindings_core::ascii_capabilities();
    let records = serde_json::to_string_pretty(&capabilities)?;
    Ok(format!(
        "// This file is @generated by `{GENERATE_COMMAND}`.\n\
         // Do not edit it directly; edit the Rust ASCII capability authority instead.\n\n\
         import type {{ AsciiCapability }} from \"@mermanjs/web\";\n\n\
         export const GENERATED_ASCII_CAPABILITIES: readonly AsciiCapability[] = {records};\n"
    ))
}

fn write_output(path: &Path, contents: &str) -> Result<(), XtaskError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| XtaskError::WriteFile {
            path: parent.display().to_string(),
            source,
        })?;
    }
    fs::write(path, contents).map_err(|source| XtaskError::WriteFile {
        path: path.display().to_string(),
        source,
    })
}

pub(crate) fn gen_playground_ascii_capabilities(args: Vec<String>) -> Result<(), XtaskError> {
    if !args.is_empty() {
        return Err(XtaskError::Usage);
    }
    let output = crate::cmd::workspace_root().join(DEFAULT_OUTPUT);
    write_output(&output, &render_ascii_capabilities()?)
}

pub(crate) fn verify_playground_ascii_capabilities_artifact() -> Result<Option<String>, XtaskError>
{
    let root = crate::cmd::workspace_root();
    let path = root.join(DEFAULT_OUTPUT);
    let actual = fs::read_to_string(&path).map_err(|source| XtaskError::ReadFile {
        path: path.display().to_string(),
        source,
    })?;
    let expected = render_ascii_capabilities()?;
    if actual.replace("\r\n", "\n") == expected {
        Ok(None)
    } else {
        Ok(Some(format!(
            "Playground ASCII capability fallback drifted; regenerate with `{GENERATE_COMMAND}`"
        )))
    }
}
