//! Cross-platform projections of the render resource policy descriptor.
//!
//! The Rust descriptor in `merman-render` is the authority. This module only projects its stable
//! identifiers and validation metadata into host-language builders; it does not define another
//! budget table.

use crate::XtaskError;
use merman_render::{
    RenderResourceProfile, resource_limit_descriptors, resource_profile_descriptors,
};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_NOTICE: &str =
    "This file is @generated by `cargo run -p xtask -- gen-resource-contract`.\n";

const OUTPUTS: &[&str] = &[
    "crates/merman-ffi/src/generated/resource_contract.rs",
    "crates/merman-ffi/include/merman_resource_contract.h",
    "crates/merman-uniffi/src/generated/resource_contract.rs",
    "platforms/web/src/generated/resource-contract.ts",
    "platforms/android/src/main/kotlin/io/merman/MermanResourceOptions.kt",
    "platforms/apple/Sources/Merman/Generated/ResourceOptions.swift",
    "platforms/flutter/lib/src/generated/resource_options.dart",
    "platforms/python/merman/src/merman/_resource_options.py",
];

fn pascal_case(value: &str) -> String {
    value
        .split(['_', '-'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            let first = chars
                .next()
                .map(|ch| ch.to_ascii_uppercase().to_string())
                .unwrap_or_default();
            format!("{first}{}", chars.as_str())
        })
        .collect()
}

fn camel_case(value: &str) -> String {
    let pascal = pascal_case(value);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => format!("{}{}", first.to_ascii_lowercase(), chars.as_str()),
        None => String::new(),
    }
}

fn upper_snake(value: &str) -> String {
    value.replace('-', "_").to_ascii_uppercase()
}

fn profile_enum_name(id: &str) -> String {
    pascal_case(id)
}

fn limit_enum_name(id: &str) -> String {
    pascal_case(id)
}

fn profile_default() -> &'static str {
    RenderResourceProfile::ALL
        .iter()
        .find(|profile| profile.descriptor().recommended_binding_default)
        .map(|profile| profile.id())
        .expect("resource descriptor has a binding default")
}

fn generated_preamble(comment: &str) -> String {
    format!(
        "{comment} {GENERATED_NOTICE}{comment} Do not edit directly; edit `crates/merman-render/src/resources.rs`.\n\n"
    )
}

fn render_c_rust() -> String {
    let profiles = resource_profile_descriptors();
    let limits = resource_limit_descriptors();
    let mut out = generated_preamble("//");
    writeln!(out, "pub const RESOURCE_CONTRACT_SCHEMA_VERSION: u32 = 1;").unwrap();
    writeln!(
        out,
        "pub const RESOURCE_PROFILE_COUNT: usize = {};",
        profiles.len()
    )
    .unwrap();
    writeln!(
        out,
        "pub const RESOURCE_LIMIT_COUNT: usize = {};\n",
        limits.len()
    )
    .unwrap();
    out.push_str("pub const RESOURCE_PROFILE_IDS: [&str; RESOURCE_PROFILE_COUNT] = [\n");
    for profile in profiles {
        writeln!(out, "    {:?},", profile.id).unwrap();
    }
    out.push_str("];\n\npub const RESOURCE_LIMIT_IDS: [&str; RESOURCE_LIMIT_COUNT] = [\n");
    for limit in limits {
        writeln!(out, "    {:?},", limit.stable_id).unwrap();
    }
    out.push_str("];\n\n");
    out.push_str("pub fn profile_id(code: i32) -> Option<&'static str> {\n    RESOURCE_PROFILE_IDS.get(usize::try_from(code).ok()?).copied()\n}\n\n");
    out.push_str("pub fn limit_id(code: i32) -> Option<&'static str> {\n    RESOURCE_LIMIT_IDS.get(usize::try_from(code).ok()?).copied()\n}\n");
    out
}

fn render_c_header() -> String {
    let profiles = resource_profile_descriptors();
    let limits = resource_limit_descriptors();
    let mut out = generated_preamble("//");
    out.push_str("#ifndef MERMAN_RESOURCE_CONTRACT_H\n#define MERMAN_RESOURCE_CONTRACT_H\n\n#include <stddef.h>\n#include <stdint.h>\n\n#define MERMAN_RESOURCE_CONTRACT_SCHEMA_VERSION 1\n\ntypedef int32_t MermanResourceProfile;\nenum {\n");
    for (index, profile) in profiles.iter().enumerate() {
        writeln!(
            out,
            "    MERMAN_RESOURCE_PROFILE_{} = {}{}",
            upper_snake(profile.id),
            index,
            if index + 1 == profiles.len() { "" } else { "," }
        )
        .unwrap();
    }
    out.push_str("};\n\ntypedef int32_t MermanResourceLimitId;\nenum {\n");
    for (index, limit) in limits.iter().enumerate() {
        writeln!(
            out,
            "    MERMAN_RESOURCE_LIMIT_{} = {}{}",
            upper_snake(limit.stable_id),
            index,
            if index + 1 == limits.len() { "" } else { "," }
        )
        .unwrap();
    }
    out.push_str("};\n\ntypedef struct MermanResourceLimitOverride {\n    MermanResourceLimitId id;\n    size_t value;\n} MermanResourceLimitOverride;\n\n#endif\n");
    out
}

fn render_typescript() -> String {
    let profiles = resource_profile_descriptors();
    let limits = resource_limit_descriptors();
    let mut out = generated_preamble("//");
    out.push_str("export const RESOURCE_PROFILES = [\n");
    for profile in profiles {
        writeln!(out, "  {:?},", profile.id).unwrap();
    }
    out.push_str("] as const;\nexport type ResourceProfile = (typeof RESOURCE_PROFILES)[number];\n\nexport const RESOURCE_LIMIT_IDS = [\n");
    for limit in limits {
        writeln!(out, "  {:?},", limit.stable_id).unwrap();
    }
    out.push_str("] as const;\nexport type ResourceLimitId = (typeof RESOURCE_LIMIT_IDS)[number];\n\nexport type ResourceLimitOverrides = Partial<Record<ResourceLimitId, number>>;\n\nexport interface ResourceOptions {\n  profile?: ResourceProfile;\n  limits?: ResourceLimitOverrides;\n}\n\nexport interface RawResourceOptions {\n  profile?: string;\n  limits?: Record<string, number>;\n}\n\nconst OVERRIDABLE_LIMITS = new Set<ResourceLimitId>([\n");
    for limit in limits.iter().filter(|limit| limit.overridable) {
        writeln!(out, "  {:?},", limit.stable_id).unwrap();
    }
    out.push_str("]);\n\nexport function resourceOptions(\n  profile: ResourceProfile = ");
    write!(out, "{:?}", profile_default()).unwrap();
    out.push_str(",\n  limits: ResourceLimitOverrides = {},\n): ResourceOptions {\n  if (!(RESOURCE_PROFILES as readonly string[]).includes(profile)) {\n    throw new RangeError(`unsupported resource profile: ${profile}`);\n  }\n  const normalized: ResourceLimitOverrides = {};\n  for (const [id, value] of Object.entries(limits) as [ResourceLimitId, number][]) {\n    if (!(RESOURCE_LIMIT_IDS as readonly string[]).includes(id)) {\n      throw new RangeError(`unknown resource limit: ${id}`);\n    }\n    if (!OVERRIDABLE_LIMITS.has(id)) {\n      throw new RangeError(`resource limit is not overridable: ${id}`);\n    }\n    if (!Number.isSafeInteger(value) || value <= 0) {\n      throw new RangeError(`resource limit must be a positive safe integer: ${id}`);\n    }\n    normalized[id] = value;\n  }\n  return Object.keys(normalized).length === 0\n    ? { profile }\n    : { profile, limits: normalized };\n}\n\nexport function resourceOptionsJson(\n  profile: ResourceProfile = ");
    write!(out, "{:?}", profile_default()).unwrap();
    out.push_str(",\n  limits: ResourceLimitOverrides = {},\n): string {\n  return JSON.stringify({ version: 1, resources: resourceOptions(profile, limits) });\n}\n\nexport function rawResourceOptionsJson(options: RawResourceOptions): string {\n  return JSON.stringify({ version: 1, resources: options });\n}\n");
    out
}

fn render_kotlin() -> String {
    let profiles = resource_profile_descriptors();
    let limits = resource_limit_descriptors();
    let mut out = generated_preamble("//");
    out.push_str("package io.merman\n\n");
    out.push_str("public enum class MermanResourceProfile(public val id: String) {\n");
    for profile in profiles {
        writeln!(out, "    {}(\"{}\"),", upper_snake(profile.id), profile.id).unwrap();
    }
    out.push_str("}\n\npublic enum class MermanResourceLimitId(public val id: String, public val overridable: Boolean) {\n");
    for limit in limits {
        writeln!(
            out,
            "    {}(\"{}\", {}),",
            upper_snake(limit.stable_id),
            limit.stable_id,
            limit.overridable
        )
        .unwrap();
    }
    out.push_str("}\n\npublic class MermanResourceOptionsBuilder(\n    private var profile: MermanResourceProfile = MermanResourceProfile.");
    write!(out, "{}", upper_snake(profile_default())).unwrap();
    out.push_str(") {\n    private val limits = linkedMapOf<MermanResourceLimitId, Long>()\n\n    public fun profile(profile: MermanResourceProfile): MermanResourceOptionsBuilder {\n        this.profile = profile\n        return this\n    }\n\n    public fun limit(id: MermanResourceLimitId, value: Long): MermanResourceOptionsBuilder {\n        require(id.overridable) { \"Resource limit is not overridable: ${id.id}\" }\n        require(value > 0) { \"Resource limit must be positive: ${id.id}\" }\n        limits[id] = value\n        return this\n    }\n\n    public fun build(): MermanResourceOptions = MermanResourceOptions(profile, limits.toMap())\n}\n\npublic data class MermanResourceOptions(\n    val profile: MermanResourceProfile,\n    val limits: Map<MermanResourceLimitId, Long> = emptyMap(),\n) {\n    public fun toOptionsJson(): String {\n        val sorted = limits.entries.sortedBy { it.key.ordinal }\n        val limitJson = sorted.joinToString(\",\") { \"\\\"${it.key.id}\\\":${it.value}\" }\n        val limitsPart = if (sorted.isEmpty()) \"\" else \",\\\"limits\\\":{${limitJson}}\"\n        return \"{\\\"version\\\":1,\\\"resources\\\":{\\\"profile\\\":\\\"${profile.id}\\\"${limitsPart}}}\"\n    }\n}\n");
    out
}

fn render_swift() -> String {
    let profiles = resource_profile_descriptors();
    let limits = resource_limit_descriptors();
    let mut out = generated_preamble("//");
    out.push_str("import Foundation\n\npublic enum MermanResourceProfile: String, CaseIterable, Codable, Sendable {\n");
    for profile in profiles {
        writeln!(
            out,
            "    case {} = \"{}\"",
            camel_case(profile.id),
            profile.id
        )
        .unwrap();
    }
    out.push_str(
        "}\n\npublic enum MermanResourceLimitID: String, CaseIterable, Codable, Sendable {\n",
    );
    for limit in limits {
        writeln!(
            out,
            "    case {} = \"{}\"",
            camel_case(limit.stable_id),
            limit.stable_id
        )
        .unwrap();
    }
    out.push_str("\n    public var overridable: Bool {\n        switch self {\n");
    for limit in limits {
        writeln!(
            out,
            "        case .{}: {}",
            camel_case(limit.stable_id),
            limit.overridable
        )
        .unwrap();
    }
    out.push_str("        }\n    }\n}\n\npublic struct MermanResourceOptionsBuilder: Sendable {\n    private var profile: MermanResourceProfile = .");
    write!(out, "{}", camel_case(profile_default())).unwrap();
    out.push_str("\n    private var limits: [MermanResourceLimitID: UInt64] = [:]\n\n    public init() {}\n    public mutating func setProfile(_ profile: MermanResourceProfile) { self.profile = profile }\n    public mutating func setLimit(_ id: MermanResourceLimitID, value: UInt64) throws {\n        guard id.overridable else { throw MermanResourceOptionsError.notOverridable(id.rawValue) }\n        guard value > 0 else { throw MermanResourceOptionsError.nonPositive(id.rawValue) }\n        limits[id] = value\n    }\n    public func build() -> MermanResourceOptions { MermanResourceOptions(profile: profile, limits: limits) }\n}\n\npublic enum MermanResourceOptionsError: Error {\n    case notOverridable(String)\n    case nonPositive(String)\n}\n\npublic struct MermanResourceOptions: Sendable {\n    public let profile: MermanResourceProfile\n    public let limits: [MermanResourceLimitID: UInt64]\n    public init(profile: MermanResourceProfile, limits: [MermanResourceLimitID: UInt64] = [:]) { self.profile = profile; self.limits = limits }\n    public func optionsJSON() throws -> String {\n        let wireLimits = Dictionary(uniqueKeysWithValues: limits.map { ($0.key.rawValue, $0.value) })\n        let envelope: [String: Any] = [\"version\": 1, \"resources\": [\"profile\": profile.rawValue, \"limits\": wireLimits]]\n        let data = try JSONSerialization.data(withJSONObject: envelope, options: [.sortedKeys])\n        return String(decoding: data, as: UTF8.self)\n    }\n}\n");
    out
}

fn render_dart() -> String {
    let profiles = resource_profile_descriptors();
    let limits = resource_limit_descriptors();
    let mut out = generated_preamble("//");
    out.push_str("import 'dart:convert';\n\nenum MermanResourceProfile {\n");
    for profile in profiles {
        writeln!(out, "  {}('{}'),", camel_case(profile.id), profile.id).unwrap();
    }
    out.push_str("  ;\n\n  const MermanResourceProfile(this.id);\n  final String id;\n}\n\nenum MermanResourceLimitId {\n");
    for limit in limits {
        writeln!(
            out,
            "  {}('{}', {}),",
            camel_case(limit.stable_id),
            limit.stable_id,
            limit.overridable
        )
        .unwrap();
    }
    out.push_str("  ;\n\n  const MermanResourceLimitId(this.id, this.overridable);\n  final String id;\n  final bool overridable;\n}\n\nclass MermanResourceOptionsBuilder {\n  MermanResourceProfile _profile = MermanResourceProfile.");
    write!(out, "{}", camel_case(profile_default())).unwrap();
    out.push_str(";\n  final Map<MermanResourceLimitId, int> _limits = {};\n\n  void setProfile(MermanResourceProfile profile) => _profile = profile;\n  void setLimit(MermanResourceLimitId id, int value) {\n    if (!id.overridable)\n      throw ArgumentError('Resource limit is not overridable: ${id.id}');\n    if (value <= 0)\n      throw ArgumentError('Resource limit must be positive: ${id.id}');\n    _limits[id] = value;\n  }\n\n  MermanResourceOptions build() =>\n      MermanResourceOptions(_profile, Map.unmodifiable(_limits));\n}\n\nclass MermanResourceOptions {\n  const MermanResourceOptions(this.profile, [this.limits = const {}]);\n  final MermanResourceProfile profile;\n  final Map<MermanResourceLimitId, int> limits;\n\n  String toOptionsJson() {\n    final sorted = limits.entries.toList()\n      ..sort((a, b) => a.key.index.compareTo(b.key.index));\n    return jsonEncode(<String, Object?>{\n      'version': 1,\n      'resources': <String, Object?>{\n        'profile': profile.id,\n        if (sorted.isNotEmpty)\n          'limits': <String, int>{\n            for (final entry in sorted) entry.key.id: entry.value\n          },\n      },\n    });\n  }\n}\n");
    out
}

fn render_python() -> String {
    let profiles = resource_profile_descriptors();
    let limits = resource_limit_descriptors();
    let mut out = generated_preamble("#");
    out.push_str("from __future__ import annotations\n\nimport json\nfrom dataclasses import dataclass, field\nfrom enum import Enum\nfrom typing import Mapping\n\nclass ResourceProfile(str, Enum):\n");
    for profile in profiles {
        writeln!(out, "    {} = \"{}\"", upper_snake(profile.id), profile.id).unwrap();
    }
    out.push_str("\nclass ResourceLimitId(str, Enum):\n");
    for limit in limits {
        writeln!(
            out,
            "    {} = \"{}\"",
            upper_snake(limit.stable_id),
            limit.stable_id
        )
        .unwrap();
    }
    out.push_str("\n_OVERRIDABLE_LIMITS = {\n");
    for limit in limits.iter().filter(|limit| limit.overridable) {
        writeln!(out, "    ResourceLimitId.{},", upper_snake(limit.stable_id)).unwrap();
    }
    out.push_str("}\n\n@dataclass(frozen=True)\nclass ResourceOptions:\n    profile: ResourceProfile = ResourceProfile.");
    write!(out, "{}", upper_snake(profile_default())).unwrap();
    out.push_str("\n    limits: Mapping[ResourceLimitId, int] = field(default_factory=dict)\n\n    def __post_init__(self) -> None:\n        for limit, value in self.limits.items():\n            if limit not in _OVERRIDABLE_LIMITS:\n                raise ValueError(f\"resource limit is not overridable: {limit.value}\")\n            if not isinstance(value, int) or isinstance(value, bool) or value <= 0:\n                raise ValueError(f\"resource limit must be a positive integer: {limit.value}\")\n\n    def to_options_json(self) -> str:\n        limits = {limit.value: self.limits[limit] for limit in sorted(self.limits, key=lambda item: item.value)}\n        resources = {\"profile\": self.profile.value}\n        if limits:\n            resources[\"limits\"] = limits\n        return json.dumps({\"version\": 1, \"resources\": resources}, separators=(\",\", \":\"), sort_keys=True)\n\n@dataclass\nclass ResourceOptionsBuilder:\n    _profile: ResourceProfile = ResourceProfile.");
    write!(out, "{}", upper_snake(profile_default())).unwrap();
    out.push_str("\n    _limits: dict[ResourceLimitId, int] = field(default_factory=dict)\n\n    def profile(self, profile: ResourceProfile) -> ResourceOptionsBuilder:\n        self._profile = profile\n        return self\n\n    def limit(self, limit: ResourceLimitId, value: int) -> ResourceOptionsBuilder:\n        self._limits[limit] = value\n        return self\n\n    def build(self) -> ResourceOptions:\n        return ResourceOptions(self._profile, dict(self._limits))\n");
    out
}

fn render_uniffi() -> String {
    let profiles = resource_profile_descriptors();
    let limits = resource_limit_descriptors();
    let mut out = generated_preamble("//");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]\npub enum MermanResourceProfile {\n");
    for profile in profiles {
        writeln!(out, "    {},", profile_enum_name(profile.id)).unwrap();
    }
    out.push_str(
        "}\n\nimpl MermanResourceProfile {\n    fn id(self) -> &'static str { match self {\n",
    );
    for profile in profiles {
        writeln!(
            out,
            "        Self::{} => {:?},",
            profile_enum_name(profile.id),
            profile.id
        )
        .unwrap();
    }
    out.push_str("    } }\n}\n\n#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]\npub enum MermanResourceLimitId {\n");
    for limit in limits {
        writeln!(out, "    {},", limit_enum_name(limit.stable_id)).unwrap();
    }
    out.push_str(
        "}\n\nimpl MermanResourceLimitId {\n    fn id(self) -> &'static str { match self {\n",
    );
    for limit in limits {
        writeln!(
            out,
            "        Self::{} => {:?},",
            limit_enum_name(limit.stable_id),
            limit.stable_id
        )
        .unwrap();
    }
    out.push_str("    } }\n}\n\n#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Record)]\npub struct MermanResourceLimitOverride {\n    pub id: MermanResourceLimitId,\n    pub value: u64,\n}\n\n#[cfg(feature = \"render\")]\n#[uniffi::export]\npub fn resource_options_json(\n    profile: MermanResourceProfile,\n    overrides: Vec<MermanResourceLimitOverride>,\n) -> Result<String, MermanError> {\n    let pairs = overrides\n        .iter()\n        .map(|override_| {\n            usize::try_from(override_.value)\n                .map(|value| (override_.id.id(), value))\n                .map_err(|_| MermanError::internal(\"resource override exceeds host usize\"))\n        })\n        .collect::<Result<Vec<_>, _>>()?;\n    let bytes = merman_bindings_core::resource_options_json(profile.id(), &pairs)\n        .map_err(MermanError::from_binding)?;\n    String::from_utf8(bytes).map_err(|error| MermanError::internal(error.to_string()))\n}\n");
    out
}

fn generated_artifacts() -> Vec<(PathBuf, String)> {
    vec![
        (PathBuf::from(OUTPUTS[0]), render_c_rust()),
        (PathBuf::from(OUTPUTS[1]), render_c_header()),
        (PathBuf::from(OUTPUTS[2]), render_uniffi()),
        (PathBuf::from(OUTPUTS[3]), render_typescript()),
        (PathBuf::from(OUTPUTS[4]), render_kotlin()),
        (PathBuf::from(OUTPUTS[5]), render_swift()),
        (PathBuf::from(OUTPUTS[6]), render_dart()),
        (PathBuf::from(OUTPUTS[7]), render_python()),
    ]
}

fn write_artifact(root: &Path, path: &Path, contents: &str) -> Result<(), XtaskError> {
    let full = root.join(path);
    if let Some(parent) = full.parent() {
        fs::create_dir_all(parent).map_err(|source| XtaskError::WriteFile {
            path: parent.display().to_string(),
            source,
        })?;
    }
    fs::write(&full, contents).map_err(|source| XtaskError::WriteFile {
        path: full.display().to_string(),
        source,
    })
}

pub(crate) fn gen_resource_contract(args: Vec<String>) -> Result<(), XtaskError> {
    if !args.is_empty() {
        return Err(XtaskError::Usage);
    }
    let root = crate::cmd::workspace_root();
    for (path, contents) in generated_artifacts() {
        write_artifact(&root, &path, &contents)?;
    }
    Ok(())
}

pub(crate) fn verify_resource_contract_artifacts() -> Result<Option<String>, XtaskError> {
    let root = crate::cmd::workspace_root();
    let mut drift = Vec::new();
    for (path, expected) in generated_artifacts() {
        let full = root.join(&path);
        let actual = fs::read_to_string(&full).map_err(|source| XtaskError::ReadFile {
            path: full.display().to_string(),
            source,
        })?;
        if actual.replace("\r\n", "\n") != expected {
            drift.push(path.display().to_string());
        }
    }
    if drift.is_empty() {
        Ok(None)
    } else {
        Ok(Some(format!(
            "resource contract projections drifted: {}; regenerate with `cargo run -p xtask -- gen-resource-contract`",
            drift.join(", ")
        )))
    }
}

pub(crate) fn verify_resource_contract(args: Vec<String>) -> Result<(), XtaskError> {
    if !args.is_empty() {
        return Err(XtaskError::Usage);
    }
    match verify_resource_contract_artifacts()? {
        Some(message) => Err(XtaskError::VerifyFailed(message)),
        None => Ok(()),
    }
}
