//! Cross-platform projections of the resource policy descriptors.
//!
//! The input descriptors in `merman-core` and render descriptors in `merman-render` are the
//! authorities. This module only projects their stable identifiers and validation metadata into
//! host-language builders; it does not define another budget table.

use crate::XtaskError;
use merman_bindings_core::{
    BINDING_OPTIONS_SCHEMA_VERSION, BindingResourceContract, RuntimeResourceContract,
    TextMeasurementProviderProjection, binding_resource_contract,
    compiled_runtime_capability_surface, runtime_catalog_for,
};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_NOTICE: &str =
    "This file is @generated by `cargo run -p xtask -- gen-resource-contract`.\n";

const FFI_HEADER_OUTPUT: &str = "crates/merman-ffi/include/merman_resource_contract.h";
const UNIFFI_RUST_OUTPUT: &str = "crates/merman-uniffi/src/generated/resource_contract.rs";
const WEB_OUTPUT: &str = "platforms/web/src/generated/resource-contract.ts";
const ANDROID_OUTPUT: &str = "platforms/android/src/main/kotlin/io/merman/MermanResourceOptions.kt";
const FLUTTER_OUTPUT: &str = "platforms/flutter/lib/src/generated/resource_options.dart";
const UNIFFI_PYTHON_TEMPLATE_OUTPUT: &str = "crates/merman-uniffi/python/resource_options.py";
const PYTHON_PACKAGE_OUTPUT: &str = "platforms/python/merman/src/merman/_resource_options.py";

fn pascal_case(value: &str) -> String {
    value
        .split(['_', '-'])
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            let first = chars
                .next()
                .map(|ch| ch.to_ascii_uppercase().to_string())
                .unwrap_or_default();
            format!("{first}{}", chars.as_str())
        })
        .collect()
}

fn camel_case(value: &str) -> String {
    let pascal = pascal_case(value);
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => format!("{}{}", first.to_ascii_lowercase(), chars.as_str()),
        None => String::new(),
    }
}

fn upper_snake(value: &str) -> String {
    value.replace('-', "_").to_ascii_uppercase()
}

fn web_profile_default(contract: &RuntimeResourceContract) -> &'static str {
    let defaults = contract
        .profiles
        .iter()
        .filter(|profile| profile.recommended_binding_default)
        .map(|profile| profile.id)
        .collect::<Vec<_>>();
    assert_eq!(
        defaults,
        [contract.general_binding_default_profile],
        "resource descriptor must recommend exactly its general binding default"
    );
    contract.general_binding_default_profile
}

fn generated_preamble(comment: &str) -> String {
    format!(
        "{comment} {GENERATED_NOTICE}{comment} Do not edit directly; edit the authoritative descriptors in the owning core, render, analysis, ASCII, or export crate.\n\n"
    )
}

fn web_resource_contract() -> RuntimeResourceContract {
    let surface = compiled_runtime_capability_surface()
        .project_to_descriptor_target("web", TextMeasurementProviderProjection::VendoredOnly)
        .expect("the compiled binding surface projects to the Web target");
    runtime_catalog_for(0, surface).resources
}

fn render_c_header(contract: &BindingResourceContract) -> String {
    let profiles = &contract.profiles;
    let limits = &contract.limits;
    let mut out = generated_preamble("//");
    out.push_str("#ifndef MERMAN_RESOURCE_CONTRACT_H\n#define MERMAN_RESOURCE_CONTRACT_H\n\n#include <stddef.h>\n\n");
    writeln!(
        out,
        "#define MERMAN_BINDING_OPTIONS_SCHEMA_VERSION {BINDING_OPTIONS_SCHEMA_VERSION}u\n"
    )
    .unwrap();
    for profile in profiles {
        writeln!(
            out,
            "#define MERMAN_RESOURCE_PROFILE_{} \"{}\"",
            upper_snake(profile.id),
            profile.id,
        )
        .unwrap();
    }
    out.push('\n');
    for limit in limits {
        writeln!(
            out,
            "#define MERMAN_RESOURCE_LIMIT_{} \"{}\"",
            upper_snake(limit.stable_id),
            limit.stable_id,
        )
        .unwrap();
    }
    out.push('\n');
    for limit in limits {
        writeln!(
            out,
            "#define MERMAN_RESOURCE_LIMIT_{}_MINIMUM ((size_t){})",
            upper_snake(limit.stable_id),
            limit.minimum_value
        )
        .unwrap();
        writeln!(
            out,
            "#define MERMAN_RESOURCE_LIMIT_{}_OVERRIDABLE {}",
            upper_snake(limit.stable_id),
            i32::from(limit.overridable)
        )
        .unwrap();
    }
    out.push_str("\n#endif\n");
    out
}

fn render_typescript(contract: &RuntimeResourceContract) -> String {
    let profiles = &contract.profiles;
    let limits = &contract.limits;
    let default_profile = web_profile_default(contract);
    let mut out = generated_preamble("//");
    writeln!(
        out,
        "export const BINDING_OPTIONS_SCHEMA_VERSION = {BINDING_OPTIONS_SCHEMA_VERSION} as const;\n"
    )
    .unwrap();
    out.push_str("export const RESOURCE_PROFILES = [\n");
    for profile in profiles {
        writeln!(out, "  {:?},", profile.id).unwrap();
    }
    out.push_str("] as const;\nexport type ResourceProfile = (typeof RESOURCE_PROFILES)[number];\n\nexport const RESOURCE_LIMIT_IDS = [\n");
    for limit in limits {
        writeln!(out, "  {:?},", limit.id).unwrap();
    }
    out.push_str("] as const;\nexport type ResourceLimitId = (typeof RESOURCE_LIMIT_IDS)[number];\n\nexport const RESOURCE_OVERRIDE_IDS = [\n");
    for limit in limits.iter().filter(|limit| limit.overridable) {
        writeln!(out, "  {:?},", limit.id).unwrap();
    }
    out.push_str("] as const;\nexport type ResourceOverrideId = (typeof RESOURCE_OVERRIDE_IDS)[number];\n\nexport type ResourceLimitOverrides = Partial<Record<ResourceOverrideId, number>>;\n\nexport interface ResourceOptions {\n  profile?: ResourceProfile;\n  limits?: ResourceLimitOverrides;\n}\n\nexport interface RawResourceOptions {\n  profile?: string;\n  limits?: Record<string, number>;\n}\n\ntype ResourceLimitValues = Record<ResourceLimitId, number | null>;\n\nconst RESOURCE_PROFILE_LIMITS: Record<ResourceProfile, ResourceLimitValues> = {\n");
    for profile in profiles {
        writeln!(out, "  {:?}: {{", profile.id).unwrap();
        for limit in limits {
            match profile.limits[limit.id] {
                Some(value) => writeln!(out, "    {:?}: {value},", limit.id).unwrap(),
                None => writeln!(out, "    {:?}: null,", limit.id).unwrap(),
            }
        }
        out.push_str("  },\n");
    }
    out.push_str("};\n\nconst RESOURCE_LIMIT_MINIMUMS: Record<ResourceOverrideId, number> = {\n");
    for limit in limits.iter().filter(|limit| limit.overridable) {
        writeln!(out, "  {:?}: {},", limit.id, limit.minimum_value).unwrap();
    }
    out.push_str("};\n\nexport function resourceOptions(\n  profile?: ResourceProfile,\n  limits: ResourceLimitOverrides = {},\n): ResourceOptions {\n  if (profile !== undefined && !(RESOURCE_PROFILES as readonly string[]).includes(profile)) {\n    throw new RangeError(`unsupported resource profile: ${profile}`);\n  }\n  const normalized: ResourceLimitOverrides = {};\n  for (const [id, value] of Object.entries(limits) as [ResourceOverrideId, number][]) {\n    if (!(RESOURCE_OVERRIDE_IDS as readonly string[]).includes(id)) {\n      throw new RangeError(`resource limit is not overridable: ${id}`);\n    }\n    if (!Number.isSafeInteger(value) || value < RESOURCE_LIMIT_MINIMUMS[id]) {\n      throw new RangeError(`resource limit must be at least ${RESOURCE_LIMIT_MINIMUMS[id]}: ${id}`);\n    }\n    normalized[id] = value;\n  }\n  const resources: ResourceOptions = {};\n  if (profile !== undefined) {\n    resources.profile = profile;\n  }\n  if (Object.keys(normalized).length !== 0) {\n    resources.limits = normalized;\n  }\n  return resources;\n}\n\nexport function tightenResourceOptions(\n  ceiling: ResourceOptions,\n  requested?: ResourceOptions,\n): ResourceOptions {\n  assertResourceOptions(ceiling, \"resource ceiling\");\n  const ceilingProfile = ceiling.profile ?? ");
    write!(out, "{default_profile:?}").unwrap();
    out.push_str(";\n  const normalizedCeiling = resourceOptions(ceilingProfile, ceiling.limits);\n  if (requested === undefined) {\n    return normalizedCeiling;\n  }\n\n  assertResourceOptions(requested, \"requested resources\");\n  const candidate = requested.profile === undefined\n    ? resourceOptions(ceilingProfile, {\n        ...normalizedCeiling.limits,\n        ...(requested.limits ?? {}),\n      })\n    : resourceOptions(requested.profile, requested.limits);\n  const ceilingValues = effectiveResourceLimits(normalizedCeiling);\n  const requestedValues = effectiveResourceLimits(candidate);\n  const tightened: ResourceLimitOverrides = { ...normalizedCeiling.limits };\n  for (const id of RESOURCE_LIMIT_IDS) {\n    const maximum = ceilingValues[id];\n    const value = requestedValues[id];\n    if (maximum !== null && (value === null || value > maximum)) {\n      throw new RangeError(\n        `resources would loosen the transport ceiling for ${id}: requested ${value ?? \"unbounded\"}, maximum ${maximum}`,\n      );\n    }\n    if (\n      value !== null &&\n      (maximum === null || value < maximum) &&\n      (RESOURCE_OVERRIDE_IDS as readonly string[]).includes(id)\n    ) {\n      tightened[id as ResourceOverrideId] = value;\n    }\n  }\n  return Object.keys(tightened).length === 0\n    ? { profile: ceilingProfile }\n    : { profile: ceilingProfile, limits: tightened };\n}\n\nfunction effectiveResourceLimits(options: ResourceOptions): ResourceLimitValues {\n  const profile = options.profile ?? ");
    write!(out, "{default_profile:?}").unwrap();
    out.push_str(";\n  const values = { ...RESOURCE_PROFILE_LIMITS[profile] };\n  for (const [id, value] of Object.entries(options.limits ?? {}) as [ResourceOverrideId, number][]) {\n    values[id] = value;\n  }\n  return values;\n}\n\nfunction assertResourceOptions(value: unknown, label: string): asserts value is ResourceOptions {\n  if (value === null || typeof value !== \"object\" || Array.isArray(value)) {\n    throw new TypeError(`${label} must be an object`);\n  }\n  const limits = (value as ResourceOptions).limits;\n  if (limits !== undefined && (limits === null || typeof limits !== \"object\" || Array.isArray(limits))) {\n    throw new TypeError(`${label}.limits must be an object`);\n  }\n}\n\nexport function resourceOptionsJson(\n  profile?: ResourceProfile,\n  limits: ResourceLimitOverrides = {},\n): string {\n  const resources = resourceOptions(profile, limits);\n  return JSON.stringify(\n    Object.keys(resources).length === 0\n      ? { version: BINDING_OPTIONS_SCHEMA_VERSION }\n      : { version: BINDING_OPTIONS_SCHEMA_VERSION, resources },\n  );\n}\n\nexport function rawResourceOptionsJson(options: RawResourceOptions): string {\n  return JSON.stringify(\n    Object.keys(options).length === 0\n      ? { version: BINDING_OPTIONS_SCHEMA_VERSION }\n      : { version: BINDING_OPTIONS_SCHEMA_VERSION, resources: options },\n  );\n}\n");
    out
}

fn render_kotlin(contract: &BindingResourceContract) -> String {
    let profiles = &contract.profiles;
    let limits = &contract.limits;
    let mut out = generated_preamble("//");
    out.push_str("package io.merman\n\n");
    writeln!(
        out,
        "internal const val MERMAN_BINDING_OPTIONS_SCHEMA_VERSION: Int = {BINDING_OPTIONS_SCHEMA_VERSION}\n"
    )
    .unwrap();
    out.push_str("public enum class MermanResourceProfile(public val id: String) {\n");
    for profile in profiles {
        writeln!(out, "    {}(\"{}\"),", upper_snake(profile.id), profile.id).unwrap();
    }
    out.push_str("}\n\npublic enum class MermanResourceLimitId(public val id: String, public val overridable: Boolean, public val minimumValue: Long) {\n");
    for limit in limits {
        writeln!(
            out,
            "    {}(\"{}\", {}, {}),",
            upper_snake(limit.stable_id),
            limit.stable_id,
            limit.overridable,
            limit.minimum_value
        )
        .unwrap();
    }
    out.push_str("}\n\npublic enum class MermanResourceOverrideId(public val id: String, public val minimumValue: Long) {\n");
    for limit in limits.iter().filter(|limit| limit.overridable) {
        writeln!(
            out,
            "    {}(\"{}\", {}),",
            upper_snake(limit.stable_id),
            limit.stable_id,
            limit.minimum_value
        )
        .unwrap();
    }
    out.push_str("}\n\npublic class MermanResourceOptionsBuilder(\n    private var profile: MermanResourceProfile? = null,\n) {\n    private val limits = linkedMapOf<MermanResourceOverrideId, Long>()\n\n    public fun profile(profile: MermanResourceProfile): MermanResourceOptionsBuilder {\n        this.profile = profile\n        return this\n    }\n\n    public fun limit(id: MermanResourceOverrideId, value: Long): MermanResourceOptionsBuilder {\n        require(value >= id.minimumValue) { \"Resource limit must be at least ${id.minimumValue}: ${id.id}\" }\n        limits[id] = value\n        return this\n    }\n\n    public fun build(): MermanResourceOptions = MermanResourceOptions(profile, limits)\n}\n\npublic class MermanResourceOptions(\n    profile: MermanResourceProfile? = null,\n    limits: Map<MermanResourceOverrideId, Long> = emptyMap(),\n) {\n    public val profile: MermanResourceProfile? = profile\n    public val limits: Map<MermanResourceOverrideId, Long> = limits.toMap()\n\n    init {\n        for ((id, value) in this.limits) {\n            require(value >= id.minimumValue) { \"Resource limit must be at least ${id.minimumValue}: ${id.id}\" }\n        }\n    }\n\n    public fun toOptionsJson(): String {\n        val sorted = limits.entries.sortedBy { it.key.ordinal }\n        val parts = mutableListOf<String>()\n        profile?.let { parts += \"\\\"profile\\\":\\\"${it.id}\\\"\" }\n        if (sorted.isNotEmpty()) {\n            val limitJson = sorted.joinToString(\",\") { \"\\\"${it.key.id}\\\":${it.value}\" }\n            parts += \"\\\"limits\\\":{${limitJson}}\"\n        }\n        return if (parts.isEmpty()) {\n            \"{\\\"version\\\":");
    write!(out, "{BINDING_OPTIONS_SCHEMA_VERSION}").unwrap();
    out.push_str("}\"\n        } else {\n            \"{\\\"version\\\":");
    write!(out, "{BINDING_OPTIONS_SCHEMA_VERSION}").unwrap();
    out.push_str(",\\\"resources\\\":{${parts.joinToString(\",\")}}}\"\n        }\n    }\n}\n");
    out
}

fn render_dart(contract: &BindingResourceContract) -> String {
    let profiles = &contract.profiles;
    let limits = &contract.limits;
    let mut out = generated_preamble("//");
    out.push_str("import 'dart:convert';\n\n");
    writeln!(
        out,
        "const int mermanBindingOptionsSchemaVersion = {BINDING_OPTIONS_SCHEMA_VERSION};\n"
    )
    .unwrap();
    out.push_str("enum MermanResourceProfile {\n");
    for profile in profiles {
        writeln!(out, "  {}('{}'),", camel_case(profile.id), profile.id).unwrap();
    }
    out.push_str(
        r#"  ;

  const MermanResourceProfile(this.id);
  final String id;
}

enum MermanResourceLimitId {
"#,
    );
    for limit in limits {
        let variant = camel_case(limit.stable_id);
        let line = format!(
            "  {variant}('{}', {}, {}),",
            limit.stable_id, limit.overridable, limit.minimum_value
        );
        if line.len() <= 80 {
            writeln!(out, "{line}").unwrap();
        } else {
            writeln!(
                out,
                "  {variant}(\n      '{}', {}, {}),",
                limit.stable_id, limit.overridable, limit.minimum_value
            )
            .unwrap();
        }
    }
    out.push_str(
        r#"  ;

  const MermanResourceLimitId(this.id, this.overridable, this.minimumValue);
  final String id;
  final bool overridable;
  final int minimumValue;
}

enum MermanResourceOverrideId {
"#,
    );
    for limit in limits.iter().filter(|limit| limit.overridable) {
        let variant = camel_case(limit.stable_id);
        let line = format!(
            "  {variant}('{}', {}),",
            limit.stable_id, limit.minimum_value
        );
        if line.len() <= 80 {
            writeln!(out, "{line}").unwrap();
        } else {
            writeln!(
                out,
                "  {variant}(\n      '{}', {}),",
                limit.stable_id, limit.minimum_value
            )
            .unwrap();
        }
    }
    out.push_str(
        r#"  ;

  const MermanResourceOverrideId(this.id, this.minimumValue);
  final String id;
  final int minimumValue;
}

class MermanResourceOptionsBuilder {
  MermanResourceProfile? _profile;
  final Map<MermanResourceOverrideId, int> _limits = {};

  void setProfile(MermanResourceProfile? profile) => _profile = profile;
  void setLimit(MermanResourceOverrideId id, int value) {
    if (value < id.minimumValue)
      throw ArgumentError(
          'Resource limit must be at least ${id.minimumValue}: ${id.id}');
    _limits[id] = value;
  }

  MermanResourceOptions build() => MermanResourceOptions(_profile, _limits);
}

class MermanResourceOptions {
  MermanResourceOptions([
    this.profile,
    Map<MermanResourceOverrideId, int> limits = const {},
  ]) : limits = _validatedLimits(limits);

  final MermanResourceProfile? profile;
  final Map<MermanResourceOverrideId, int> limits;

  static Map<MermanResourceOverrideId, int> _validatedLimits(
    Map<MermanResourceOverrideId, int> limits,
  ) {
    final normalized = Map<MermanResourceOverrideId, int>.from(limits);
    for (final entry in normalized.entries) {
      if (entry.value < entry.key.minimumValue) {
        throw ArgumentError(
            'Resource limit must be at least ${entry.key.minimumValue}: ${entry.key.id}');
      }
    }
    return Map.unmodifiable(normalized);
  }

  String toOptionsJson() {
    final sorted = limits.entries.toList()
      ..sort((a, b) => a.key.index.compareTo(b.key.index));
    final resources = <String, Object?>{
      if (profile != null) 'profile': profile!.id,
      if (sorted.isNotEmpty)
        'limits': <String, int>{
          for (final entry in sorted) entry.key.id: entry.value
        },
    };
    return jsonEncode(<String, Object?>{
      'version': "#,
    );
    write!(out, "{BINDING_OPTIONS_SCHEMA_VERSION}").unwrap();
    out.push_str(
        r#",
      if (resources.isNotEmpty) 'resources': resources,
    });
  }
}
"#,
    );
    out
}

fn render_python(contract: &BindingResourceContract) -> String {
    let profiles = &contract.profiles;
    let limits = &contract.limits;
    let mut out = generated_preamble("#");
    out.push_str("from __future__ import annotations\n\nimport json\nfrom dataclasses import dataclass, field\nfrom enum import Enum\nfrom types import MappingProxyType\nfrom typing import Mapping, Optional\n\n");
    writeln!(
        out,
        "BINDING_OPTIONS_SCHEMA_VERSION = {BINDING_OPTIONS_SCHEMA_VERSION}\n"
    )
    .unwrap();
    out.push_str("class ResourceProfile(str, Enum):\n");
    for profile in profiles {
        writeln!(out, "    {} = \"{}\"", upper_snake(profile.id), profile.id).unwrap();
    }
    out.push_str("\nclass ResourceLimitId(str, Enum):\n");
    for limit in limits {
        writeln!(
            out,
            "    {} = \"{}\"",
            upper_snake(limit.stable_id),
            limit.stable_id
        )
        .unwrap();
    }
    out.push_str("\nclass ResourceOverrideId(str, Enum):\n");
    for limit in limits.iter().filter(|limit| limit.overridable) {
        writeln!(
            out,
            "    {} = \"{}\"",
            upper_snake(limit.stable_id),
            limit.stable_id
        )
        .unwrap();
    }
    out.push_str("\n_MINIMUM_LIMIT_VALUES = {\n");
    for limit in limits.iter().filter(|limit| limit.overridable) {
        writeln!(
            out,
            "    ResourceOverrideId.{}: {},",
            upper_snake(limit.stable_id),
            limit.minimum_value
        )
        .unwrap();
    }
    out.push_str("}\n\ndef _validate_override(limit: ResourceOverrideId, value: int) -> None:\n    if not isinstance(limit, ResourceOverrideId):\n        raise ValueError(f\"resource limit is not overridable: {limit}\")\n    if not isinstance(value, int) or isinstance(value, bool) or value < _MINIMUM_LIMIT_VALUES[limit]:\n        raise ValueError(f\"resource limit must be at least {_MINIMUM_LIMIT_VALUES[limit]}: {limit.value}\")\n\n@dataclass(frozen=True)\nclass ResourceOptions:\n    profile: Optional[ResourceProfile] = None\n    limits: Mapping[ResourceOverrideId, int] = field(default_factory=dict)\n\n    def __post_init__(self) -> None:\n        if self.profile is not None and not isinstance(self.profile, ResourceProfile):\n            raise ValueError(f\"unsupported resource profile: {self.profile}\")\n        normalized = {}\n        for limit, value in self.limits.items():\n            _validate_override(limit, value)\n            normalized[limit] = value\n        object.__setattr__(self, \"limits\", MappingProxyType(normalized))\n\n    def to_options_json(self) -> str:\n        limits = {limit.value: self.limits[limit] for limit in sorted(self.limits, key=lambda item: item.value)}\n        resources = {}\n        if self.profile is not None:\n            resources[\"profile\"] = self.profile.value\n        if limits:\n            resources[\"limits\"] = limits\n        payload = {\"version\": ");
    write!(out, "{BINDING_OPTIONS_SCHEMA_VERSION}").unwrap();
    out.push_str("}\n        if resources:\n            payload[\"resources\"] = resources\n        return json.dumps(payload, separators=(\",\", \":\"), sort_keys=True)\n\n@dataclass\nclass ResourceOptionsBuilder:\n    _profile: Optional[ResourceProfile] = None\n    _limits: dict[ResourceOverrideId, int] = field(default_factory=dict)\n\n    def profile(self, profile: Optional[ResourceProfile]) -> ResourceOptionsBuilder:\n        self._profile = profile\n        return self\n\n    def limit(self, limit: ResourceOverrideId, value: int) -> ResourceOptionsBuilder:\n        _validate_override(limit, value)\n        self._limits[limit] = value\n        return self\n\n    def build(self) -> ResourceOptions:\n        return ResourceOptions(self._profile, dict(self._limits))\n");
    out
}

fn render_uniffi(contract: &BindingResourceContract) -> String {
    let profiles = &contract.profiles;
    let limits = &contract.limits;
    let mut out = generated_preamble("//");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]\npub enum MermanResourceProfile {\n");
    for profile in profiles {
        writeln!(out, "    {},", pascal_case(profile.id)).unwrap();
    }
    out.push_str(
        "}\n\nimpl MermanResourceProfile {\n    fn id(self) -> &'static str { match self {\n",
    );
    for profile in profiles {
        writeln!(
            out,
            "        Self::{} => {:?},",
            pascal_case(profile.id),
            profile.id
        )
        .unwrap();
    }
    out.push_str("        }\n    }\n}\n\n#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]\npub enum MermanResourceOverrideId {\n");
    for limit in limits.iter().filter(|limit| limit.overridable) {
        writeln!(out, "    {},", pascal_case(limit.stable_id)).unwrap();
    }
    out.push_str(
        "}\n\nimpl MermanResourceOverrideId {\n    fn id(self) -> &'static str { match self {\n",
    );
    for limit in limits.iter().filter(|limit| limit.overridable) {
        writeln!(
            out,
            "        Self::{} => {:?},",
            pascal_case(limit.stable_id),
            limit.stable_id
        )
        .unwrap();
    }
    out.push_str("        }\n    }\n}\n\n#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Record)]\npub struct MermanResourceLimitOverride {\n    pub id: MermanResourceOverrideId,\n    pub value: u64,\n}\n\n#[uniffi::export]\npub fn resource_options_json(\n    profile: Option<MermanResourceProfile>,\n    overrides: Vec<MermanResourceLimitOverride>,\n) -> Result<String, MermanError> {\n    let pairs = overrides\n        .iter()\n        .map(|override_| {\n            usize::try_from(override_.value)\n                .map(|value| (override_.id.id(), value))\n                .map_err(|_| MermanError::internal(\"resource override exceeds host usize\"))\n        })\n        .collect::<Result<Vec<_>, _>>()?;\n    let profile_id = profile.map(MermanResourceProfile::id);\n    let bytes = merman_bindings_core::resource_options_json(profile_id, &pairs)\n        .map_err(MermanError::from_binding)?;\n    String::from_utf8(bytes).map_err(|error| MermanError::internal(error.to_string()))\n}\n");
    out
}

fn generated_artifacts() -> Vec<(PathBuf, String)> {
    let binding_contract = binding_resource_contract();
    let web_contract = web_resource_contract();
    let python = render_python(&binding_contract);
    vec![
        (
            PathBuf::from(FFI_HEADER_OUTPUT),
            render_c_header(&binding_contract),
        ),
        (
            PathBuf::from(UNIFFI_RUST_OUTPUT),
            render_uniffi(&binding_contract),
        ),
        (PathBuf::from(WEB_OUTPUT), render_typescript(&web_contract)),
        (
            PathBuf::from(ANDROID_OUTPUT),
            render_kotlin(&binding_contract),
        ),
        (
            PathBuf::from(FLUTTER_OUTPUT),
            render_dart(&binding_contract),
        ),
        (PathBuf::from(UNIFFI_PYTHON_TEMPLATE_OUTPUT), python.clone()),
        (PathBuf::from(PYTHON_PACKAGE_OUTPUT), python),
    ]
}

fn write_artifact(root: &Path, path: &Path, contents: &str) -> Result<(), XtaskError> {
    let full = root.join(path);
    if let Some(parent) = full.parent() {
        fs::create_dir_all(parent).map_err(|source| XtaskError::WriteFile {
            path: parent.display().to_string(),
            source,
        })?;
    }
    fs::write(&full, contents).map_err(|source| XtaskError::WriteFile {
        path: full.display().to_string(),
        source,
    })
}

pub(crate) fn gen_resource_contract(args: Vec<String>) -> Result<(), XtaskError> {
    if !args.is_empty() {
        return Err(XtaskError::Usage);
    }
    let root = crate::cmd::workspace_root();
    for (path, contents) in generated_artifacts() {
        write_artifact(&root, &path, &contents)?;
    }
    Ok(())
}

pub(crate) fn verify_resource_contract_artifacts() -> Result<Option<String>, XtaskError> {
    let root = crate::cmd::workspace_root();
    let mut drift = Vec::new();
    for (path, expected) in generated_artifacts() {
        let full = root.join(&path);
        let actual = fs::read_to_string(&full).map_err(|source| XtaskError::ReadFile {
            path: full.display().to_string(),
            source,
        })?;
        if actual.replace("\r\n", "\n") != expected {
            drift.push(path.display().to_string());
        }
    }
    if drift.is_empty() {
        Ok(None)
    } else {
        Ok(Some(format!(
            "resource contract projections drifted: {}; regenerate with `cargo run -p xtask -- gen-resource-contract`",
            drift.join(", ")
        )))
    }
}

pub(crate) fn verify_resource_contract(args: Vec<String>) -> Result<(), XtaskError> {
    if !args.is_empty() {
        return Err(XtaskError::Usage);
    }
    match verify_resource_contract_artifacts()? {
        Some(message) => Err(XtaskError::VerifyFailed(message)),
        None => Ok(()),
    }
}
