use crate::XtaskError;
use merman_core::baseline::BaselineRegistryProfile;
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const DEFAULT_OUTPUT: &str = "platforms/web/src/generated/diagram-catalog.ts";

fn parse_output_path(args: Vec<String>) -> Result<PathBuf, XtaskError> {
    let mut output = None;
    let mut index = 0;
    while index < args.len() {
        match args[index].as_str() {
            "--out" => {
                index += 1;
                let path = args.get(index).ok_or(XtaskError::Usage)?;
                if output.is_some() {
                    return Err(XtaskError::Usage);
                }
                output = Some(PathBuf::from(path));
            }
            "--help" | "-h" => return Err(XtaskError::Usage),
            _ => return Err(XtaskError::Usage),
        }
        index += 1;
    }
    Ok(output.unwrap_or_else(|| PathBuf::from(DEFAULT_OUTPUT)))
}

fn render_diagram_catalog(diagrams: &[&str]) -> Result<String, XtaskError> {
    let mut output = String::from(
        "// This file is @generated by `cargo run -p xtask -- gen-web-diagram-catalog`.\n\
         // Do not edit it directly; edit the Rust family catalog instead.\n\n\
         export const SUPPORTED_DIAGRAMS = [\n",
    );
    for diagram in diagrams {
        writeln!(&mut output, "  {},", serde_json::to_string(diagram)?)
            .expect("writing to a String cannot fail");
    }
    output.push_str("] as const;\n");
    Ok(output)
}

fn write_catalog(path: &Path, contents: &str) -> Result<(), XtaskError> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|source| XtaskError::WriteFile {
            path: parent.display().to_string(),
            source,
        })?;
    }
    fs::write(path, contents).map_err(|source| XtaskError::WriteFile {
        path: path.display().to_string(),
        source,
    })
}

pub(crate) fn gen_web_diagram_catalog(args: Vec<String>) -> Result<(), XtaskError> {
    let output = parse_output_path(args)?;
    let diagrams = merman_core::supported_diagrams_for_profile(BaselineRegistryProfile::Full);
    write_catalog(&output, &render_diagram_catalog(diagrams)?)
}

#[cfg(test)]
mod tests {
    use super::{DEFAULT_OUTPUT, parse_output_path, render_diagram_catalog};
    use merman_core::baseline::BaselineRegistryProfile;
    use std::fs;
    use std::path::PathBuf;

    #[test]
    fn generator_projects_the_full_registry_in_catalog_order() {
        let diagrams = merman_core::supported_diagrams_for_profile(BaselineRegistryProfile::Full);
        let output = render_diagram_catalog(diagrams).expect("render catalog");

        assert_eq!(diagrams.len(), 35);
        for diagram in [
            "eventmodeling",
            "ishikawa",
            "swimlane",
            "treeView",
            "wardley",
        ] {
            assert!(
                output.contains(&format!("  \"{diagram}\",")),
                "generated catalog omitted {diagram}"
            );
        }
        let offsets: Vec<_> = diagrams
            .iter()
            .map(|diagram| output.find(&format!("  \"{diagram}\",")).unwrap())
            .collect();
        assert!(offsets.windows(2).all(|pair| pair[0] < pair[1]));
    }

    #[test]
    fn output_path_defaults_and_rejects_unknown_arguments() {
        assert_eq!(
            parse_output_path(Vec::new()).unwrap(),
            PathBuf::from(DEFAULT_OUTPUT)
        );
        assert_eq!(
            parse_output_path(vec!["--out".into(), "custom.ts".into()]).unwrap(),
            PathBuf::from("custom.ts")
        );
        assert!(parse_output_path(vec!["--out".into()]).is_err());
        assert!(
            parse_output_path(vec![
                "--out".into(),
                "first.ts".into(),
                "--out".into(),
                "second.ts".into(),
            ])
            .is_err()
        );
        assert!(parse_output_path(vec!["unexpected".into()]).is_err());
    }

    #[test]
    fn committed_catalog_matches_the_full_rust_registry() {
        let expected = render_diagram_catalog(merman_core::supported_diagrams_for_profile(
            BaselineRegistryProfile::Full,
        ))
        .expect("render catalog");
        let path = crate::cmd::workspace_root().join(DEFAULT_OUTPUT);
        let actual = fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));

        assert_eq!(
            actual, expected,
            "regenerate with `cargo run -p xtask -- gen-web-diagram-catalog`"
        );
    }
}
