"""Python package shim for generated merman UniFFI bindings."""
# Generated by `cargo run -p merman-uniffi --example generate_python_package`; do not edit by hand.

from ._text_measurement_protocol import (
    TEXT_MEASUREMENT_PROTOCOL_VERSION,
    TEXT_MEASUREMENT_OPERATIONS,
    TEXT_MEASUREMENT_RESULT_KINDS,
    TextMeasurementProtocolVersionMismatch,
    require_text_measurement_protocol_version,
)

from ._runtime_catalog import (
    MermanRuntimeCatalog,
    MermanRuntimeCatalogError,
    get_runtime_catalog,
)

from ._resource_options import (
    ResourceLimitId,
    ResourceOverrideId,
    ResourceOptions,
    ResourceOptionsBuilder,
    ResourceProfile,
)

try:
    from .merman_uniffi import (
        MermanAsciiCapability,
        MermanAsciiCapabilityEvidence,
        MermanDiagramFamilyCapability,
        MermanEngine,
        MermanError,
        MermanErrorKind,
        MermanLintRuleCatalogEntry,
        MermanOperationRequest,
        MermanOperationResult,
        MermanResourceErrorDetails,
        MermanReusableEngine,
        MermanTextDirection,
        MermanTextMeasureRequest,
        MermanTextMeasureResult,
        MermanTextMeasurementOperation,
        MermanTextMeasurementPhase,
        MermanTextMeasurementResultKind,
        MermanTextMeasurer,
        MermanTextWhiteSpace,
        MermanTextWrapMode,
        MermanValidationResult,
    )
except ModuleNotFoundError as exc:
    if exc.name == f"{__name__}.merman_uniffi":
        raise ImportError(
            "Generated merman UniFFI bindings are missing. "
            "Build an explicit merman-uniffi artifact profile, then run "
            "`cargo run -p merman-uniffi --no-default-features --features 'svg,analysis,ascii,png,jpeg,pdf,layout-cytoscape,layout-elk,math,system-clock,system-timezone,system-random,bindgen-smoke' --example "
            "generate_python_package -- --package-dir platforms/python/merman`."
        ) from exc
    raise

__all__ = [
    "MermanAsciiCapability",
    "MermanAsciiCapabilityEvidence",
    "MermanDiagramFamilyCapability",
    "MermanEngine",
    "MermanError",
    "MermanErrorKind",
    "MermanLintRuleCatalogEntry",
    "MermanOperationRequest",
    "MermanOperationResult",
    "MermanResourceErrorDetails",
    "MermanReusableEngine",
    "ResourceLimitId",
    "ResourceOverrideId",
    "ResourceOptions",
    "ResourceOptionsBuilder",
    "ResourceProfile",
    "MermanRuntimeCatalog",
    "MermanRuntimeCatalogError",
    "MermanValidationResult",
    "get_runtime_catalog",
    "TEXT_MEASUREMENT_PROTOCOL_VERSION",
    "TextMeasurementProtocolVersionMismatch",
    "TEXT_MEASUREMENT_OPERATIONS",
    "TEXT_MEASUREMENT_RESULT_KINDS",
    "MermanTextDirection",
    "MermanTextMeasureRequest",
    "MermanTextMeasureResult",
    "MermanTextMeasurementOperation",
    "MermanTextMeasurementPhase",
    "MermanTextMeasurementResultKind",
    "MermanTextMeasurer",
    "MermanTextWhiteSpace",
    "MermanTextWrapMode",
    "require_text_measurement_protocol_version",
]
