"""Python package shim for generated merman UniFFI bindings."""
# Generated by `cargo run -p merman-uniffi --example generate_python_package`; do not edit by hand.

from ._abi import (
    ABI_VERSION,
    TEXT_MEASUREMENT_OPERATIONS,
    TEXT_MEASUREMENT_RESULT_KINDS,
    AbiVersionMismatch,
    require_abi_version,
)

from ._runtime_contract import (
    MermanRuntimeContract,
    MermanRuntimeContractError,
    MermanRuntimeFeatures,
    MermanTextMeasurementCapabilities,
    get_runtime_contract,
)

try:
    from .merman_uniffi import (
        MermanAsciiCapability,
        MermanAsciiCapabilityEvidence,
        MermanDiagramFamilyCapability,
        MermanEngine,
        MermanError,
        MermanLintRuleCatalogEntry,
        MermanReusableEngine,
        MermanTextDirection,
        MermanTextMeasureRequest,
        MermanTextMeasureResult,
        MermanTextMeasurementOperation,
        MermanTextMeasurementPhase,
        MermanTextMeasurementResultKind,
        MermanTextMeasurer,
        MermanTextWhiteSpace,
        MermanTextWrapMode,
        MermanValidationResult,
    )
except ModuleNotFoundError as exc:
    if exc.name == f"{__name__}.merman_uniffi":
        raise ImportError(
            "Generated merman UniFFI bindings are missing. "
            "Build an explicit merman-uniffi artifact profile, then run "
            "`cargo run -p merman-uniffi --no-default-features --features bindgen-smoke --example "
            "generate_python_package -- --package-dir platforms/python/merman`."
        ) from exc
    raise

__all__ = [
    "ABI_VERSION",
    "AbiVersionMismatch",
    "TEXT_MEASUREMENT_OPERATIONS",
    "TEXT_MEASUREMENT_RESULT_KINDS",
    "MermanAsciiCapability",
    "MermanAsciiCapabilityEvidence",
    "MermanDiagramFamilyCapability",
    "MermanEngine",
    "MermanError",
    "MermanLintRuleCatalogEntry",
    "MermanReusableEngine",
    "MermanRuntimeContract",
    "MermanRuntimeContractError",
    "MermanRuntimeFeatures",
    "MermanTextDirection",
    "MermanTextMeasureRequest",
    "MermanTextMeasureResult",
    "MermanTextMeasurementOperation",
    "MermanTextMeasurementPhase",
    "MermanTextMeasurementResultKind",
    "MermanTextMeasurementCapabilities",
    "MermanTextMeasurer",
    "MermanTextWhiteSpace",
    "MermanTextWrapMode",
    "MermanValidationResult",
    "get_runtime_contract",
    "require_abi_version",
]
