# This file is @generated by `cargo run -p xtask -- gen-text-measurement-abi`.
# Do not edit it directly; edit `abi/merman-v2.json` instead.

ABI_VERSION = 2

TEXT_MEASUREMENT_RESULT_KINDS = (
    (0, "metrics"),
    (1, "length"),
    (2, "horizontal-extents"),
    (3, "wrapped-with-raw-width"),
)

TEXT_MEASUREMENT_OPERATIONS = (
    (0, "measure", "metrics", False),
    (1, "computed-length", "length", False),
    (2, "bbox-x", "horizontal-extents", False),
    (3, "bbox-x-with-ascii-overhang", "horizontal-extents", False),
    (4, "title-bbox-x", "horizontal-extents", False),
    (5, "simple-bbox-width", "length", False),
    (6, "raw-bbox-width", "length", False),
    (7, "tspan-bbox-width", "length", False),
    (8, "tspan-bbox-height", "length", False),
    (9, "wrap-probe-bbox-width", "length", False),
    (10, "simple-bbox-height", "length", False),
    (11, "wrapped", "metrics", False),
    (12, "wrapped-with-raw-width", "wrapped-with-raw-width", False),
    (13, "bounding-client-rect-width", "length", False),
    (14, "create-text-bbox-y-offset", "length", True),
    (15, "mermaid-calculate-text-dimensions", "metrics", False),
    (16, "canvas-measure-text-width", "length", False),
    (17, "create-text-middle-bbox-y-offset", "length", True),
    (18, "raw-bbox-height", "length", False),
)

class AbiVersionMismatch(RuntimeError):
    """Raised when a loaded native library does not implement the packaged ABI."""

    def __init__(self, actual: int) -> None:
        self.expected = ABI_VERSION
        self.actual = actual
        super().__init__(f"expected ABI {self.expected}, got {actual}")


def require_abi_version(actual: int) -> None:
    """Reject a native library whose ABI does not match this package."""
    if actual != ABI_VERSION:
        raise AbiVersionMismatch(actual)
