# @generated by `cargo run -p xtask -- gen-binding-contract`.
# Sources: typed registries in merman-bindings-core. Do not edit directly.

RUNTIME_CATALOG_SCHEMA_VERSION = 1
RUNTIME_CATALOG_IDENTIFIER_PATTERN = "^[a-z0-9][a-z0-9-]*$"
RUNTIME_CATALOG_FIELD_IDENTIFIER_PATTERN = "^[a-z][a-z0-9_-]*$"
RUNTIME_CATALOG_MAX_SAFE_INTEGER = 9007199254740991

CAPABILITY_SPECS = (
    {
        "id": "analysis",
        "implication_ids": (),
    },
    {
        "id": "ascii",
        "implication_ids": (),
    },
    {
        "id": "editor",
        "implication_ids": (),
    },
    {
        "id": "icons",
        "implication_ids": (),
    },
    {
        "id": "jpeg",
        "implication_ids": (),
    },
    {
        "id": "layout-cytoscape",
        "implication_ids": ("svg",),
    },
    {
        "id": "layout-elk",
        "implication_ids": ("svg",),
    },
    {
        "id": "markdown",
        "implication_ids": (),
    },
    {
        "id": "math",
        "implication_ids": ("svg",),
    },
    {
        "id": "network-icons",
        "implication_ids": (),
    },
    {
        "id": "parallel-markdown",
        "implication_ids": (),
    },
    {
        "id": "pdf",
        "implication_ids": (),
    },
    {
        "id": "png",
        "implication_ids": (),
    },
    {
        "id": "rustdoc",
        "implication_ids": ("layout-cytoscape", "layout-elk", "markdown", "math"),
    },
    {
        "id": "shell-completions",
        "implication_ids": (),
    },
    {
        "id": "svg",
        "implication_ids": (),
    },
    {
        "id": "system-clock",
        "implication_ids": (),
    },
    {
        "id": "system-random",
        "implication_ids": (),
    },
    {
        "id": "system-timezone",
        "implication_ids": (),
    },
    {
        "id": "system-timing",
        "implication_ids": (),
    },
)

REQUIRED_PAYLOAD_SCHEMA_VERSIONS = {
    "binding-result": 1,
    "operation-metadata": 1,
}

BINDING_OPERATION_RELATION_SPECS = (
    {
        "operation_id": "analysis-facts-json",
        "availability_capability_id": "analysis",
        "output_id": None,
        "compiled_prerequisite_ids": (),
    },
    {
        "operation_id": "analysis-json",
        "availability_capability_id": "analysis",
        "output_id": None,
        "compiled_prerequisite_ids": (),
    },
    {
        "operation_id": "ascii",
        "availability_capability_id": "ascii",
        "output_id": "ascii",
        "compiled_prerequisite_ids": (),
    },
    {
        "operation_id": "document-analysis-facts-json",
        "availability_capability_id": "analysis",
        "output_id": None,
        "compiled_prerequisite_ids": (),
    },
    {
        "operation_id": "document-analysis-json",
        "availability_capability_id": "analysis",
        "output_id": None,
        "compiled_prerequisite_ids": (),
    },
    {
        "operation_id": "jpeg",
        "availability_capability_id": "jpeg",
        "output_id": "jpeg",
        "compiled_prerequisite_ids": ("svg",),
    },
    {
        "operation_id": "layout-json",
        "availability_capability_id": "svg",
        "output_id": None,
        "compiled_prerequisite_ids": (),
    },
    {
        "operation_id": "pdf",
        "availability_capability_id": "pdf",
        "output_id": "pdf",
        "compiled_prerequisite_ids": ("svg",),
    },
    {
        "operation_id": "png",
        "availability_capability_id": "png",
        "output_id": "png",
        "compiled_prerequisite_ids": ("svg",),
    },
    {
        "operation_id": "semantic-json",
        "availability_capability_id": None,
        "output_id": None,
        "compiled_prerequisite_ids": (),
    },
    {
        "operation_id": "svg",
        "availability_capability_id": "svg",
        "output_id": "svg",
        "compiled_prerequisite_ids": (),
    },
    {
        "operation_id": "svg-plan-json",
        "availability_capability_id": "svg",
        "output_id": None,
        "compiled_prerequisite_ids": (),
    },
    {
        "operation_id": "validation-json",
        "availability_capability_id": "analysis",
        "output_id": None,
        "compiled_prerequisite_ids": (),
    },
)

METADATA_SPECS = (
    {
        "id": "ascii-capabilities",
        "required_capability_id": "ascii",
    },
    {
        "id": "diagram-family-capabilities",
        "required_capability_id": None,
    },
    {
        "id": "lint-rule-catalog",
        "required_capability_id": "analysis",
    },
    {
        "id": "presentation-catalog",
        "required_capability_id": None,
    },
    {
        "id": "supported-diagrams",
        "required_capability_id": None,
    },
    {
        "id": "supported-themes",
        "required_capability_id": None,
    },
)

BINDING_OPTION_GROUP_SPECS = (
    {
        "id": "ascii",
        "always_available": False,
        "any_capability_ids": ("ascii",),
        "requires_svg_pipeline": False,
    },
    {
        "id": "environment",
        "always_available": False,
        "any_capability_ids": (),
        "requires_svg_pipeline": True,
    },
    {
        "id": "fixed_local_offset_minutes",
        "always_available": True,
        "any_capability_ids": (),
        "requires_svg_pipeline": False,
    },
    {
        "id": "fixed_today",
        "always_available": True,
        "any_capability_ids": (),
        "requires_svg_pipeline": False,
    },
    {
        "id": "jpeg",
        "always_available": False,
        "any_capability_ids": ("jpeg",),
        "requires_svg_pipeline": False,
    },
    {
        "id": "layout",
        "always_available": False,
        "any_capability_ids": (),
        "requires_svg_pipeline": True,
    },
    {
        "id": "lint",
        "always_available": False,
        "any_capability_ids": ("analysis",),
        "requires_svg_pipeline": False,
    },
    {
        "id": "parse",
        "always_available": True,
        "any_capability_ids": (),
        "requires_svg_pipeline": False,
    },
    {
        "id": "pdf",
        "always_available": False,
        "any_capability_ids": ("pdf",),
        "requires_svg_pipeline": False,
    },
    {
        "id": "presentation",
        "always_available": False,
        "any_capability_ids": (),
        "requires_svg_pipeline": True,
    },
    {
        "id": "raster",
        "always_available": False,
        "any_capability_ids": ("jpeg", "png"),
        "requires_svg_pipeline": False,
    },
    {
        "id": "resources",
        "always_available": True,
        "any_capability_ids": (),
        "requires_svg_pipeline": False,
    },
    {
        "id": "runtime_policy",
        "always_available": True,
        "any_capability_ids": (),
        "requires_svg_pipeline": False,
    },
    {
        "id": "site_config",
        "always_available": True,
        "any_capability_ids": (),
        "requires_svg_pipeline": False,
    },
    {
        "id": "svg",
        "always_available": False,
        "any_capability_ids": (),
        "requires_svg_pipeline": True,
    },
    {
        "id": "version",
        "always_available": True,
        "any_capability_ids": (),
        "requires_svg_pipeline": False,
    },
)

TEXT_MEASUREMENT_PROVIDER_SPECS = (
    {
        "id": "host-callback",
        "source": "constructor-service",
        "constructor_service_id": "host-text-measurement",
    },
    {
        "id": "vendored",
        "source": "svg-pipeline",
        "constructor_service_id": None,
    },
)

TEXT_MEASUREMENT_PROVIDER_IDS = (
    "host-callback",
    "vendored",
)

BINDING_TRANSPORT_EXPOSURE_SPECS = (
    {
        "id": "android-jni",
        "payload_schema_ids": ("binding-result", "operation-metadata"),
        "constructor_service_candidate_ids": ("host-text-measurement", "icon-registry"),
    },
    {
        "id": "native-c",
        "payload_schema_ids": ("binding-result", "operation-metadata"),
        "constructor_service_candidate_ids": ("host-text-measurement", "icon-registry"),
    },
    {
        "id": "node",
        "payload_schema_ids": ("binding-result", "operation-metadata"),
        "constructor_service_candidate_ids": (),
    },
    {
        "id": "rust",
        "payload_schema_ids": ("binding-result", "operation-metadata"),
        "constructor_service_candidate_ids": ("host-text-measurement", "icon-registry"),
    },
    {
        "id": "typst",
        "payload_schema_ids": (),
        "constructor_service_candidate_ids": (),
    },
    {
        "id": "uniffi",
        "payload_schema_ids": ("binding-result", "operation-metadata"),
        "constructor_service_candidate_ids": ("host-text-measurement", "icon-registry"),
    },
    {
        "id": "web",
        "payload_schema_ids": ("binding-result",),
        "constructor_service_candidate_ids": ("host-text-measurement",),
    },
)
VENDORED_TEXT_MEASUREMENT_PROVIDER_ID = "vendored"
HOST_CALLBACK_TEXT_MEASUREMENT_PROVIDER_ID = "host-callback"

CONSTRUCTOR_SERVICE_SPECS = (
    {
        "id": "host-text-measurement",
        "requires_svg_pipeline": True,
        "provided_text_measurement_provider_ids": ("host-callback",),
        "resource_limits": (
        ),
    },
    {
        "id": "icon-registry",
        "requires_svg_pipeline": True,
        "provided_text_measurement_provider_ids": (),
        "resource_limits": (
            {
                "id": "max_icon_body_bytes",
                "phase": "icon_registry_xml",
                "unit": "bytes",
                "description": "Maximum decoded SVG fragment bytes retained for one direct icon",
                "value": 262144,
            },
            {
                "id": "max_icon_coordinate_magnitude",
                "phase": "icon_registry_geometry",
                "unit": "coordinate_units",
                "description": "Maximum absolute view-box coordinate or positive dimension",
                "value": 1000000,
            },
            {
                "id": "max_icon_id_rewrite_edits_per_body",
                "phase": "icon_registry_xml",
                "unit": "edits",
                "description": "Maximum XML ID declaration and reference rewrites planned for one icon body",
                "value": 16384,
            },
            {
                "id": "max_icon_pack_bytes",
                "phase": "icon_registry_input",
                "unit": "bytes",
                "description": "Maximum encoded bytes admitted from one IconifyJSON pack",
                "value": 16777216,
            },
            {
                "id": "max_icon_registry_alias_depth",
                "phase": "icon_registry_alias",
                "unit": "levels",
                "description": "Maximum resolved alias parent-chain depth",
                "value": 64,
            },
            {
                "id": "max_icon_registry_alias_edges",
                "phase": "icon_registry_alias",
                "unit": "edges",
                "description": "Maximum parent edges inspected by alias resolution",
                "value": 32768,
            },
            {
                "id": "max_icon_registry_alias_entries",
                "phase": "icon_registry_alias",
                "unit": "entries",
                "description": "Maximum alias entries admitted by one registry",
                "value": 32768,
            },
            {
                "id": "max_icon_registry_alias_fanout",
                "phase": "icon_registry_alias",
                "unit": "aliases",
                "description": "Maximum aliases that may directly reference one parent",
                "value": 1024,
            },
            {
                "id": "max_icon_registry_build_work_units",
                "phase": "icon_registry_build",
                "unit": "work_units",
                "description": "Maximum deterministic parse, XML, and alias-resolution work",
                "value": 4000000,
            },
            {
                "id": "max_icon_registry_entries",
                "phase": "icon_registry_alias",
                "unit": "entries",
                "description": "Maximum resolved direct icon and alias entries published",
                "value": 65536,
            },
            {
                "id": "max_icon_registry_icon_entries",
                "phase": "icon_registry_parse",
                "unit": "entries",
                "description": "Maximum direct icon entries admitted by one registry",
                "value": 32768,
            },
            {
                "id": "max_icon_registry_input_bytes",
                "phase": "icon_registry_input",
                "unit": "bytes",
                "description": "Maximum aggregate encoded bytes admitted by one registry",
                "value": 33554432,
            },
            {
                "id": "max_icon_registry_json_depth",
                "phase": "icon_registry_parse",
                "unit": "levels",
                "description": "Maximum JSON nesting depth inspected while ingesting packs",
                "value": 32,
            },
            {
                "id": "max_icon_registry_json_key_bytes",
                "phase": "icon_registry_parse",
                "unit": "bytes",
                "description": "Maximum decoded bytes in any IconifyJSON object key, including unknown extensions",
                "value": 1024,
            },
            {
                "id": "max_icon_registry_json_members",
                "phase": "icon_registry_parse",
                "unit": "members",
                "description": "Maximum aggregate JSON map members and sequence items inspected",
                "value": 1000000,
            },
            {
                "id": "max_icon_registry_name_bytes",
                "phase": "icon_registry_parse",
                "unit": "bytes",
                "description": "Maximum admitted Iconify icon or alias name bytes",
                "value": 128,
            },
            {
                "id": "max_icon_registry_packs",
                "phase": "icon_registry_input",
                "unit": "packs",
                "description": "Maximum IconifyJSON packs admitted by one immutable registry",
                "value": 16,
            },
            {
                "id": "max_icon_registry_prefix_bytes",
                "phase": "icon_registry_parse",
                "unit": "bytes",
                "description": "Maximum admitted Iconify prefix or registration-name bytes",
                "value": 64,
            },
            {
                "id": "max_icon_registry_retained_body_bytes",
                "phase": "icon_registry_retain",
                "unit": "bytes",
                "description": "Maximum aggregate decoded direct-icon SVG body bytes retained",
                "value": 33554432,
            },
            {
                "id": "max_icon_registry_retained_xml_plan_bytes",
                "phase": "icon_registry_retain",
                "unit": "bytes",
                "description": "Maximum aggregate retained XML rewrite and defs-plan bytes",
                "value": 16777216,
            },
            {
                "id": "max_icon_xml_depth_per_body",
                "phase": "icon_registry_xml",
                "unit": "levels",
                "description": "Maximum XML element nesting depth in one direct icon fragment",
                "value": 32,
            },
            {
                "id": "max_icon_xml_elements_per_body",
                "phase": "icon_registry_xml",
                "unit": "elements",
                "description": "Maximum XML elements in one direct icon SVG fragment",
                "value": 4096,
            },
        ),
    },
)
HOST_TEXT_MEASUREMENT_CONSTRUCTOR_SERVICE_ID = "host-text-measurement"
ICON_REGISTRY_CONSTRUCTOR_SERVICE_ID = "icon-registry"
