# This file is @generated by `cargo run -p xtask -- gen-resource-contract`.
# Do not edit directly; edit the authoritative descriptors in the owning core, render, analysis, ASCII, or export crate.

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum
from types import MappingProxyType
from typing import Mapping, Optional

BINDING_OPTIONS_SCHEMA_VERSION = 2

class ResourceProfile(str, Enum):
    INTERACTIVE = "interactive"
    CONSTRAINED = "constrained"
    TRUSTED_NATIVE = "trusted-native"
    UNBOUNDED_FOR_TRUSTED_INPUT = "unbounded-for-trusted-input"

class ResourceLimitId(str, Enum):
    MAX_SOURCE_BYTES = "max_source_bytes"
    MAX_MODEL_ITEMS = "max_model_items"
    MAX_MODEL_TEXT_BYTES = "max_model_text_bytes"
    MAX_MODEL_NESTING_DEPTH = "max_model_nesting_depth"
    MAX_LAYOUT_WORK_UNITS = "max_layout_work_units"
    MAX_SVG_BYTES = "max_svg_bytes"
    MAX_SVG_ELEMENTS = "max_svg_elements"
    MAX_DOCUMENT_DIAGRAMS = "max_document_diagrams"
    MAX_ASCII_GRID_CELLS = "max_ascii_grid_cells"
    MAX_RASTER_WIDTH = "max_raster_width"
    MAX_RASTER_HEIGHT = "max_raster_height"
    MAX_RASTER_PIXELS = "max_raster_pixels"
    MAX_EMBEDDED_IMAGE_BYTES = "max_embedded_image_bytes"
    MAX_TOTAL_EMBEDDED_IMAGE_BYTES = "max_total_embedded_image_bytes"
    MAX_EMBEDDED_IMAGE_PIXELS = "max_embedded_image_pixels"
    MAX_TOTAL_EMBEDDED_IMAGE_PIXELS = "max_total_embedded_image_pixels"
    MAX_PDF_FILTER_IMAGE_PIXELS = "max_pdf_filter_image_pixels"
    MAX_SVG_CONVERSION_ISOLATION_DEPTH = "max_svg_conversion_isolation_depth"
    MAX_SVG_CONVERSION_FILTER_PRIMITIVES_PER_FILTER = "max_svg_conversion_filter_primitives_per_filter"
    MAX_TOTAL_SVG_CONVERSION_FILTER_PRIMITIVES = "max_total_svg_conversion_filter_primitives"
    MAX_SVG_CONVERSION_SUBROOTS = "max_svg_conversion_subroots"
    MAX_NESTED_SVG_IMAGES = "max_nested_svg_images"
    SVG_BACKEND_TREE_NODES = "svg_backend_tree_nodes"

class ResourceOverrideId(str, Enum):
    MAX_SOURCE_BYTES = "max_source_bytes"
    MAX_MODEL_ITEMS = "max_model_items"
    MAX_MODEL_TEXT_BYTES = "max_model_text_bytes"
    MAX_MODEL_NESTING_DEPTH = "max_model_nesting_depth"
    MAX_LAYOUT_WORK_UNITS = "max_layout_work_units"
    MAX_SVG_BYTES = "max_svg_bytes"
    MAX_SVG_ELEMENTS = "max_svg_elements"
    MAX_DOCUMENT_DIAGRAMS = "max_document_diagrams"
    MAX_ASCII_GRID_CELLS = "max_ascii_grid_cells"
    MAX_RASTER_WIDTH = "max_raster_width"
    MAX_RASTER_HEIGHT = "max_raster_height"
    MAX_RASTER_PIXELS = "max_raster_pixels"
    MAX_EMBEDDED_IMAGE_BYTES = "max_embedded_image_bytes"
    MAX_TOTAL_EMBEDDED_IMAGE_BYTES = "max_total_embedded_image_bytes"
    MAX_EMBEDDED_IMAGE_PIXELS = "max_embedded_image_pixels"
    MAX_TOTAL_EMBEDDED_IMAGE_PIXELS = "max_total_embedded_image_pixels"
    MAX_PDF_FILTER_IMAGE_PIXELS = "max_pdf_filter_image_pixels"

_MINIMUM_LIMIT_VALUES = {
    ResourceOverrideId.MAX_SOURCE_BYTES: 1,
    ResourceOverrideId.MAX_MODEL_ITEMS: 1,
    ResourceOverrideId.MAX_MODEL_TEXT_BYTES: 1,
    ResourceOverrideId.MAX_MODEL_NESTING_DEPTH: 1,
    ResourceOverrideId.MAX_LAYOUT_WORK_UNITS: 1,
    ResourceOverrideId.MAX_SVG_BYTES: 1,
    ResourceOverrideId.MAX_SVG_ELEMENTS: 1,
    ResourceOverrideId.MAX_DOCUMENT_DIAGRAMS: 0,
    ResourceOverrideId.MAX_ASCII_GRID_CELLS: 1,
    ResourceOverrideId.MAX_RASTER_WIDTH: 1,
    ResourceOverrideId.MAX_RASTER_HEIGHT: 1,
    ResourceOverrideId.MAX_RASTER_PIXELS: 1,
    ResourceOverrideId.MAX_EMBEDDED_IMAGE_BYTES: 1,
    ResourceOverrideId.MAX_TOTAL_EMBEDDED_IMAGE_BYTES: 1,
    ResourceOverrideId.MAX_EMBEDDED_IMAGE_PIXELS: 1,
    ResourceOverrideId.MAX_TOTAL_EMBEDDED_IMAGE_PIXELS: 1,
    ResourceOverrideId.MAX_PDF_FILTER_IMAGE_PIXELS: 1,
}

def _validate_override(limit: ResourceOverrideId, value: int) -> None:
    if not isinstance(limit, ResourceOverrideId):
        raise ValueError(f"resource limit is not overridable: {limit}")
    if not isinstance(value, int) or isinstance(value, bool) or value < _MINIMUM_LIMIT_VALUES[limit]:
        raise ValueError(f"resource limit must be at least {_MINIMUM_LIMIT_VALUES[limit]}: {limit.value}")

@dataclass(frozen=True)
class ResourceOptions:
    profile: Optional[ResourceProfile] = None
    limits: Mapping[ResourceOverrideId, int] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.profile is not None and not isinstance(self.profile, ResourceProfile):
            raise ValueError(f"unsupported resource profile: {self.profile}")
        normalized = {}
        for limit, value in self.limits.items():
            _validate_override(limit, value)
            normalized[limit] = value
        object.__setattr__(self, "limits", MappingProxyType(normalized))

    def to_options_json(self) -> str:
        limits = {limit.value: self.limits[limit] for limit in sorted(self.limits, key=lambda item: item.value)}
        resources = {}
        if self.profile is not None:
            resources["profile"] = self.profile.value
        if limits:
            resources["limits"] = limits
        payload = {"version": 2}
        if resources:
            payload["resources"] = resources
        return json.dumps(payload, separators=(",", ":"), sort_keys=True)

@dataclass
class ResourceOptionsBuilder:
    _profile: Optional[ResourceProfile] = None
    _limits: dict[ResourceOverrideId, int] = field(default_factory=dict)

    def profile(self, profile: Optional[ResourceProfile]) -> ResourceOptionsBuilder:
        self._profile = profile
        return self

    def limit(self, limit: ResourceOverrideId, value: int) -> ResourceOptionsBuilder:
        _validate_override(limit, value)
        self._limits[limit] = value
        return self

    def build(self) -> ResourceOptions:
        return ResourceOptions(self._profile, dict(self._limits))
