# This file is @generated by `cargo run -p xtask -- gen-resource-contract`.
# Do not edit directly; edit `crates/merman-render/src/resources.rs`.

from __future__ import annotations

import json
from dataclasses import dataclass, field
from enum import Enum
from typing import Mapping

class ResourceProfile(str, Enum):
    INTERACTIVE = "interactive"
    CONSTRAINED = "constrained"
    TRUSTED_NATIVE = "trusted-native"
    UNBOUNDED_FOR_TRUSTED_INPUT = "unbounded-for-trusted-input"

class ResourceLimitId(str, Enum):
    MAX_SOURCE_BYTES = "max_source_bytes"
    MAX_SVG_BYTES = "max_svg_bytes"
    MAX_SVG_ELEMENTS = "max_svg_elements"
    MAX_SVG_TREE_DEPTH = "max_svg_tree_depth"
    MAX_FLOWCHART_NODES = "max_flowchart_nodes"
    MAX_FLOWCHART_EDGES = "max_flowchart_edges"
    MAX_FLOWCHART_SUBGRAPHS = "max_flowchart_subgraphs"
    MAX_CLASS_NODES = "max_class_nodes"
    MAX_CLASS_EDGES = "max_class_edges"
    MAX_CLASS_NAMESPACES = "max_class_namespaces"
    MAX_ZENUML_PARTICIPANTS = "max_zenuml_participants"
    MAX_ZENUML_STATEMENTS = "max_zenuml_statements"
    MAX_ZENUML_FRAGMENTS = "max_zenuml_fragments"
    MAX_VENN_AREAS = "max_venn_areas"
    MAX_SWIMLANE_LINE_HOP_SEGMENT_PAIRS = "max_swimlane_line_hop_segment_pairs"
    MAX_LABEL_BYTES = "max_label_bytes"

_OVERRIDABLE_LIMITS = {
    ResourceLimitId.MAX_SOURCE_BYTES,
    ResourceLimitId.MAX_SVG_BYTES,
    ResourceLimitId.MAX_SVG_ELEMENTS,
    ResourceLimitId.MAX_FLOWCHART_NODES,
    ResourceLimitId.MAX_FLOWCHART_EDGES,
    ResourceLimitId.MAX_FLOWCHART_SUBGRAPHS,
    ResourceLimitId.MAX_CLASS_NODES,
    ResourceLimitId.MAX_CLASS_EDGES,
    ResourceLimitId.MAX_CLASS_NAMESPACES,
    ResourceLimitId.MAX_ZENUML_PARTICIPANTS,
    ResourceLimitId.MAX_ZENUML_STATEMENTS,
    ResourceLimitId.MAX_ZENUML_FRAGMENTS,
    ResourceLimitId.MAX_VENN_AREAS,
    ResourceLimitId.MAX_SWIMLANE_LINE_HOP_SEGMENT_PAIRS,
    ResourceLimitId.MAX_LABEL_BYTES,
}

@dataclass(frozen=True)
class ResourceOptions:
    profile: ResourceProfile = ResourceProfile.INTERACTIVE
    limits: Mapping[ResourceLimitId, int] = field(default_factory=dict)

    def __post_init__(self) -> None:
        for limit, value in self.limits.items():
            if limit not in _OVERRIDABLE_LIMITS:
                raise ValueError(f"resource limit is not overridable: {limit.value}")
            if not isinstance(value, int) or isinstance(value, bool) or value <= 0:
                raise ValueError(f"resource limit must be a positive integer: {limit.value}")

    def to_options_json(self) -> str:
        limits = {limit.value: self.limits[limit] for limit in sorted(self.limits, key=lambda item: item.value)}
        resources = {"profile": self.profile.value}
        if limits:
            resources["limits"] = limits
        return json.dumps({"version": 1, "resources": resources}, separators=(",", ":"), sort_keys=True)

@dataclass
class ResourceOptionsBuilder:
    _profile: ResourceProfile = ResourceProfile.INTERACTIVE
    _limits: dict[ResourceLimitId, int] = field(default_factory=dict)

    def profile(self, profile: ResourceProfile) -> ResourceOptionsBuilder:
        self._profile = profile
        return self

    def limit(self, limit: ResourceLimitId, value: int) -> ResourceOptionsBuilder:
        self._limits[limit] = value
        return self

    def build(self) -> ResourceOptions:
        return ResourceOptions(self._profile, dict(self._limits))
