# This file is @generated by `cargo run -p xtask -- gen-text-measurement-protocol`.
# Do not edit it directly; edit `contracts/abi/text-measurement-v1.json` instead.

TEXT_MEASUREMENT_PROTOCOL_VERSION = 1

TEXT_MEASUREMENT_WRAP_MODES = (
    (0, "svg-like"),
    (1, "svg-like-single-run"),
    (2, "html-like"),
)

TEXT_MEASUREMENT_DIRECTIONS = (
    (0, "auto"),
)

TEXT_MEASUREMENT_WHITE_SPACES = (
    (0, "normal"),
    (1, "nowrap"),
    (2, "break-spaces"),
)

TEXT_MEASUREMENT_PHASES = (
    (0, "layout"),
    (1, "wrap"),
    (2, "svg-bbox"),
    (3, "computed-length"),
)

TEXT_MEASUREMENT_RESULT_KINDS = (
    (0, "metrics"),
    (1, "length"),
    (2, "horizontal-extents"),
    (3, "wrapped-with-raw-width"),
)

TEXT_MEASUREMENT_OPERATIONS = (
    (0, "measure", "metrics", False),
    (1, "computed-length", "length", False),
    (2, "bbox-x", "horizontal-extents", False),
    (3, "bbox-x-with-ascii-overhang", "horizontal-extents", False),
    (4, "title-bbox-x", "horizontal-extents", False),
    (5, "simple-bbox-width", "length", False),
    (6, "raw-bbox-width", "length", False),
    (7, "tspan-bbox-width", "length", False),
    (8, "tspan-bbox-height", "length", False),
    (9, "wrap-probe-bbox-width", "length", False),
    (10, "simple-bbox-height", "length", False),
    (11, "wrapped", "metrics", False),
    (12, "wrapped-with-raw-width", "wrapped-with-raw-width", False),
    (13, "bounding-client-rect-width", "length", False),
    (14, "create-text-bbox-y-offset", "length", True),
    (15, "mermaid-calculate-text-dimensions", "metrics", False),
    (16, "canvas-measure-text-width", "length", False),
    (17, "create-text-middle-bbox-y-offset", "length", True),
    (18, "raw-bbox-height", "length", False),
)

class TextMeasurementProtocolVersionMismatch(RuntimeError):
    """Raised when a host text-measurement protocol version is incompatible."""

    def __init__(self, actual: int) -> None:
        self.expected = TEXT_MEASUREMENT_PROTOCOL_VERSION
        self.actual = actual
        super().__init__(f"expected text-measurement protocol {self.expected}, got {actual}")


def require_text_measurement_protocol_version(actual: int) -> None:
    """Reject an incompatible host text-measurement protocol."""
    if actual != TEXT_MEASUREMENT_PROTOCOL_VERSION:
        raise TextMeasurementProtocolVersionMismatch(actual)
