
using namespace System.Management.Automation
using namespace System.Management.Automation.Language

Register-ArgumentCompleter -Native -CommandName 'merman-cli' -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $commandElements = $commandAst.CommandElements
    $command = @(
        'merman-cli'
        for ($i = 1; $i -lt $commandElements.Count; $i++) {
            $element = $commandElements[$i]
            if ($element -isnot [StringConstantExpressionAst] -or
                $element.StringConstantType -ne [StringConstantType]::BareWord -or
                $element.Value.StartsWith('-') -or
                $element.Value -eq $wordToComplete) {
                break
        }
        $element.Value
    }) -join ';'

    $completions = @(switch ($command) {
        'merman-cli' {
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('lint-rules', 'lint-rules', [CompletionResultType]::ParameterValue, 'List lint rule metadata')
            [CompletionResult]::new('rustdoc', 'rustdoc', [CompletionResultType]::ParameterValue, 'Build or check committed static Mermaid fragments for Rustdoc')
            [CompletionResult]::new('capabilities', 'capabilities', [CompletionResultType]::ParameterValue, 'Print the compiled capabilities from the canonical capability descriptor')
            [CompletionResult]::new('detect', 'detect', [CompletionResultType]::ParameterValue, 'Detect the Mermaid diagram type')
            [CompletionResult]::new('parse', 'parse', [CompletionResultType]::ParameterValue, 'Parse Mermaid source and print the semantic JSON model')
            [CompletionResult]::new('render', 'render', [CompletionResultType]::ParameterValue, 'Render one Mermaid diagram with Merman''s native interface')
            [CompletionResult]::new('batch', 'batch', [CompletionResultType]::ParameterValue, 'Render every Mermaid diagram in one Markdown document')
            [CompletionResult]::new('lint', 'lint', [CompletionResultType]::ParameterValue, 'Analyze Mermaid source and print diagnostics JSON or text')
            [CompletionResult]::new('fix', 'fix', [CompletionResultType]::ParameterValue, 'Apply non-conflicting diagnostics fixes to Mermaid or Markdown source')
            [CompletionResult]::new('completion', 'completion', [CompletionResultType]::ParameterValue, 'Generate shell completion scripts')
            [CompletionResult]::new('layout', 'layout', [CompletionResultType]::ParameterValue, 'Parse and layout Mermaid source, then print layout JSON')
            [CompletionResult]::new('mmdc', 'mmdc', [CompletionResultType]::ParameterValue, 'Render through the pinned mmdc-compatible interface')
            break
        }
        'merman-cli;lint-rules' {
            [CompletionResult]::new('--format', '--format', [CompletionResultType]::ParameterName, 'Output format for rule metadata')
            [CompletionResult]::new('--pretty', '--pretty', [CompletionResultType]::ParameterName, 'Pretty-print JSON output')
            [CompletionResult]::new('--configurable', '--configurable', [CompletionResultType]::ParameterName, 'Only list rules that public lint configuration can reference')
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            break
        }
        'merman-cli;rustdoc' {
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('build', 'build', [CompletionResultType]::ParameterValue, 'Build the complete managed Rustdoc fragment bundle')
            [CompletionResult]::new('check', 'check', [CompletionResultType]::ParameterValue, 'Check the managed Rustdoc fragment bundle without writing')
            break
        }
        'merman-cli;rustdoc;build' {
            [CompletionResult]::new('--config', '--config', [CompletionResultType]::ParameterName, 'Rustdoc fragment configuration file')
            [CompletionResult]::new('--operation-timeout-ms', '--operation-timeout-ms', [CompletionResultType]::ParameterName, 'Cancel the complete command operation after this many milliseconds')
            [CompletionResult]::new('--quiet', '--quiet', [CompletionResultType]::ParameterName, 'Suppress non-error progress output')
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            break
        }
        'merman-cli;rustdoc;check' {
            [CompletionResult]::new('--config', '--config', [CompletionResultType]::ParameterName, 'Rustdoc fragment configuration file')
            [CompletionResult]::new('--operation-timeout-ms', '--operation-timeout-ms', [CompletionResultType]::ParameterName, 'Cancel the complete command operation after this many milliseconds')
            [CompletionResult]::new('--quiet', '--quiet', [CompletionResultType]::ParameterName, 'Suppress non-error progress output')
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            break
        }
        'merman-cli;capabilities' {
            [CompletionResult]::new('--json', '--json', [CompletionResultType]::ParameterName, 'Emit the machine-readable capability document')
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            break
        }
        'merman-cli;detect' {
            [CompletionResult]::new('--resource-profile', '--resource-profile', [CompletionResultType]::ParameterName, 'Resource policy used to bound source acquisition')
            [CompletionResult]::new('--resource-limit', '--resource-limit', [CompletionResultType]::ParameterName, 'Override source bytes as max_source_bytes=POSITIVE_U64')
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            break
        }
        'merman-cli;parse' {
            [CompletionResult]::new('-c', '-c', [CompletionResultType]::ParameterName, 'JSON Mermaid configuration file')
            [CompletionResult]::new('--config-file', '--config-file', [CompletionResultType]::ParameterName, 'JSON Mermaid configuration file')
            [CompletionResult]::new('-t', '-t', [CompletionResultType]::ParameterName, 'Mermaid theme override')
            [CompletionResult]::new('--theme', '--theme', [CompletionResultType]::ParameterName, 'Mermaid theme override')
            [CompletionResult]::new('--runtime', '--runtime', [CompletionResultType]::ParameterName, 'Runtime source for clock, local timezone, and operation randomness')
            [CompletionResult]::new('--fixed-today', '--fixed-today', [CompletionResultType]::ParameterName, 'Override the local "today" date for time-dependent diagrams')
            [CompletionResult]::new('--fixed-local-offset-minutes', '--fixed-local-offset-minutes', [CompletionResultType]::ParameterName, 'Override the local timezone offset in minutes for time-dependent diagrams')
            [CompletionResult]::new('--resource-profile', '--resource-profile', [CompletionResultType]::ParameterName, 'Resource policy for input, semantic models, output, and CLI acquisition')
            [CompletionResult]::new('--resource-limit', '--resource-limit', [CompletionResultType]::ParameterName, 'Override a resource budget as STABLE_ID=POSITIVE_U64. Can be repeated')
            [CompletionResult]::new('--pretty', '--pretty', [CompletionResultType]::ParameterName, 'Pretty-print JSON output')
            [CompletionResult]::new('--meta', '--meta', [CompletionResultType]::ParameterName, 'Include parse metadata alongside the model')
            [CompletionResult]::new('--suppress-errors', '--suppress-errors', [CompletionResultType]::ParameterName, 'Emit an error diagram instead of failing on parse errors')
            [CompletionResult]::new('--system-clock', '--system-clock', [CompletionResultType]::ParameterName, 'Use the system clock while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-timezone', '--system-timezone', [CompletionResultType]::ParameterName, 'Use the system local timezone while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-random', '--system-random', [CompletionResultType]::ParameterName, 'Use system randomness while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-timing', '--system-timing', [CompletionResultType]::ParameterName, 'Enable operation timing diagnostics through the compiled system timing adapter')
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            break
        }
        'merman-cli;render' {
            [CompletionResult]::new('-o', '-o', [CompletionResultType]::ParameterName, 'Output file. Use `-` for stdout')
            [CompletionResult]::new('--output', '--output', [CompletionResultType]::ParameterName, 'Output file. Use `-` for stdout')
            [CompletionResult]::new('--input-kind', '--input-kind', [CompletionResultType]::ParameterName, 'Interpret the input as Mermaid source or an existing SVG document')
            [CompletionResult]::new('-f', '-f', [CompletionResultType]::ParameterName, 'Output format. Defaults to the first compiled output format')
            [CompletionResult]::new('--format', '--format', [CompletionResultType]::ParameterName, 'Output format. Defaults to the first compiled output format')
            [CompletionResult]::new('--svg-pipeline', '--svg-pipeline', [CompletionResultType]::ParameterName, 'SVG output pipeline. Compiled binary exports always start from resvg-safe')
            [CompletionResult]::new('-b', '-b', [CompletionResultType]::ParameterName, 'Background color for the selected rendered output')
            [CompletionResult]::new('--background', '--background', [CompletionResultType]::ParameterName, 'Background color for the selected rendered output')
            [CompletionResult]::new('-C', '-C ', [CompletionResultType]::ParameterName, 'CSS file injected into SVG output before export')
            [CompletionResult]::new('--css-file', '--css-file', [CompletionResultType]::ParameterName, 'CSS file injected into SVG output before export')
            [CompletionResult]::new('-s', '-s', [CompletionResultType]::ParameterName, 'Raster output scale factor. Defaults to 1')
            [CompletionResult]::new('--scale', '--scale', [CompletionResultType]::ParameterName, 'Raster output scale factor. Defaults to 1')
            [CompletionResult]::new('--raster-fit-width', '--raster-fit-width', [CompletionResultType]::ParameterName, 'Fit raster output to this CSS-pixel width before applying --scale')
            [CompletionResult]::new('--raster-fit-height', '--raster-fit-height', [CompletionResultType]::ParameterName, 'Fit raster output to this CSS-pixel height before applying --scale')
            [CompletionResult]::new('--raster-max-width', '--raster-max-width', [CompletionResultType]::ParameterName, 'Maximum raster output width after scale and fit. Defaults to 4096')
            [CompletionResult]::new('--raster-max-height', '--raster-max-height', [CompletionResultType]::ParameterName, 'Maximum raster output height after scale and fit. Defaults to 4096')
            [CompletionResult]::new('--raster-max-pixels', '--raster-max-pixels', [CompletionResultType]::ParameterName, 'Maximum raster output pixels after scale and fit. Defaults to 4096*4096')
            [CompletionResult]::new('--pdf-filter-scale', '--pdf-filter-scale', [CompletionResultType]::ParameterName, 'Sampling scale for SVG filters that require localized PDF bitmaps. Defaults to 4')
            [CompletionResult]::new('--pdf-max-filter-image-pixels', '--pdf-max-filter-image-pixels', [CompletionResultType]::ParameterName, 'Maximum aggregate pixels retained as localized PDF filter images. Defaults to 33554432')
            [CompletionResult]::new('--pdf-max-filter-pixels', '--pdf-max-filter-pixels', [CompletionResultType]::ParameterName, 'Maximum aggregate pixels retained as localized PDF filter images. Defaults to 33554432')
            [CompletionResult]::new('--embedded-image-max-bytes', '--embedded-image-max-bytes', [CompletionResultType]::ParameterName, 'Maximum decoded data-URL bytes for one embedded image. Defaults to 16777216')
            [CompletionResult]::new('--embedded-image-max-total-bytes', '--embedded-image-max-total-bytes', [CompletionResultType]::ParameterName, 'Maximum aggregate decoded data-URL bytes for embedded images. Defaults to 33554432')
            [CompletionResult]::new('--embedded-image-max-pixels', '--embedded-image-max-pixels', [CompletionResultType]::ParameterName, 'Maximum intrinsic pixels for one embedded raster image. Defaults to 16777216')
            [CompletionResult]::new('--embedded-image-max-total-pixels', '--embedded-image-max-total-pixels', [CompletionResultType]::ParameterName, 'Maximum aggregate intrinsic pixels for embedded raster images. Defaults to 33554432')
            [CompletionResult]::new('--icon-pack', '--icon-pack', [CompletionResultType]::ParameterName, 'Iconify package name or local package path. Can be repeated')
            [CompletionResult]::new('--icon-pack-source', '--icon-pack-source', [CompletionResultType]::ParameterName, 'Iconify prefix and source as PREFIX#SOURCE. Can be repeated')
            [CompletionResult]::new('-c', '-c', [CompletionResultType]::ParameterName, 'JSON Mermaid configuration file')
            [CompletionResult]::new('--config-file', '--config-file', [CompletionResultType]::ParameterName, 'JSON Mermaid configuration file')
            [CompletionResult]::new('-t', '-t', [CompletionResultType]::ParameterName, 'Mermaid theme override')
            [CompletionResult]::new('--theme', '--theme', [CompletionResultType]::ParameterName, 'Mermaid theme override')
            [CompletionResult]::new('--runtime', '--runtime', [CompletionResultType]::ParameterName, 'Runtime source for clock, local timezone, and operation randomness')
            [CompletionResult]::new('--fixed-today', '--fixed-today', [CompletionResultType]::ParameterName, 'Override the local "today" date for time-dependent diagrams')
            [CompletionResult]::new('--fixed-local-offset-minutes', '--fixed-local-offset-minutes', [CompletionResultType]::ParameterName, 'Override the local timezone offset in minutes for time-dependent diagrams')
            [CompletionResult]::new('--presentation-profile', '--presentation-profile', [CompletionResultType]::ParameterName, 'First-party presentation profile applied below explicit Mermaid configuration')
            [CompletionResult]::new('--text-measurer', '--text-measurer', [CompletionResultType]::ParameterName, 'Text measurement strategy')
            [CompletionResult]::new('--math-renderer', '--math-renderer', [CompletionResultType]::ParameterName, 'Math renderer override. Unspecified uses the compiled default; `ratex` requires `math`')
            [CompletionResult]::new('-w', '-w', [CompletionResultType]::ParameterName, 'Available container width for size-sensitive layouts')
            [CompletionResult]::new('--width', '--width', [CompletionResultType]::ParameterName, 'Available container width for size-sensitive layouts')
            [CompletionResult]::new('-H', '-H ', [CompletionResultType]::ParameterName, 'Available container height for size-sensitive layouts')
            [CompletionResult]::new('--height', '--height', [CompletionResultType]::ParameterName, 'Available container height for size-sensitive layouts')
            [CompletionResult]::new('-I', '-I ', [CompletionResultType]::ParameterName, 'Root SVG id and internal marker prefix')
            [CompletionResult]::new('--svg-id', '--svg-id', [CompletionResultType]::ParameterName, 'Root SVG id and internal marker prefix')
            [CompletionResult]::new('--hand-drawn-seed', '--hand-drawn-seed', [CompletionResultType]::ParameterName, 'Stabilize rough/hand-drawn rendering where supported')
            [CompletionResult]::new('--ascii-charset', '--ascii-charset', [CompletionResultType]::ParameterName, 'Override the text renderer character set')
            [CompletionResult]::new('--ascii-width-profile', '--ascii-width-profile', [CompletionResultType]::ParameterName, 'Display-width convention used for terminal text measurement')
            [CompletionResult]::new('--ascii-flowchart-node-label-wrap-width', '--ascii-flowchart-node-label-wrap-width', [CompletionResultType]::ParameterName, 'Flowchart node-label wrap width in terminal display cells')
            [CompletionResult]::new('--ascii-direction', '--ascii-direction', [CompletionResultType]::ParameterName, 'Override the default graph direction when Mermaid input omits one')
            [CompletionResult]::new('--ascii-color', '--ascii-color', [CompletionResultType]::ParameterName, 'Color mode for terminal text output')
            [CompletionResult]::new('--xychart-vertical-plot-height', '--xychart-vertical-plot-height', [CompletionResultType]::ParameterName, 'XYChart vertical plot height for text output')
            [CompletionResult]::new('--xychart-category-band-width', '--xychart-category-band-width', [CompletionResultType]::ParameterName, 'XYChart category band width for text output')
            [CompletionResult]::new('--xychart-horizontal-plot-width', '--xychart-horizontal-plot-width', [CompletionResultType]::ParameterName, 'XYChart horizontal plot width for text output')
            [CompletionResult]::new('--ascii-max-grid-cells', '--ascii-max-grid-cells', [CompletionResultType]::ParameterName, 'Maximum graph grid cells for text route planning')
            [CompletionResult]::new('--ascii-max-width', '--ascii-max-width', [CompletionResultType]::ParameterName, 'Maximum terminal display-cell width for ASCII/Unicode output')
            [CompletionResult]::new('--ascii-overflow', '--ascii-overflow', [CompletionResultType]::ParameterName, 'Width overflow behavior for ASCII/Unicode output')
            [CompletionResult]::new('--ascii-layout-profile', '--ascii-layout-profile', [CompletionResultType]::ParameterName, 'Select the canonical or opt-in compact ASCII layout profile')
            [CompletionResult]::new('--resource-profile', '--resource-profile', [CompletionResultType]::ParameterName, 'Resource policy for input, semantic models, output, and CLI acquisition')
            [CompletionResult]::new('--resource-limit', '--resource-limit', [CompletionResultType]::ParameterName, 'Override a resource budget as STABLE_ID=POSITIVE_U64. Can be repeated')
            [CompletionResult]::new('--operation-timeout-ms', '--operation-timeout-ms', [CompletionResultType]::ParameterName, 'Cancel the complete command operation after this many milliseconds')
            [CompletionResult]::new('-q', '-q', [CompletionResultType]::ParameterName, 'Suppress non-error log output')
            [CompletionResult]::new('--quiet', '--quiet', [CompletionResultType]::ParameterName, 'Suppress non-error log output')
            [CompletionResult]::new('--raster-unbounded', '--raster-unbounded', [CompletionResultType]::ParameterName, 'Disable raster size limits. Use only for trusted oversized exports')
            [CompletionResult]::new('--pdf-filter-images-unbounded', '--pdf-filter-images-unbounded', [CompletionResultType]::ParameterName, 'Disable the retained PDF filter-image pixel budget for trusted inputs')
            [CompletionResult]::new('--pdf-filter-unbounded', '--pdf-filter-unbounded', [CompletionResultType]::ParameterName, 'Disable the retained PDF filter-image pixel budget for trusted inputs')
            [CompletionResult]::new('--embedded-images-unbounded', '--embedded-images-unbounded', [CompletionResultType]::ParameterName, 'Disable embedded raster image decode budgets for trusted inputs')
            [CompletionResult]::new('--allow-network', '--allow-network', [CompletionResultType]::ParameterName, 'Allow icon pack loading from public HTTP(S) destinations')
            [CompletionResult]::new('--allow-private-network', '--allow-private-network', [CompletionResultType]::ParameterName, 'Allow explicitly configured icon URLs to resolve to private or loopback addresses')
            [CompletionResult]::new('--suppress-errors', '--suppress-errors', [CompletionResultType]::ParameterName, 'Emit an error diagram instead of failing on parse errors')
            [CompletionResult]::new('--system-clock', '--system-clock', [CompletionResultType]::ParameterName, 'Use the system clock while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-timezone', '--system-timezone', [CompletionResultType]::ParameterName, 'Use the system local timezone while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-random', '--system-random', [CompletionResultType]::ParameterName, 'Use system randomness while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-timing', '--system-timing', [CompletionResultType]::ParameterName, 'Enable operation timing diagnostics through the compiled system timing adapter')
            [CompletionResult]::new('--sequence-mirror-actors', '--sequence-mirror-actors', [CompletionResultType]::ParameterName, 'Mirror sequence participants below lifelines for ASCII/Unicode output')
            [CompletionResult]::new('--ascii-trim-trailing-spaces', '--ascii-trim-trailing-spaces', [CompletionResultType]::ParameterName, 'Remove renderer-owned trailing spaces from emitted text rows')
            [CompletionResult]::new('--ascii-report', '--ascii-report', [CompletionResultType]::ParameterName, 'Emit the canonical ASCII report JSON instead of text bytes')
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            break
        }
        'merman-cli;batch' {
            [CompletionResult]::new('--stdin-file-name', '--stdin-file-name', [CompletionResultType]::ParameterName, 'Logical source file name for Markdown read from stdin')
            [CompletionResult]::new('-o', '-o', [CompletionResultType]::ParameterName, 'Tool-owned directory for the rewritten document and generated artifacts')
            [CompletionResult]::new('--output-dir', '--output-dir', [CompletionResultType]::ParameterName, 'Tool-owned directory for the rewritten document and generated artifacts')
            [CompletionResult]::new('-j', '-j', [CompletionResultType]::ParameterName, 'Maximum number of Markdown charts rendered concurrently')
            [CompletionResult]::new('--jobs', '--jobs', [CompletionResultType]::ParameterName, 'Maximum number of Markdown charts rendered concurrently')
            [CompletionResult]::new('-f', '-f', [CompletionResultType]::ParameterName, 'Output format. Defaults to SVG')
            [CompletionResult]::new('--format', '--format', [CompletionResultType]::ParameterName, 'Output format. Defaults to SVG')
            [CompletionResult]::new('--svg-pipeline', '--svg-pipeline', [CompletionResultType]::ParameterName, 'SVG output pipeline. Compiled binary exports always start from resvg-safe')
            [CompletionResult]::new('-b', '-b', [CompletionResultType]::ParameterName, 'Background color for the selected rendered output')
            [CompletionResult]::new('--background', '--background', [CompletionResultType]::ParameterName, 'Background color for the selected rendered output')
            [CompletionResult]::new('-C', '-C ', [CompletionResultType]::ParameterName, 'CSS file injected into SVG output before export')
            [CompletionResult]::new('--css-file', '--css-file', [CompletionResultType]::ParameterName, 'CSS file injected into SVG output before export')
            [CompletionResult]::new('-s', '-s', [CompletionResultType]::ParameterName, 'Raster output scale factor. Defaults to 1')
            [CompletionResult]::new('--scale', '--scale', [CompletionResultType]::ParameterName, 'Raster output scale factor. Defaults to 1')
            [CompletionResult]::new('--raster-fit-width', '--raster-fit-width', [CompletionResultType]::ParameterName, 'Fit raster output to this CSS-pixel width before applying --scale')
            [CompletionResult]::new('--raster-fit-height', '--raster-fit-height', [CompletionResultType]::ParameterName, 'Fit raster output to this CSS-pixel height before applying --scale')
            [CompletionResult]::new('--raster-max-width', '--raster-max-width', [CompletionResultType]::ParameterName, 'Maximum raster output width after scale and fit. Defaults to 4096')
            [CompletionResult]::new('--raster-max-height', '--raster-max-height', [CompletionResultType]::ParameterName, 'Maximum raster output height after scale and fit. Defaults to 4096')
            [CompletionResult]::new('--raster-max-pixels', '--raster-max-pixels', [CompletionResultType]::ParameterName, 'Maximum raster output pixels after scale and fit. Defaults to 4096*4096')
            [CompletionResult]::new('--pdf-filter-scale', '--pdf-filter-scale', [CompletionResultType]::ParameterName, 'Sampling scale for SVG filters that require localized PDF bitmaps. Defaults to 4')
            [CompletionResult]::new('--pdf-max-filter-image-pixels', '--pdf-max-filter-image-pixels', [CompletionResultType]::ParameterName, 'Maximum aggregate pixels retained as localized PDF filter images. Defaults to 33554432')
            [CompletionResult]::new('--pdf-max-filter-pixels', '--pdf-max-filter-pixels', [CompletionResultType]::ParameterName, 'Maximum aggregate pixels retained as localized PDF filter images. Defaults to 33554432')
            [CompletionResult]::new('--embedded-image-max-bytes', '--embedded-image-max-bytes', [CompletionResultType]::ParameterName, 'Maximum decoded data-URL bytes for one embedded image. Defaults to 16777216')
            [CompletionResult]::new('--embedded-image-max-total-bytes', '--embedded-image-max-total-bytes', [CompletionResultType]::ParameterName, 'Maximum aggregate decoded data-URL bytes for embedded images. Defaults to 33554432')
            [CompletionResult]::new('--embedded-image-max-pixels', '--embedded-image-max-pixels', [CompletionResultType]::ParameterName, 'Maximum intrinsic pixels for one embedded raster image. Defaults to 16777216')
            [CompletionResult]::new('--embedded-image-max-total-pixels', '--embedded-image-max-total-pixels', [CompletionResultType]::ParameterName, 'Maximum aggregate intrinsic pixels for embedded raster images. Defaults to 33554432')
            [CompletionResult]::new('--icon-pack', '--icon-pack', [CompletionResultType]::ParameterName, 'Iconify package name or local package path. Can be repeated')
            [CompletionResult]::new('--icon-pack-source', '--icon-pack-source', [CompletionResultType]::ParameterName, 'Iconify prefix and source as PREFIX#SOURCE. Can be repeated')
            [CompletionResult]::new('-c', '-c', [CompletionResultType]::ParameterName, 'JSON Mermaid configuration file')
            [CompletionResult]::new('--config-file', '--config-file', [CompletionResultType]::ParameterName, 'JSON Mermaid configuration file')
            [CompletionResult]::new('-t', '-t', [CompletionResultType]::ParameterName, 'Mermaid theme override')
            [CompletionResult]::new('--theme', '--theme', [CompletionResultType]::ParameterName, 'Mermaid theme override')
            [CompletionResult]::new('--runtime', '--runtime', [CompletionResultType]::ParameterName, 'Runtime source for clock, local timezone, and operation randomness')
            [CompletionResult]::new('--fixed-today', '--fixed-today', [CompletionResultType]::ParameterName, 'Override the local "today" date for time-dependent diagrams')
            [CompletionResult]::new('--fixed-local-offset-minutes', '--fixed-local-offset-minutes', [CompletionResultType]::ParameterName, 'Override the local timezone offset in minutes for time-dependent diagrams')
            [CompletionResult]::new('--presentation-profile', '--presentation-profile', [CompletionResultType]::ParameterName, 'First-party presentation profile applied below explicit Mermaid configuration')
            [CompletionResult]::new('--text-measurer', '--text-measurer', [CompletionResultType]::ParameterName, 'Text measurement strategy')
            [CompletionResult]::new('--math-renderer', '--math-renderer', [CompletionResultType]::ParameterName, 'Math renderer override. Unspecified uses the compiled default; `ratex` requires `math`')
            [CompletionResult]::new('-w', '-w', [CompletionResultType]::ParameterName, 'Available container width for size-sensitive layouts')
            [CompletionResult]::new('--width', '--width', [CompletionResultType]::ParameterName, 'Available container width for size-sensitive layouts')
            [CompletionResult]::new('-H', '-H ', [CompletionResultType]::ParameterName, 'Available container height for size-sensitive layouts')
            [CompletionResult]::new('--height', '--height', [CompletionResultType]::ParameterName, 'Available container height for size-sensitive layouts')
            [CompletionResult]::new('-I', '-I ', [CompletionResultType]::ParameterName, 'Root SVG id and internal marker prefix')
            [CompletionResult]::new('--svg-id', '--svg-id', [CompletionResultType]::ParameterName, 'Root SVG id and internal marker prefix')
            [CompletionResult]::new('--hand-drawn-seed', '--hand-drawn-seed', [CompletionResultType]::ParameterName, 'Stabilize rough/hand-drawn rendering where supported')
            [CompletionResult]::new('--resource-profile', '--resource-profile', [CompletionResultType]::ParameterName, 'Resource policy for input, semantic models, output, and CLI acquisition')
            [CompletionResult]::new('--resource-limit', '--resource-limit', [CompletionResultType]::ParameterName, 'Override a resource budget as STABLE_ID=POSITIVE_U64. Can be repeated')
            [CompletionResult]::new('--operation-timeout-ms', '--operation-timeout-ms', [CompletionResultType]::ParameterName, 'Cancel the complete command operation after this many milliseconds')
            [CompletionResult]::new('-q', '-q', [CompletionResultType]::ParameterName, 'Suppress non-error log output')
            [CompletionResult]::new('--quiet', '--quiet', [CompletionResultType]::ParameterName, 'Suppress non-error log output')
            [CompletionResult]::new('--raster-unbounded', '--raster-unbounded', [CompletionResultType]::ParameterName, 'Disable raster size limits. Use only for trusted oversized exports')
            [CompletionResult]::new('--pdf-filter-images-unbounded', '--pdf-filter-images-unbounded', [CompletionResultType]::ParameterName, 'Disable the retained PDF filter-image pixel budget for trusted inputs')
            [CompletionResult]::new('--pdf-filter-unbounded', '--pdf-filter-unbounded', [CompletionResultType]::ParameterName, 'Disable the retained PDF filter-image pixel budget for trusted inputs')
            [CompletionResult]::new('--embedded-images-unbounded', '--embedded-images-unbounded', [CompletionResultType]::ParameterName, 'Disable embedded raster image decode budgets for trusted inputs')
            [CompletionResult]::new('--allow-network', '--allow-network', [CompletionResultType]::ParameterName, 'Allow icon pack loading from public HTTP(S) destinations')
            [CompletionResult]::new('--allow-private-network', '--allow-private-network', [CompletionResultType]::ParameterName, 'Allow explicitly configured icon URLs to resolve to private or loopback addresses')
            [CompletionResult]::new('--suppress-errors', '--suppress-errors', [CompletionResultType]::ParameterName, 'Emit an error diagram instead of failing on parse errors')
            [CompletionResult]::new('--system-clock', '--system-clock', [CompletionResultType]::ParameterName, 'Use the system clock while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-timezone', '--system-timezone', [CompletionResultType]::ParameterName, 'Use the system local timezone while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-random', '--system-random', [CompletionResultType]::ParameterName, 'Use system randomness while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-timing', '--system-timing', [CompletionResultType]::ParameterName, 'Enable operation timing diagnostics through the compiled system timing adapter')
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            break
        }
        'merman-cli;lint' {
            [CompletionResult]::new('--stdin-file-name', '--stdin-file-name', [CompletionResultType]::ParameterName, 'Optional file name to use when linting stdin')
            [CompletionResult]::new('--format', '--format', [CompletionResultType]::ParameterName, 'Output format for diagnostics')
            [CompletionResult]::new('-c', '-c', [CompletionResultType]::ParameterName, 'JSON Mermaid configuration file')
            [CompletionResult]::new('--config-file', '--config-file', [CompletionResultType]::ParameterName, 'JSON Mermaid configuration file')
            [CompletionResult]::new('--runtime', '--runtime', [CompletionResultType]::ParameterName, 'Runtime source for clock, local timezone, and operation randomness')
            [CompletionResult]::new('--fixed-today', '--fixed-today', [CompletionResultType]::ParameterName, 'Override the local "today" date for time-dependent diagrams')
            [CompletionResult]::new('--fixed-local-offset-minutes', '--fixed-local-offset-minutes', [CompletionResultType]::ParameterName, 'Override the local timezone offset in minutes for time-dependent diagrams')
            [CompletionResult]::new('--lint-profile', '--lint-profile', [CompletionResultType]::ParameterName, 'Built-in lint rule profile: core, recommended, or strict')
            [CompletionResult]::new('--enable-rule', '--enable-rule', [CompletionResultType]::ParameterName, 'Enable a configurable lint rule by stable rule id. Can be repeated')
            [CompletionResult]::new('--disable-rule', '--disable-rule', [CompletionResultType]::ParameterName, 'Disable a configurable lint rule by stable rule id. Can be repeated')
            [CompletionResult]::new('--rule-severity', '--rule-severity', [CompletionResultType]::ParameterName, 'Override a configurable lint rule severity as RULE_ID=error|warning|info|hint. Can be repeated')
            [CompletionResult]::new('--resource-profile', '--resource-profile', [CompletionResultType]::ParameterName, 'Resource policy for input, semantic models, output, and CLI acquisition')
            [CompletionResult]::new('--resource-limit', '--resource-limit', [CompletionResultType]::ParameterName, 'Override a resource budget as STABLE_ID=POSITIVE_U64. Can be repeated')
            [CompletionResult]::new('--pretty', '--pretty', [CompletionResultType]::ParameterName, 'Pretty-print JSON output')
            [CompletionResult]::new('--markdown', '--markdown', [CompletionResultType]::ParameterName, 'Include Markdown fence diagnostics by scanning `.md`, `.markdown`, or `.mdx` input')
            [CompletionResult]::new('--system-clock', '--system-clock', [CompletionResultType]::ParameterName, 'Use the system clock while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-timezone', '--system-timezone', [CompletionResultType]::ParameterName, 'Use the system local timezone while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-random', '--system-random', [CompletionResultType]::ParameterName, 'Use system randomness while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-timing', '--system-timing', [CompletionResultType]::ParameterName, 'Enable operation timing diagnostics through the compiled system timing adapter')
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            break
        }
        'merman-cli;fix' {
            [CompletionResult]::new('--stdin-file-name', '--stdin-file-name', [CompletionResultType]::ParameterName, 'Optional file name to use when fixing stdin')
            [CompletionResult]::new('-o', '-o', [CompletionResultType]::ParameterName, 'Write the result to this file instead of stdout')
            [CompletionResult]::new('--output', '--output', [CompletionResultType]::ParameterName, 'Write the result to this file instead of stdout')
            [CompletionResult]::new('--rule', '--rule', [CompletionResultType]::ParameterName, 'Restrict fixes to this fixable lint rule id. Can be repeated')
            [CompletionResult]::new('--fix', '--fix', [CompletionResultType]::ParameterName, 'Select an exact stable fix id. Can be repeated')
            [CompletionResult]::new('-c', '-c', [CompletionResultType]::ParameterName, 'JSON Mermaid configuration file')
            [CompletionResult]::new('--config-file', '--config-file', [CompletionResultType]::ParameterName, 'JSON Mermaid configuration file')
            [CompletionResult]::new('--runtime', '--runtime', [CompletionResultType]::ParameterName, 'Runtime source for clock, local timezone, and operation randomness')
            [CompletionResult]::new('--fixed-today', '--fixed-today', [CompletionResultType]::ParameterName, 'Override the local "today" date for time-dependent diagrams')
            [CompletionResult]::new('--fixed-local-offset-minutes', '--fixed-local-offset-minutes', [CompletionResultType]::ParameterName, 'Override the local timezone offset in minutes for time-dependent diagrams')
            [CompletionResult]::new('--lint-profile', '--lint-profile', [CompletionResultType]::ParameterName, 'Built-in lint rule profile: core, recommended, or strict')
            [CompletionResult]::new('--enable-rule', '--enable-rule', [CompletionResultType]::ParameterName, 'Enable a configurable lint rule by stable rule id. Can be repeated')
            [CompletionResult]::new('--disable-rule', '--disable-rule', [CompletionResultType]::ParameterName, 'Disable a configurable lint rule by stable rule id. Can be repeated')
            [CompletionResult]::new('--rule-severity', '--rule-severity', [CompletionResultType]::ParameterName, 'Override a configurable lint rule severity as RULE_ID=error|warning|info|hint. Can be repeated')
            [CompletionResult]::new('--resource-profile', '--resource-profile', [CompletionResultType]::ParameterName, 'Resource policy for input, semantic models, output, and CLI acquisition')
            [CompletionResult]::new('--resource-limit', '--resource-limit', [CompletionResultType]::ParameterName, 'Override a resource budget as STABLE_ID=POSITIVE_U64. Can be repeated')
            [CompletionResult]::new('--check', '--check', [CompletionResultType]::ParameterName, 'Exit 1 when the selected fixes would change the source')
            [CompletionResult]::new('--diff', '--diff', [CompletionResultType]::ParameterName, 'Print a unified diff and exit 1 when the source would change')
            [CompletionResult]::new('--write', '--write', [CompletionResultType]::ParameterName, 'Write the result back to the input file')
            [CompletionResult]::new('-q', '-q', [CompletionResultType]::ParameterName, 'Suppress non-error fix selection diagnostics')
            [CompletionResult]::new('--quiet', '--quiet', [CompletionResultType]::ParameterName, 'Suppress non-error fix selection diagnostics')
            [CompletionResult]::new('--markdown', '--markdown', [CompletionResultType]::ParameterName, 'Include Markdown fence diagnostics by scanning `.md`, `.markdown`, or `.mdx` input')
            [CompletionResult]::new('--system-clock', '--system-clock', [CompletionResultType]::ParameterName, 'Use the system clock while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-timezone', '--system-timezone', [CompletionResultType]::ParameterName, 'Use the system local timezone while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-random', '--system-random', [CompletionResultType]::ParameterName, 'Use system randomness while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-timing', '--system-timing', [CompletionResultType]::ParameterName, 'Enable operation timing diagnostics through the compiled system timing adapter')
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            break
        }
        'merman-cli;completion' {
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            break
        }
        'merman-cli;layout' {
            [CompletionResult]::new('-c', '-c', [CompletionResultType]::ParameterName, 'JSON Mermaid configuration file')
            [CompletionResult]::new('--config-file', '--config-file', [CompletionResultType]::ParameterName, 'JSON Mermaid configuration file')
            [CompletionResult]::new('-t', '-t', [CompletionResultType]::ParameterName, 'Mermaid theme override')
            [CompletionResult]::new('--theme', '--theme', [CompletionResultType]::ParameterName, 'Mermaid theme override')
            [CompletionResult]::new('--runtime', '--runtime', [CompletionResultType]::ParameterName, 'Runtime source for clock, local timezone, and operation randomness')
            [CompletionResult]::new('--fixed-today', '--fixed-today', [CompletionResultType]::ParameterName, 'Override the local "today" date for time-dependent diagrams')
            [CompletionResult]::new('--fixed-local-offset-minutes', '--fixed-local-offset-minutes', [CompletionResultType]::ParameterName, 'Override the local timezone offset in minutes for time-dependent diagrams')
            [CompletionResult]::new('--text-measurer', '--text-measurer', [CompletionResultType]::ParameterName, 'Text measurement strategy')
            [CompletionResult]::new('--math-renderer', '--math-renderer', [CompletionResultType]::ParameterName, 'Math renderer override. Unspecified uses the compiled default; `ratex` requires `math`')
            [CompletionResult]::new('-w', '-w', [CompletionResultType]::ParameterName, 'Available container width for size-sensitive layouts')
            [CompletionResult]::new('--width', '--width', [CompletionResultType]::ParameterName, 'Available container width for size-sensitive layouts')
            [CompletionResult]::new('-H', '-H ', [CompletionResultType]::ParameterName, 'Available container height for size-sensitive layouts')
            [CompletionResult]::new('--height', '--height', [CompletionResultType]::ParameterName, 'Available container height for size-sensitive layouts')
            [CompletionResult]::new('--resource-profile', '--resource-profile', [CompletionResultType]::ParameterName, 'Resource policy for input, semantic models, output, and CLI acquisition')
            [CompletionResult]::new('--resource-limit', '--resource-limit', [CompletionResultType]::ParameterName, 'Override a resource budget as STABLE_ID=POSITIVE_U64. Can be repeated')
            [CompletionResult]::new('--operation-timeout-ms', '--operation-timeout-ms', [CompletionResultType]::ParameterName, 'Cancel the complete command operation after this many milliseconds')
            [CompletionResult]::new('--pretty', '--pretty', [CompletionResultType]::ParameterName, 'Pretty-print JSON output')
            [CompletionResult]::new('--suppress-errors', '--suppress-errors', [CompletionResultType]::ParameterName, 'Emit an error diagram instead of failing on parse errors')
            [CompletionResult]::new('--system-clock', '--system-clock', [CompletionResultType]::ParameterName, 'Use the system clock while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-timezone', '--system-timezone', [CompletionResultType]::ParameterName, 'Use the system local timezone while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-random', '--system-random', [CompletionResultType]::ParameterName, 'Use system randomness while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-timing', '--system-timing', [CompletionResultType]::ParameterName, 'Enable operation timing diagnostics through the compiled system timing adapter')
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            break
        }
        'merman-cli;mmdc' {
            [CompletionResult]::new('-i', '-i', [CompletionResultType]::ParameterName, 'Input Mermaid file. Use `-` for stdin')
            [CompletionResult]::new('--input', '--input', [CompletionResultType]::ParameterName, 'Input Mermaid file. Use `-` for stdin')
            [CompletionResult]::new('-o', '-o', [CompletionResultType]::ParameterName, 'Output file. Use `-` for stdout')
            [CompletionResult]::new('--output', '--output', [CompletionResultType]::ParameterName, 'Output file. Use `-` for stdout')
            [CompletionResult]::new('-a', '-a', [CompletionResultType]::ParameterName, 'Output artefacts directory for Markdown input')
            [CompletionResult]::new('--artefacts', '--artefacts', [CompletionResultType]::ParameterName, 'Output artefacts directory for Markdown input')
            [CompletionResult]::new('-j', '-j', [CompletionResultType]::ParameterName, 'Parallel jobs for Markdown input. Defaults and maxima come from the resource profile')
            [CompletionResult]::new('--jobs', '--jobs', [CompletionResultType]::ParameterName, 'Parallel jobs for Markdown input. Defaults and maxima come from the resource profile')
            [CompletionResult]::new('-e', '-e', [CompletionResultType]::ParameterName, 'Output format. Defaults to the output extension, then SVG')
            [CompletionResult]::new('--outputFormat', '--outputFormat', [CompletionResultType]::ParameterName, 'Output format. Defaults to the output extension, then SVG')
            [CompletionResult]::new('--format', '--format', [CompletionResultType]::ParameterName, 'Output format. Defaults to the output extension, then SVG')
            [CompletionResult]::new('--svg-pipeline', '--svg-pipeline', [CompletionResultType]::ParameterName, 'SVG output pipeline. Compiled binary exports always start from resvg-safe')
            [CompletionResult]::new('-b', '-b', [CompletionResultType]::ParameterName, 'Background color for the selected rendered output. `mmdc` defaults to white')
            [CompletionResult]::new('--backgroundColor', '--backgroundColor', [CompletionResultType]::ParameterName, 'Background color for the selected rendered output. `mmdc` defaults to white')
            [CompletionResult]::new('-C', '-C ', [CompletionResultType]::ParameterName, 'CSS file injected into SVG output before export')
            [CompletionResult]::new('--cssFile', '--cssFile', [CompletionResultType]::ParameterName, 'CSS file injected into SVG output before export')
            [CompletionResult]::new('-p', '-p', [CompletionResultType]::ParameterName, 'JSON Puppeteer configuration file. Accepted for mmdc compatibility')
            [CompletionResult]::new('--puppeteerConfigFile', '--puppeteerConfigFile', [CompletionResultType]::ParameterName, 'JSON Puppeteer configuration file. Accepted for mmdc compatibility')
            [CompletionResult]::new('-s', '-s', [CompletionResultType]::ParameterName, 'Raster output scale factor. Defaults to 1')
            [CompletionResult]::new('--scale', '--scale', [CompletionResultType]::ParameterName, 'Raster output scale factor. Defaults to 1')
            [CompletionResult]::new('--raster-fit-width', '--raster-fit-width', [CompletionResultType]::ParameterName, 'Fit raster output to this CSS-pixel width before applying --scale')
            [CompletionResult]::new('--raster-fit-height', '--raster-fit-height', [CompletionResultType]::ParameterName, 'Fit raster output to this CSS-pixel height before applying --scale')
            [CompletionResult]::new('--raster-max-width', '--raster-max-width', [CompletionResultType]::ParameterName, 'Maximum raster output width after scale and fit. Defaults to 4096')
            [CompletionResult]::new('--raster-max-height', '--raster-max-height', [CompletionResultType]::ParameterName, 'Maximum raster output height after scale and fit. Defaults to 4096')
            [CompletionResult]::new('--raster-max-pixels', '--raster-max-pixels', [CompletionResultType]::ParameterName, 'Maximum raster output pixels after scale and fit. Defaults to 4096*4096')
            [CompletionResult]::new('--pdf-filter-scale', '--pdf-filter-scale', [CompletionResultType]::ParameterName, 'Sampling scale for SVG filters that require localized PDF bitmaps. Defaults to 4')
            [CompletionResult]::new('--pdf-max-filter-image-pixels', '--pdf-max-filter-image-pixels', [CompletionResultType]::ParameterName, 'Maximum aggregate pixels retained as localized PDF filter images. Defaults to 33554432')
            [CompletionResult]::new('--pdf-max-filter-pixels', '--pdf-max-filter-pixels', [CompletionResultType]::ParameterName, 'Maximum aggregate pixels retained as localized PDF filter images. Defaults to 33554432')
            [CompletionResult]::new('--embedded-image-max-bytes', '--embedded-image-max-bytes', [CompletionResultType]::ParameterName, 'Maximum decoded data-URL bytes for one embedded image. Defaults to 16777216')
            [CompletionResult]::new('--embedded-image-max-total-bytes', '--embedded-image-max-total-bytes', [CompletionResultType]::ParameterName, 'Maximum aggregate decoded data-URL bytes for embedded images. Defaults to 33554432')
            [CompletionResult]::new('--embedded-image-max-pixels', '--embedded-image-max-pixels', [CompletionResultType]::ParameterName, 'Maximum intrinsic pixels for one embedded raster image. Defaults to 16777216')
            [CompletionResult]::new('--embedded-image-max-total-pixels', '--embedded-image-max-total-pixels', [CompletionResultType]::ParameterName, 'Maximum aggregate intrinsic pixels for embedded raster images. Defaults to 33554432')
            [CompletionResult]::new('--iconPacks', '--iconPacks', [CompletionResultType]::ParameterName, 'Iconify package names')
            [CompletionResult]::new('--iconPacksNamesAndUrls', '--iconPacksNamesAndUrls', [CompletionResultType]::ParameterName, 'Iconify prefix#url definitions')
            [CompletionResult]::new('-c', '-c', [CompletionResultType]::ParameterName, 'JSON Mermaid configuration file')
            [CompletionResult]::new('--configFile', '--configFile', [CompletionResultType]::ParameterName, 'JSON Mermaid configuration file')
            [CompletionResult]::new('-t', '-t', [CompletionResultType]::ParameterName, 'Theme of the chart')
            [CompletionResult]::new('--theme', '--theme', [CompletionResultType]::ParameterName, 'Theme of the chart')
            [CompletionResult]::new('--runtime', '--runtime', [CompletionResultType]::ParameterName, 'Runtime source for clock, local timezone, and operation randomness')
            [CompletionResult]::new('--fixed-today', '--fixed-today', [CompletionResultType]::ParameterName, 'Override the local "today" date for time-dependent diagrams')
            [CompletionResult]::new('--fixed-local-offset-minutes', '--fixed-local-offset-minutes', [CompletionResultType]::ParameterName, 'Override the local timezone offset in minutes for time-dependent diagrams')
            [CompletionResult]::new('--presentation-profile', '--presentation-profile', [CompletionResultType]::ParameterName, 'First-party presentation profile applied below explicit Mermaid configuration')
            [CompletionResult]::new('--text-measurer', '--text-measurer', [CompletionResultType]::ParameterName, 'Text measurement strategy')
            [CompletionResult]::new('--math-renderer', '--math-renderer', [CompletionResultType]::ParameterName, 'Math renderer override. Unspecified uses the compiled default')
            [CompletionResult]::new('-w', '-w', [CompletionResultType]::ParameterName, 'Width of the page')
            [CompletionResult]::new('--width', '--width', [CompletionResultType]::ParameterName, 'Width of the page')
            [CompletionResult]::new('-H', '-H ', [CompletionResultType]::ParameterName, 'Height of the page')
            [CompletionResult]::new('--height', '--height', [CompletionResultType]::ParameterName, 'Height of the page')
            [CompletionResult]::new('-I', '-I ', [CompletionResultType]::ParameterName, 'Root SVG id and internal marker prefix')
            [CompletionResult]::new('--svgId', '--svgId', [CompletionResultType]::ParameterName, 'Root SVG id and internal marker prefix')
            [CompletionResult]::new('--hand-drawn-seed', '--hand-drawn-seed', [CompletionResultType]::ParameterName, 'Stabilize rough/hand-drawn rendering where supported')
            [CompletionResult]::new('--resource-profile', '--resource-profile', [CompletionResultType]::ParameterName, 'Resource policy for input, semantic models, output, and CLI acquisition')
            [CompletionResult]::new('--resource-limit', '--resource-limit', [CompletionResultType]::ParameterName, 'Override a resource budget as STABLE_ID=POSITIVE_U64. Can be repeated')
            [CompletionResult]::new('--operation-timeout-ms', '--operation-timeout-ms', [CompletionResultType]::ParameterName, 'Cancel the complete command operation after this many milliseconds')
            [CompletionResult]::new('-f', '-f', [CompletionResultType]::ParameterName, 'Scale PDF to fit chart. Accepted for mmdc compatibility')
            [CompletionResult]::new('--pdfFit', '--pdfFit', [CompletionResultType]::ParameterName, 'Scale PDF to fit chart. Accepted for mmdc compatibility')
            [CompletionResult]::new('-q', '-q', [CompletionResultType]::ParameterName, 'Suppress non-error log output')
            [CompletionResult]::new('--quiet', '--quiet', [CompletionResultType]::ParameterName, 'Suppress non-error log output')
            [CompletionResult]::new('--raster-unbounded', '--raster-unbounded', [CompletionResultType]::ParameterName, 'Disable raster size limits. Use only for trusted oversized exports')
            [CompletionResult]::new('--pdf-filter-images-unbounded', '--pdf-filter-images-unbounded', [CompletionResultType]::ParameterName, 'Disable the retained PDF filter-image pixel budget for trusted inputs')
            [CompletionResult]::new('--pdf-filter-unbounded', '--pdf-filter-unbounded', [CompletionResultType]::ParameterName, 'Disable the retained PDF filter-image pixel budget for trusted inputs')
            [CompletionResult]::new('--embedded-images-unbounded', '--embedded-images-unbounded', [CompletionResultType]::ParameterName, 'Disable embedded raster image decode budgets for trusted inputs')
            [CompletionResult]::new('--allow-network', '--allow-network', [CompletionResultType]::ParameterName, 'Allow icon pack loading from HTTP(S) URLs')
            [CompletionResult]::new('--allow-private-network', '--allow-private-network', [CompletionResultType]::ParameterName, 'Allow explicitly configured icon URLs to resolve to private or loopback addresses')
            [CompletionResult]::new('--system-clock', '--system-clock', [CompletionResultType]::ParameterName, 'Use the system clock while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-timezone', '--system-timezone', [CompletionResultType]::ParameterName, 'Use the system local timezone while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-random', '--system-random', [CompletionResultType]::ParameterName, 'Use system randomness while keeping other runtime sources deterministic')
            [CompletionResult]::new('--system-timing', '--system-timing', [CompletionResultType]::ParameterName, 'Enable operation timing diagnostics through the compiled system timing adapter')
            [CompletionResult]::new('-h', '-h', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('--help', '--help', [CompletionResultType]::ParameterName, 'Print help (see more with ''--help'')')
            [CompletionResult]::new('-V', '-V ', [CompletionResultType]::ParameterName, 'Print version')
            [CompletionResult]::new('--version', '--version', [CompletionResultType]::ParameterName, 'Print version')
            break
        }
    })

    $completions.Where{ $_.CompletionText -like "$wordToComplete*" } |
        Sort-Object -Property ListItemText
}
