
use builtin;
use str;

set edit:completion:arg-completer[merman-cli] = {|@words|
    fn spaces {|n|
        builtin:repeat $n ' ' | str:join ''
    }
    fn cand {|text desc|
        edit:complex-candidate $text &display=$text' '(spaces (- 14 (wcswidth $text)))$desc
    }
    var command = 'merman-cli'
    for word $words[1..-1] {
        if (str:has-prefix $word '-') {
            break
        }
        set command = $command';'$word
    }
    var completions = [
        &'merman-cli'= {
            cand -h 'Print help (see more with ''--help'')'
            cand --help 'Print help (see more with ''--help'')'
            cand -V 'Print version'
            cand --version 'Print version'
            cand lint-rules 'List lint rule metadata'
            cand capabilities 'Print the compiled capabilities from the canonical capability descriptor'
            cand detect 'Detect the Mermaid diagram type'
            cand parse 'Parse Mermaid source and print the semantic JSON model'
            cand render 'Render one Mermaid diagram with Merman''s native interface'
            cand batch 'Render every Mermaid diagram in one Markdown document'
            cand lint 'Analyze Mermaid source and print diagnostics JSON or text'
            cand fix 'Apply non-conflicting diagnostics fixes to Mermaid or Markdown source'
            cand completion 'Generate shell completion scripts'
            cand layout 'Parse and layout Mermaid source, then print layout JSON'
            cand mmdc 'Render through the pinned mmdc-compatible interface'
        }
        &'merman-cli;lint-rules'= {
            cand --format 'Output format for rule metadata'
            cand --pretty 'Pretty-print JSON output'
            cand --configurable 'Only list rules that public lint configuration can reference'
            cand -h 'Print help'
            cand --help 'Print help'
            cand -V 'Print version'
            cand --version 'Print version'
        }
        &'merman-cli;capabilities'= {
            cand --json 'Emit the machine-readable capability document'
            cand -h 'Print help'
            cand --help 'Print help'
            cand -V 'Print version'
            cand --version 'Print version'
        }
        &'merman-cli;detect'= {
            cand --resource-profile 'Resource policy used to bound source acquisition'
            cand --resource-limit 'Override source bytes as max_source_bytes=POSITIVE_U64'
            cand -h 'Print help (see more with ''--help'')'
            cand --help 'Print help (see more with ''--help'')'
            cand -V 'Print version'
            cand --version 'Print version'
        }
        &'merman-cli;parse'= {
            cand -c 'JSON Mermaid configuration file'
            cand --config-file 'JSON Mermaid configuration file'
            cand -t 'Mermaid theme override'
            cand --theme 'Mermaid theme override'
            cand --runtime 'Runtime source for clock, local timezone, and operation randomness'
            cand --fixed-today 'Override the local "today" date for time-dependent diagrams'
            cand --fixed-local-offset-minutes 'Override the local timezone offset in minutes for time-dependent diagrams'
            cand --resource-profile 'Resource policy for input, semantic models, output, and CLI acquisition'
            cand --resource-limit 'Override a resource budget as STABLE_ID=POSITIVE_U64. Can be repeated'
            cand --pretty 'Pretty-print JSON output'
            cand --meta 'Include parse metadata alongside the model'
            cand --suppress-errors 'Emit an error diagram instead of failing on parse errors'
            cand --system-clock 'Use the system clock while keeping other runtime sources deterministic'
            cand --system-timezone 'Use the system local timezone while keeping other runtime sources deterministic'
            cand --system-random 'Use system randomness while keeping other runtime sources deterministic'
            cand --system-timing 'Enable operation timing diagnostics through the compiled system timing adapter'
            cand -h 'Print help (see more with ''--help'')'
            cand --help 'Print help (see more with ''--help'')'
            cand -V 'Print version'
            cand --version 'Print version'
        }
        &'merman-cli;render'= {
            cand -o 'Output file. Use `-` for stdout'
            cand --output 'Output file. Use `-` for stdout'
            cand --input-kind 'Interpret the input as Mermaid source or an existing SVG document'
            cand -f 'Output format. Defaults to the first compiled output format'
            cand --format 'Output format. Defaults to the first compiled output format'
            cand --svg-pipeline 'SVG output pipeline. Compiled binary exports always start from resvg-safe'
            cand -b 'Background color for the selected rendered output'
            cand --background 'Background color for the selected rendered output'
            cand -C 'CSS file injected into SVG output before export'
            cand --css-file 'CSS file injected into SVG output before export'
            cand -s 'Raster output scale factor. Defaults to 1'
            cand --scale 'Raster output scale factor. Defaults to 1'
            cand --raster-fit-width 'Fit raster output to this CSS-pixel width before applying --scale'
            cand --raster-fit-height 'Fit raster output to this CSS-pixel height before applying --scale'
            cand --raster-max-width 'Maximum raster output width after scale and fit. Defaults to 4096'
            cand --raster-max-height 'Maximum raster output height after scale and fit. Defaults to 4096'
            cand --raster-max-pixels 'Maximum raster output pixels after scale and fit. Defaults to 4096*4096'
            cand --pdf-filter-scale 'Sampling scale for SVG filters that require localized PDF bitmaps. Defaults to 4'
            cand --pdf-max-filter-image-pixels 'Maximum aggregate pixels retained as localized PDF filter images. Defaults to 33554432'
            cand --pdf-max-filter-pixels 'Maximum aggregate pixels retained as localized PDF filter images. Defaults to 33554432'
            cand --embedded-image-max-bytes 'Maximum decoded data-URL bytes for one embedded image. Defaults to 16777216'
            cand --embedded-image-max-total-bytes 'Maximum aggregate decoded data-URL bytes for embedded images. Defaults to 33554432'
            cand --embedded-image-max-pixels 'Maximum intrinsic pixels for one embedded raster image. Defaults to 16777216'
            cand --embedded-image-max-total-pixels 'Maximum aggregate intrinsic pixels for embedded raster images. Defaults to 33554432'
            cand --icon-pack 'Iconify package name or local package path. Can be repeated'
            cand --icon-pack-source 'Iconify prefix and source as PREFIX#SOURCE. Can be repeated'
            cand -c 'JSON Mermaid configuration file'
            cand --config-file 'JSON Mermaid configuration file'
            cand -t 'Mermaid theme override'
            cand --theme 'Mermaid theme override'
            cand --runtime 'Runtime source for clock, local timezone, and operation randomness'
            cand --fixed-today 'Override the local "today" date for time-dependent diagrams'
            cand --fixed-local-offset-minutes 'Override the local timezone offset in minutes for time-dependent diagrams'
            cand --presentation-profile 'First-party presentation profile applied below explicit Mermaid configuration'
            cand --text-measurer 'Text measurement strategy'
            cand --math-renderer 'Math renderer override. Unspecified uses the compiled default; `ratex` requires `math`'
            cand -w 'Available container width for size-sensitive layouts'
            cand --width 'Available container width for size-sensitive layouts'
            cand -H 'Available container height for size-sensitive layouts'
            cand --height 'Available container height for size-sensitive layouts'
            cand -I 'Root SVG id and internal marker prefix'
            cand --svg-id 'Root SVG id and internal marker prefix'
            cand --hand-drawn-seed 'Stabilize rough/hand-drawn rendering where supported'
            cand --ascii-charset 'Override the text renderer character set'
            cand --ascii-width-profile 'Display-width convention used for terminal text measurement'
            cand --ascii-direction 'Override the default graph direction when Mermaid input omits one'
            cand --ascii-color 'Color mode for terminal text output'
            cand --xychart-vertical-plot-height 'XYChart vertical plot height for text output'
            cand --xychart-category-band-width 'XYChart category band width for text output'
            cand --xychart-horizontal-plot-width 'XYChart horizontal plot width for text output'
            cand --ascii-max-grid-cells 'Maximum graph grid cells for text route planning'
            cand --resource-profile 'Resource policy for input, semantic models, output, and CLI acquisition'
            cand --resource-limit 'Override a resource budget as STABLE_ID=POSITIVE_U64. Can be repeated'
            cand --operation-timeout-ms 'Cancel the complete render operation after this many milliseconds'
            cand -q 'Suppress non-error log output'
            cand --quiet 'Suppress non-error log output'
            cand --raster-unbounded 'Disable raster size limits. Use only for trusted oversized exports'
            cand --pdf-filter-images-unbounded 'Disable the retained PDF filter-image pixel budget for trusted inputs'
            cand --pdf-filter-unbounded 'Disable the retained PDF filter-image pixel budget for trusted inputs'
            cand --embedded-images-unbounded 'Disable embedded raster image decode budgets for trusted inputs'
            cand --allow-network 'Allow icon pack loading from public HTTP(S) destinations'
            cand --allow-private-network 'Allow explicitly configured icon URLs to resolve to private or loopback addresses'
            cand --suppress-errors 'Emit an error diagram instead of failing on parse errors'
            cand --system-clock 'Use the system clock while keeping other runtime sources deterministic'
            cand --system-timezone 'Use the system local timezone while keeping other runtime sources deterministic'
            cand --system-random 'Use system randomness while keeping other runtime sources deterministic'
            cand --system-timing 'Enable operation timing diagnostics through the compiled system timing adapter'
            cand --sequence-mirror-actors 'Mirror sequence participants below lifelines for ASCII/Unicode output'
            cand -h 'Print help (see more with ''--help'')'
            cand --help 'Print help (see more with ''--help'')'
            cand -V 'Print version'
            cand --version 'Print version'
        }
        &'merman-cli;batch'= {
            cand --stdin-file-name 'Logical source file name for Markdown read from stdin'
            cand -o 'Tool-owned directory for the rewritten document and generated artifacts'
            cand --output-dir 'Tool-owned directory for the rewritten document and generated artifacts'
            cand -j 'Maximum number of Markdown charts rendered concurrently'
            cand --jobs 'Maximum number of Markdown charts rendered concurrently'
            cand -f 'Output format. Defaults to SVG'
            cand --format 'Output format. Defaults to SVG'
            cand --svg-pipeline 'SVG output pipeline. Compiled binary exports always start from resvg-safe'
            cand -b 'Background color for the selected rendered output'
            cand --background 'Background color for the selected rendered output'
            cand -C 'CSS file injected into SVG output before export'
            cand --css-file 'CSS file injected into SVG output before export'
            cand -s 'Raster output scale factor. Defaults to 1'
            cand --scale 'Raster output scale factor. Defaults to 1'
            cand --raster-fit-width 'Fit raster output to this CSS-pixel width before applying --scale'
            cand --raster-fit-height 'Fit raster output to this CSS-pixel height before applying --scale'
            cand --raster-max-width 'Maximum raster output width after scale and fit. Defaults to 4096'
            cand --raster-max-height 'Maximum raster output height after scale and fit. Defaults to 4096'
            cand --raster-max-pixels 'Maximum raster output pixels after scale and fit. Defaults to 4096*4096'
            cand --pdf-filter-scale 'Sampling scale for SVG filters that require localized PDF bitmaps. Defaults to 4'
            cand --pdf-max-filter-image-pixels 'Maximum aggregate pixels retained as localized PDF filter images. Defaults to 33554432'
            cand --pdf-max-filter-pixels 'Maximum aggregate pixels retained as localized PDF filter images. Defaults to 33554432'
            cand --embedded-image-max-bytes 'Maximum decoded data-URL bytes for one embedded image. Defaults to 16777216'
            cand --embedded-image-max-total-bytes 'Maximum aggregate decoded data-URL bytes for embedded images. Defaults to 33554432'
            cand --embedded-image-max-pixels 'Maximum intrinsic pixels for one embedded raster image. Defaults to 16777216'
            cand --embedded-image-max-total-pixels 'Maximum aggregate intrinsic pixels for embedded raster images. Defaults to 33554432'
            cand --icon-pack 'Iconify package name or local package path. Can be repeated'
            cand --icon-pack-source 'Iconify prefix and source as PREFIX#SOURCE. Can be repeated'
            cand -c 'JSON Mermaid configuration file'
            cand --config-file 'JSON Mermaid configuration file'
            cand -t 'Mermaid theme override'
            cand --theme 'Mermaid theme override'
            cand --runtime 'Runtime source for clock, local timezone, and operation randomness'
            cand --fixed-today 'Override the local "today" date for time-dependent diagrams'
            cand --fixed-local-offset-minutes 'Override the local timezone offset in minutes for time-dependent diagrams'
            cand --presentation-profile 'First-party presentation profile applied below explicit Mermaid configuration'
            cand --text-measurer 'Text measurement strategy'
            cand --math-renderer 'Math renderer override. Unspecified uses the compiled default; `ratex` requires `math`'
            cand -w 'Available container width for size-sensitive layouts'
            cand --width 'Available container width for size-sensitive layouts'
            cand -H 'Available container height for size-sensitive layouts'
            cand --height 'Available container height for size-sensitive layouts'
            cand -I 'Root SVG id and internal marker prefix'
            cand --svg-id 'Root SVG id and internal marker prefix'
            cand --hand-drawn-seed 'Stabilize rough/hand-drawn rendering where supported'
            cand --resource-profile 'Resource policy for input, semantic models, output, and CLI acquisition'
            cand --resource-limit 'Override a resource budget as STABLE_ID=POSITIVE_U64. Can be repeated'
            cand --operation-timeout-ms 'Cancel the complete render operation after this many milliseconds'
            cand -q 'Suppress non-error log output'
            cand --quiet 'Suppress non-error log output'
            cand --raster-unbounded 'Disable raster size limits. Use only for trusted oversized exports'
            cand --pdf-filter-images-unbounded 'Disable the retained PDF filter-image pixel budget for trusted inputs'
            cand --pdf-filter-unbounded 'Disable the retained PDF filter-image pixel budget for trusted inputs'
            cand --embedded-images-unbounded 'Disable embedded raster image decode budgets for trusted inputs'
            cand --allow-network 'Allow icon pack loading from public HTTP(S) destinations'
            cand --allow-private-network 'Allow explicitly configured icon URLs to resolve to private or loopback addresses'
            cand --suppress-errors 'Emit an error diagram instead of failing on parse errors'
            cand --system-clock 'Use the system clock while keeping other runtime sources deterministic'
            cand --system-timezone 'Use the system local timezone while keeping other runtime sources deterministic'
            cand --system-random 'Use system randomness while keeping other runtime sources deterministic'
            cand --system-timing 'Enable operation timing diagnostics through the compiled system timing adapter'
            cand -h 'Print help (see more with ''--help'')'
            cand --help 'Print help (see more with ''--help'')'
            cand -V 'Print version'
            cand --version 'Print version'
        }
        &'merman-cli;lint'= {
            cand --stdin-file-name 'Optional file name to use when linting stdin'
            cand --format 'Output format for diagnostics'
            cand -c 'JSON Mermaid configuration file'
            cand --config-file 'JSON Mermaid configuration file'
            cand --runtime 'Runtime source for clock, local timezone, and operation randomness'
            cand --fixed-today 'Override the local "today" date for time-dependent diagrams'
            cand --fixed-local-offset-minutes 'Override the local timezone offset in minutes for time-dependent diagrams'
            cand --lint-profile 'Built-in lint rule profile: core, recommended, or strict'
            cand --enable-rule 'Enable a configurable lint rule by stable rule id. Can be repeated'
            cand --disable-rule 'Disable a configurable lint rule by stable rule id. Can be repeated'
            cand --rule-severity 'Override a configurable lint rule severity as RULE_ID=error|warning|info|hint. Can be repeated'
            cand --resource-profile 'Resource policy for input, semantic models, output, and CLI acquisition'
            cand --resource-limit 'Override a resource budget as STABLE_ID=POSITIVE_U64. Can be repeated'
            cand --pretty 'Pretty-print JSON output'
            cand --markdown 'Include Markdown fence diagnostics by scanning `.md`, `.markdown`, or `.mdx` input'
            cand --system-clock 'Use the system clock while keeping other runtime sources deterministic'
            cand --system-timezone 'Use the system local timezone while keeping other runtime sources deterministic'
            cand --system-random 'Use system randomness while keeping other runtime sources deterministic'
            cand --system-timing 'Enable operation timing diagnostics through the compiled system timing adapter'
            cand -h 'Print help (see more with ''--help'')'
            cand --help 'Print help (see more with ''--help'')'
            cand -V 'Print version'
            cand --version 'Print version'
        }
        &'merman-cli;fix'= {
            cand --stdin-file-name 'Optional file name to use when fixing stdin'
            cand -o 'Write the result to this file instead of stdout'
            cand --output 'Write the result to this file instead of stdout'
            cand --rule 'Restrict fixes to this fixable lint rule id. Can be repeated'
            cand --fix 'Select an exact stable fix id. Can be repeated'
            cand -c 'JSON Mermaid configuration file'
            cand --config-file 'JSON Mermaid configuration file'
            cand --runtime 'Runtime source for clock, local timezone, and operation randomness'
            cand --fixed-today 'Override the local "today" date for time-dependent diagrams'
            cand --fixed-local-offset-minutes 'Override the local timezone offset in minutes for time-dependent diagrams'
            cand --lint-profile 'Built-in lint rule profile: core, recommended, or strict'
            cand --enable-rule 'Enable a configurable lint rule by stable rule id. Can be repeated'
            cand --disable-rule 'Disable a configurable lint rule by stable rule id. Can be repeated'
            cand --rule-severity 'Override a configurable lint rule severity as RULE_ID=error|warning|info|hint. Can be repeated'
            cand --resource-profile 'Resource policy for input, semantic models, output, and CLI acquisition'
            cand --resource-limit 'Override a resource budget as STABLE_ID=POSITIVE_U64. Can be repeated'
            cand --check 'Exit 1 when the selected fixes would change the source'
            cand --diff 'Print a unified diff and exit 1 when the source would change'
            cand --write 'Write the result back to the input file'
            cand -q 'Suppress non-error fix selection diagnostics'
            cand --quiet 'Suppress non-error fix selection diagnostics'
            cand --markdown 'Include Markdown fence diagnostics by scanning `.md`, `.markdown`, or `.mdx` input'
            cand --system-clock 'Use the system clock while keeping other runtime sources deterministic'
            cand --system-timezone 'Use the system local timezone while keeping other runtime sources deterministic'
            cand --system-random 'Use system randomness while keeping other runtime sources deterministic'
            cand --system-timing 'Enable operation timing diagnostics through the compiled system timing adapter'
            cand -h 'Print help (see more with ''--help'')'
            cand --help 'Print help (see more with ''--help'')'
            cand -V 'Print version'
            cand --version 'Print version'
        }
        &'merman-cli;completion'= {
            cand -h 'Print help'
            cand --help 'Print help'
            cand -V 'Print version'
            cand --version 'Print version'
        }
        &'merman-cli;layout'= {
            cand -c 'JSON Mermaid configuration file'
            cand --config-file 'JSON Mermaid configuration file'
            cand -t 'Mermaid theme override'
            cand --theme 'Mermaid theme override'
            cand --runtime 'Runtime source for clock, local timezone, and operation randomness'
            cand --fixed-today 'Override the local "today" date for time-dependent diagrams'
            cand --fixed-local-offset-minutes 'Override the local timezone offset in minutes for time-dependent diagrams'
            cand --text-measurer 'Text measurement strategy'
            cand --math-renderer 'Math renderer override. Unspecified uses the compiled default; `ratex` requires `math`'
            cand -w 'Available container width for size-sensitive layouts'
            cand --width 'Available container width for size-sensitive layouts'
            cand -H 'Available container height for size-sensitive layouts'
            cand --height 'Available container height for size-sensitive layouts'
            cand --resource-profile 'Resource policy for input, semantic models, output, and CLI acquisition'
            cand --resource-limit 'Override a resource budget as STABLE_ID=POSITIVE_U64. Can be repeated'
            cand --pretty 'Pretty-print JSON output'
            cand --suppress-errors 'Emit an error diagram instead of failing on parse errors'
            cand --system-clock 'Use the system clock while keeping other runtime sources deterministic'
            cand --system-timezone 'Use the system local timezone while keeping other runtime sources deterministic'
            cand --system-random 'Use system randomness while keeping other runtime sources deterministic'
            cand --system-timing 'Enable operation timing diagnostics through the compiled system timing adapter'
            cand -h 'Print help (see more with ''--help'')'
            cand --help 'Print help (see more with ''--help'')'
            cand -V 'Print version'
            cand --version 'Print version'
        }
        &'merman-cli;mmdc'= {
            cand -i 'Input Mermaid file. Use `-` for stdin'
            cand --input 'Input Mermaid file. Use `-` for stdin'
            cand -o 'Output file. Use `-` for stdout'
            cand --output 'Output file. Use `-` for stdout'
            cand -a 'Output artefacts directory for Markdown input'
            cand --artefacts 'Output artefacts directory for Markdown input'
            cand -j 'Parallel jobs for Markdown input. Defaults and maxima come from the resource profile'
            cand --jobs 'Parallel jobs for Markdown input. Defaults and maxima come from the resource profile'
            cand -e 'Output format. Defaults to the output extension, then SVG'
            cand --outputFormat 'Output format. Defaults to the output extension, then SVG'
            cand --format 'Output format. Defaults to the output extension, then SVG'
            cand --svg-pipeline 'SVG output pipeline. Compiled binary exports always start from resvg-safe'
            cand -b 'Background color for the selected rendered output. `mmdc` defaults to white'
            cand --backgroundColor 'Background color for the selected rendered output. `mmdc` defaults to white'
            cand -C 'CSS file injected into SVG output before export'
            cand --cssFile 'CSS file injected into SVG output before export'
            cand -p 'JSON Puppeteer configuration file. Accepted for mmdc compatibility'
            cand --puppeteerConfigFile 'JSON Puppeteer configuration file. Accepted for mmdc compatibility'
            cand -s 'Raster output scale factor. Defaults to 1'
            cand --scale 'Raster output scale factor. Defaults to 1'
            cand --raster-fit-width 'Fit raster output to this CSS-pixel width before applying --scale'
            cand --raster-fit-height 'Fit raster output to this CSS-pixel height before applying --scale'
            cand --raster-max-width 'Maximum raster output width after scale and fit. Defaults to 4096'
            cand --raster-max-height 'Maximum raster output height after scale and fit. Defaults to 4096'
            cand --raster-max-pixels 'Maximum raster output pixels after scale and fit. Defaults to 4096*4096'
            cand --pdf-filter-scale 'Sampling scale for SVG filters that require localized PDF bitmaps. Defaults to 4'
            cand --pdf-max-filter-image-pixels 'Maximum aggregate pixels retained as localized PDF filter images. Defaults to 33554432'
            cand --pdf-max-filter-pixels 'Maximum aggregate pixels retained as localized PDF filter images. Defaults to 33554432'
            cand --embedded-image-max-bytes 'Maximum decoded data-URL bytes for one embedded image. Defaults to 16777216'
            cand --embedded-image-max-total-bytes 'Maximum aggregate decoded data-URL bytes for embedded images. Defaults to 33554432'
            cand --embedded-image-max-pixels 'Maximum intrinsic pixels for one embedded raster image. Defaults to 16777216'
            cand --embedded-image-max-total-pixels 'Maximum aggregate intrinsic pixels for embedded raster images. Defaults to 33554432'
            cand --iconPacks 'Iconify package names'
            cand --iconPacksNamesAndUrls 'Iconify prefix#url definitions'
            cand -c 'JSON Mermaid configuration file'
            cand --configFile 'JSON Mermaid configuration file'
            cand -t 'Theme of the chart'
            cand --theme 'Theme of the chart'
            cand --runtime 'Runtime source for clock, local timezone, and operation randomness'
            cand --fixed-today 'Override the local "today" date for time-dependent diagrams'
            cand --fixed-local-offset-minutes 'Override the local timezone offset in minutes for time-dependent diagrams'
            cand --presentation-profile 'First-party presentation profile applied below explicit Mermaid configuration'
            cand --text-measurer 'Text measurement strategy'
            cand --math-renderer 'Math renderer override. Unspecified uses the compiled default'
            cand -w 'Width of the page'
            cand --width 'Width of the page'
            cand -H 'Height of the page'
            cand --height 'Height of the page'
            cand -I 'Root SVG id and internal marker prefix'
            cand --svgId 'Root SVG id and internal marker prefix'
            cand --hand-drawn-seed 'Stabilize rough/hand-drawn rendering where supported'
            cand --resource-profile 'Resource policy for input, semantic models, output, and CLI acquisition'
            cand --resource-limit 'Override a resource budget as STABLE_ID=POSITIVE_U64. Can be repeated'
            cand --operation-timeout-ms 'Cancel the complete render operation after this many milliseconds'
            cand -f 'Scale PDF to fit chart. Accepted for mmdc compatibility'
            cand --pdfFit 'Scale PDF to fit chart. Accepted for mmdc compatibility'
            cand -q 'Suppress non-error log output'
            cand --quiet 'Suppress non-error log output'
            cand --raster-unbounded 'Disable raster size limits. Use only for trusted oversized exports'
            cand --pdf-filter-images-unbounded 'Disable the retained PDF filter-image pixel budget for trusted inputs'
            cand --pdf-filter-unbounded 'Disable the retained PDF filter-image pixel budget for trusted inputs'
            cand --embedded-images-unbounded 'Disable embedded raster image decode budgets for trusted inputs'
            cand --allow-network 'Allow icon pack loading from HTTP(S) URLs'
            cand --allow-private-network 'Allow explicitly configured icon URLs to resolve to private or loopback addresses'
            cand --system-clock 'Use the system clock while keeping other runtime sources deterministic'
            cand --system-timezone 'Use the system local timezone while keeping other runtime sources deterministic'
            cand --system-random 'Use system randomness while keeping other runtime sources deterministic'
            cand --system-timing 'Enable operation timing diagnostics through the compiled system timing adapter'
            cand -h 'Print help (see more with ''--help'')'
            cand --help 'Print help (see more with ''--help'')'
            cand -V 'Print version'
            cand --version 'Print version'
        }
    ]
    $completions[$command]
}
