[package]
name = "merman-theme-fixtures"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
data-encoding.workspace = true
cssparser.workspace = true
json5.workspace = true
lol_html.workspace = true
merman-core = { path = "../merman-core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile = "3.27.0"
